version: "3.9"
services:
  postgres:
    image: postgres:14
    env_file: docker-compose.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    env_file: docker-compose.env
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./backend
    volumes:
      - ./backend:/app
        # mount .tox and egg-info sub folders to custom volumes
        # to avoid conflicts with host (e.g. tox lock overridden by container)
      - tox:/app/.tox/
      - egg-info:/app/msm.egg-info/
    ports:
      - "8000:8000"
      - "443:443"
    healthcheck:
      test: python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8000'))"
      interval: 30s
      timeout: 30s
      retries: 5

volumes:
  postgres-data:
  tox:
  egg-info:
