server {
    ssl_certificate     /root/certs/msm.crt;
    ssl_certificate_key /root/certs/msm.key;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_protocols       TLSv1.1 TLSv1.2 TLSv1.3;

    listen           443 ssl default_server;

    location / {
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}
