[tox]
requires =
    tox>=4.2
env_list =
    test
no_package = true

[testenv]
pass_env =
    POSTGRES_DB
    POSTGRES_HOST
    POSTGRES_PASSWORD
    POSTGRES_PORT
    POSTGRES_USER

[testenv:test]
deps =
    .[testing]
commands =
    pytest -vs {posargs}

[testenv:shell]
deps =
    -e .
    ipython
commands =
    ipython

[testenv:format]
deps =
    black
    isort
    pyproject-fmt
    tox-ini-fmt
commands =
    isort {[globals]lint_files}
    black -q {[globals]lint_files}
    - pyproject-fmt pyproject.toml
    - tox-ini-fmt tox.ini

[testenv:lint]
deps =
    black
    flake8
    flake8-pyproject
    isort
    pyproject-fmt
commands =
    isort --check-only --diff {[globals]lint_files}
    black --check {[globals]lint_files}
    flake8 {[globals]lint_files}
    pyproject-fmt --check pyproject.toml

[testenv:check]
deps =
    .[testing]
    mypy
commands =
    mypy {[globals]lint_files} {posargs}

[testenv:run]
deps =
    -e .
    uvicorn
    uvloop
    watchfiles
commands =
    uvicorn --factory msm.user_api:create_app --host 0.0.0.0 --reload {posargs}

[globals]
lint_files =
    msm/ \
    tests/
