[tox]
requires =
    tox>=4.2
env_list =
    test
no_package = true

[testenv]
deps =
    -r requirements.txt
    .[testing]
pass_env =
    MSM_*
commands =
    pytest -vs {posargs}

[testenv:test]
deps =
    -r requirements.txt
    .[testing]
    pytest-cov
commands =
    pytest -n auto --cov {posargs}

[testenv:shell]
deps =
    -e .
    -r requirements.txt
    ipython
commands =
    ipython --simple-prompt {posargs}

[testenv:format]
deps =
    black==23.3
    isort==5.12
    pyproject-fmt==0.11.1
    tox-ini-fmt==1.3
commands =
    isort {[globals]lint_files}
    black -q {[globals]lint_files}
    - pyproject-fmt pyproject.toml
    - tox-ini-fmt tox.ini

[testenv:lint]
deps =
    Flake8-pyproject==1.2.3
    black==23.3
    flake8==6
    isort==5.12
    pyproject-fmt==0.11.1
commands =
    isort --check-only --diff {[globals]lint_files}
    black --check {[globals]lint_files}
    flake8 {[globals]lint_files}
    pyproject-fmt --check pyproject.toml

[testenv:check]
deps =
    -r requirements.txt
    .[testing]
    mypy==1.5.1
commands =
    mypy {[globals]lint_files} {posargs}

[testenv:update-deps]
deps =
    pip-tools
commands =
    pip-compile -U -o requirements.txt pyproject.toml

[testenv:admin,api,sampledata]
deps =
    -e .
    -r requirements.txt
set_env =
    MSM_DEV_MODE = true
commands =
    msm-{envname} {posargs}

[globals]
lint_files =
    msm/ \
    tests/
