// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
  urlSearchParamsBodySerializer,
} from "./client";
import type {
  GetBootSourcesV1BootassetSourcesGetData,
  GetBootSourcesV1BootassetSourcesGetResponses,
  GetBootSourcesV1BootassetSourcesGetErrors,
  PostBootSourcesV1BootassetSourcesPostData,
  PostBootSourcesV1BootassetSourcesPostResponses,
  PostBootSourcesV1BootassetSourcesPostErrors,
  DeleteBootSourceV1BootassetSourcesIdDeleteData,
  DeleteBootSourceV1BootassetSourcesIdDeleteResponses,
  DeleteBootSourceV1BootassetSourcesIdDeleteErrors,
  GetBootSourceByIdV1BootassetSourcesIdGetData,
  GetBootSourceByIdV1BootassetSourcesIdGetResponses,
  GetBootSourceByIdV1BootassetSourcesIdGetErrors,
  PatchBootSourceV1BootassetSourcesIdPatchData,
  PatchBootSourceV1BootassetSourcesIdPatchResponses,
  PatchBootSourceV1BootassetSourcesIdPatchErrors,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponses,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetErrors,
  PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutData,
  PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutResponses,
  PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutErrors,
  PutBootSourceAssetsV1BootassetSourcesIdAssetsPutData,
  PutBootSourceAssetsV1BootassetSourcesIdAssetsPutResponses,
  PutBootSourceAssetsV1BootassetSourcesIdAssetsPutErrors,
  GetBootAssetItemV1BootassetItemsIdGetData,
  GetBootAssetItemV1BootassetItemsIdGetResponses,
  GetBootAssetItemV1BootassetItemsIdGetErrors,
  PatchBootAssetItemsV1BootassetItemsIdPatchData,
  PatchBootAssetItemsV1BootassetItemsIdPatchResponses,
  PatchBootAssetItemsV1BootassetItemsIdPatchErrors,
  DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetData,
  DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetResponses,
  DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetErrors,
  DownloadV1ImagesTrackRiskBootSourceIdFilePathGetData,
  DownloadV1ImagesTrackRiskBootSourceIdFilePathGetResponses,
  DownloadV1ImagesTrackRiskBootSourceIdFilePathGetErrors,
  PostImagesV1ImagesPostData,
  PostImagesV1ImagesPostResponses,
  PostImagesV1ImagesPostErrors,
  DeleteImagesV1ImagesRemovePostData,
  DeleteImagesV1ImagesRemovePostResponses,
  DeleteImagesV1ImagesRemovePostErrors,
  RefreshIndexV1RefreshIndexGetData,
  RefreshIndexV1RefreshIndexGetResponses,
  PostV1LoginPostData,
  PostV1LoginPostResponses,
  PostV1LoginPostErrors,
  SelectImagesV1SelectableImagesSelectPostData,
  SelectImagesV1SelectableImagesSelectPostResponses,
  SelectImagesV1SelectableImagesSelectPostErrors,
  GetSelectableImagesV1SelectableImagesGetData,
  GetSelectableImagesV1SelectableImagesGetResponses,
  GetSelectableImagesV1SelectableImagesGetErrors,
  GetSelectedImagesV1SelectedImagesGetData,
  GetSelectedImagesV1SelectedImagesGetResponses,
  GetSelectedImagesV1SelectedImagesGetErrors,
  RemoveSelectionsV1SelectedImagesRemovePostData,
  RemoveSelectionsV1SelectedImagesRemovePostResponses,
  RemoveSelectionsV1SelectedImagesRemovePostErrors,
  GetImageSourcesV1ImageSourcesGetData,
  GetImageSourcesV1ImageSourcesGetResponses,
  GetImageSourcesV1ImageSourcesGetErrors,
  GetV1SettingsGetData,
  GetV1SettingsGetResponses,
  GetV1SettingsGetErrors,
  PatchV1SettingsPatchData,
  PatchV1SettingsPatchResponses,
  PatchV1SettingsPatchErrors,
  GetPendingV1SitesPendingGetData,
  GetPendingV1SitesPendingGetResponses,
  GetPendingV1SitesPendingGetErrors,
  PostPendingV1SitesPendingPostData,
  PostPendingV1SitesPendingPostResponses,
  PostPendingV1SitesPendingPostErrors,
  DeleteManyV1SitesDeleteData,
  DeleteManyV1SitesDeleteResponses,
  DeleteManyV1SitesDeleteErrors,
  GetV1SitesGetData,
  GetV1SitesGetResponses,
  GetV1SitesGetErrors,
  GetCoordinatesV1SitesCoordinatesGetData,
  GetCoordinatesV1SitesCoordinatesGetResponses,
  GetCoordinatesV1SitesCoordinatesGetErrors,
  DeleteV1SitesIdDeleteData,
  DeleteV1SitesIdDeleteResponses,
  DeleteV1SitesIdDeleteErrors,
  GetIdV1SitesIdGetData,
  GetIdV1SitesIdGetResponses,
  GetIdV1SitesIdGetErrors,
  PatchV1SitesIdPatchData,
  PatchV1SitesIdPatchResponses,
  PatchV1SitesIdPatchErrors,
  DeleteManyV1TokensDeleteData,
  DeleteManyV1TokensDeleteResponses,
  DeleteManyV1TokensDeleteErrors,
  GetV1TokensGetData,
  GetV1TokensGetResponses,
  GetV1TokensGetErrors,
  PostV1TokensPostData,
  PostV1TokensPostResponses,
  PostV1TokensPostErrors,
  GetExportV1TokensExportGetData,
  GetExportV1TokensExportGetResponses,
  GetExportV1TokensExportGetErrors,
  DeleteV1TokensIdDeleteData,
  DeleteV1TokensIdDeleteResponses,
  DeleteV1TokensIdDeleteErrors,
  GetV1UsersGetData,
  GetV1UsersGetResponses,
  GetV1UsersGetErrors,
  PostV1UsersPostData,
  PostV1UsersPostResponses,
  PostV1UsersPostErrors,
  GetMeV1UsersMeGetData,
  GetMeV1UsersMeGetResponses,
  GetMeV1UsersMeGetErrors,
  PatchMeV1UsersMePatchData,
  PatchMeV1UsersMePatchResponses,
  PatchMeV1UsersMePatchErrors,
  PatchMePasswordV1UsersMePasswordPatchData,
  PatchMePasswordV1UsersMePasswordPatchResponses,
  PatchMePasswordV1UsersMePasswordPatchErrors,
  DeleteV1UsersIdDeleteData,
  DeleteV1UsersIdDeleteResponses,
  DeleteV1UsersIdDeleteErrors,
  GetIdV1UsersIdGetData,
  GetIdV1UsersIdGetResponses,
  GetIdV1UsersIdGetErrors,
  PatchV1UsersIdPatchData,
  PatchV1UsersIdPatchResponses,
  PatchV1UsersIdPatchErrors,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Boot Sources
 * Return boot sources.
 */
export const getBootSourcesV1BootassetSourcesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetBootSourcesV1BootassetSourcesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetBootSourcesV1BootassetSourcesGetResponses,
    GetBootSourcesV1BootassetSourcesGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources",
    ...options,
  });
};

/**
 * Post Boot Sources
 */
export const postBootSourcesV1BootassetSourcesPost = <ThrowOnError extends boolean = false>(
  options: Options<PostBootSourcesV1BootassetSourcesPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostBootSourcesV1BootassetSourcesPostResponses,
    PostBootSourcesV1BootassetSourcesPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Boot Source
 */
export const deleteBootSourceV1BootassetSourcesIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBootSourceV1BootassetSourcesIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteBootSourceV1BootassetSourcesIdDeleteResponses,
    DeleteBootSourceV1BootassetSourcesIdDeleteErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources/{id}",
    ...options,
  });
};

/**
 * Get Boot Source By Id
 */
export const getBootSourceByIdV1BootassetSourcesIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetBootSourceByIdV1BootassetSourcesIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBootSourceByIdV1BootassetSourcesIdGetResponses,
    GetBootSourceByIdV1BootassetSourcesIdGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources/{id}",
    ...options,
  });
};

/**
 * Patch Boot Source
 */
export const patchBootSourceV1BootassetSourcesIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchBootSourceV1BootassetSourcesIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchBootSourceV1BootassetSourcesIdPatchResponses,
    PatchBootSourceV1BootassetSourcesIdPatchErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Boot Source Selections
 * Return boot source selections.
 */
export const getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponses,
    GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources/{id}/selections",
    ...options,
  });
};

/**
 * Put Boot Source Avail Selections
 */
export const putBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutResponses,
    PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources/{id}/available-selections",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Put Boot Source Assets
 */
export const putBootSourceAssetsV1BootassetSourcesIdAssetsPut = <ThrowOnError extends boolean = false>(
  options: Options<PutBootSourceAssetsV1BootassetSourcesIdAssetsPutData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PutBootSourceAssetsV1BootassetSourcesIdAssetsPutResponses,
    PutBootSourceAssetsV1BootassetSourcesIdAssetsPutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources/{id}/assets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Boot Asset Item
 */
export const getBootAssetItemV1BootassetItemsIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetBootAssetItemV1BootassetItemsIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBootAssetItemV1BootassetItemsIdGetResponses,
    GetBootAssetItemV1BootassetItemsIdGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-items/{id}",
    ...options,
  });
};

/**
 * Patch Boot Asset Items
 */
export const patchBootAssetItemsV1BootassetItemsIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchBootAssetItemsV1BootassetItemsIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchBootAssetItemsV1BootassetItemsIdPatchResponses,
    PatchBootAssetItemsV1BootassetItemsIdPatchErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-items/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Download Index
 */
export const downloadIndexV1ImagesTrackRiskStreamsV1IndexPathGet = <ThrowOnError extends boolean = false>(
  options: Options<DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetResponses,
    DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/v1/images/{track}/{risk}/streams/v1/{index_path}",
    ...options,
  });
};

/**
 * Download
 */
export const downloadV1ImagesTrackRiskBootSourceIdFilePathGet = <ThrowOnError extends boolean = false>(
  options: Options<DownloadV1ImagesTrackRiskBootSourceIdFilePathGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    DownloadV1ImagesTrackRiskBootSourceIdFilePathGetResponses,
    DownloadV1ImagesTrackRiskBootSourceIdFilePathGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/v1/images/{track}/{risk}/{boot_source_id}/{file_path}",
    ...options,
  });
};

/**
 * Post Images
 */
export const postImagesV1ImagesPost = <ThrowOnError extends boolean = false>(
  options: Options<PostImagesV1ImagesPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostImagesV1ImagesPostResponses,
    PostImagesV1ImagesPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/images",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * Delete Images
 */
export const deleteImagesV1ImagesRemovePost = <ThrowOnError extends boolean = false>(
  options: Options<DeleteImagesV1ImagesRemovePostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    DeleteImagesV1ImagesRemovePostResponses,
    DeleteImagesV1ImagesRemovePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/images:remove",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Refresh Index
 */
export const refreshIndexV1RefreshIndexGet = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshIndexV1RefreshIndexGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<RefreshIndexV1RefreshIndexGetResponses, unknown, ThrowOnError>({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/refresh-index",
    ...options,
  });
};

/**
 * Post
 */
export const postV1LoginPost = <ThrowOnError extends boolean = false>(
  options: Options<PostV1LoginPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<PostV1LoginPostResponses, PostV1LoginPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/v1/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
};

/**
 * Select Images
 */
export const selectImagesV1SelectableImagesSelectPost = <ThrowOnError extends boolean = false>(
  options: Options<SelectImagesV1SelectableImagesSelectPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    SelectImagesV1SelectableImagesSelectPostResponses,
    SelectImagesV1SelectableImagesSelectPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/selectable-images:select",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Selectable Images
 */
export const getSelectableImagesV1SelectableImagesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetSelectableImagesV1SelectableImagesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetSelectableImagesV1SelectableImagesGetResponses,
    GetSelectableImagesV1SelectableImagesGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/selectable-images",
    ...options,
  });
};

/**
 * Get Selected Images
 */
export const getSelectedImagesV1SelectedImagesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetSelectedImagesV1SelectedImagesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetSelectedImagesV1SelectedImagesGetResponses,
    GetSelectedImagesV1SelectedImagesGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/selected-images",
    ...options,
  });
};

/**
 * Remove Selections
 */
export const removeSelectionsV1SelectedImagesRemovePost = <ThrowOnError extends boolean = false>(
  options: Options<RemoveSelectionsV1SelectedImagesRemovePostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    RemoveSelectionsV1SelectedImagesRemovePostResponses,
    RemoveSelectionsV1SelectedImagesRemovePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/selected-images:remove",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Image Sources
 */
export const getImageSourcesV1ImageSourcesGet = <ThrowOnError extends boolean = false>(
  options: Options<GetImageSourcesV1ImageSourcesGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetImageSourcesV1ImageSourcesGetResponses,
    GetImageSourcesV1ImageSourcesGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/image-sources",
    ...options,
  });
};

/**
 * Get
 * Return service settings.
 */
export const getV1SettingsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1SettingsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetV1SettingsGetResponses, GetV1SettingsGetErrors, ThrowOnError>({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/settings",
    ...options,
  });
};

/**
 * Patch
 */
export const patchV1SettingsPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchV1SettingsPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchV1SettingsPatchResponses,
    PatchV1SettingsPatchErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/settings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Pending
 * Return pending sites.
 */
export const getPendingV1SitesPendingGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetPendingV1SitesPendingGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetPendingV1SitesPendingGetResponses,
    GetPendingV1SitesPendingGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/pending",
    ...options,
  });
};

/**
 * Post Pending
 * Accept or reject pending sites.
 */
export const postPendingV1SitesPendingPost = <ThrowOnError extends boolean = false>(
  options: Options<PostPendingV1SitesPendingPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostPendingV1SitesPendingPostResponses,
    PostPendingV1SitesPendingPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/pending",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Many
 * Delete multiple sites from the database.
 */
export const deleteManyV1SitesDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteManyV1SitesDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteManyV1SitesDeleteResponses,
    DeleteManyV1SitesDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites",
    ...options,
  });
};

/**
 * Get
 * Return accepted sites.
 */
export const getV1SitesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1SitesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetV1SitesGetResponses, GetV1SitesGetErrors, ThrowOnError>({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites",
    ...options,
  });
};

/**
 * Get Coordinates
 * Return coordinates for all accepted sites.
 */
export const getCoordinatesV1SitesCoordinatesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetCoordinatesV1SitesCoordinatesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCoordinatesV1SitesCoordinatesGetResponses,
    GetCoordinatesV1SitesCoordinatesGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/coordinates",
    ...options,
  });
};

/**
 * Delete
 * Delete a site from the database.
 */
export const deleteV1SitesIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1SitesIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteV1SitesIdDeleteResponses,
    DeleteV1SitesIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/{id}",
    ...options,
  });
};

/**
 * Get Id
 * Return a specific site.
 */
export const getIdV1SitesIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetIdV1SitesIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetIdV1SitesIdGetResponses, GetIdV1SitesIdGetErrors, ThrowOnError>({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/{id}",
    ...options,
  });
};

/**
 * Patch
 * Modify a site.
 */
export const patchV1SitesIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchV1SitesIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<PatchV1SitesIdPatchResponses, PatchV1SitesIdPatchErrors, ThrowOnError>(
    {
      responseType: "json",
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/v1/sites/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    },
  );
};

/**
 * Delete Many
 * Delete several tokens from the database
 */
export const deleteManyV1TokensDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteManyV1TokensDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteManyV1TokensDeleteResponses,
    DeleteManyV1TokensDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/tokens",
    ...options,
  });
};

/**
 * Get
 * Return all tokens.
 */
export const getV1TokensGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1TokensGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetV1TokensGetResponses, GetV1TokensGetErrors, ThrowOnError>({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/tokens",
    ...options,
  });
};

/**
 * Post
 * Create enrollment tokens for sites.
 *
 * Token duration (TTL) is expressed as an ISO-8601 duration string.
 */
export const postV1TokensPost = <ThrowOnError extends boolean = false>(
  options: Options<PostV1TokensPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<PostV1TokensPostResponses, PostV1TokensPostErrors, ThrowOnError>({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/tokens",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Export
 * Return the list of active tokens in CSV format.
 */
export const getExportV1TokensExportGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetExportV1TokensExportGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetExportV1TokensExportGetResponses,
    GetExportV1TokensExportGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/tokens/export",
    ...options,
  });
};

/**
 * Delete
 * Delete a token from the database.
 */
export const deleteV1TokensIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1TokensIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteV1TokensIdDeleteResponses,
    DeleteV1TokensIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/tokens/{id}",
    ...options,
  });
};

/**
 * Get
 * Return all users
 */
export const getV1UsersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1UsersGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetV1UsersGetResponses, GetV1UsersGetErrors, ThrowOnError>({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users",
    ...options,
  });
};

/**
 * Post
 * Create a user.
 */
export const postV1UsersPost = <ThrowOnError extends boolean = false>(
  options: Options<PostV1UsersPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<PostV1UsersPostResponses, PostV1UsersPostErrors, ThrowOnError>({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Me
 * Render info about the authenticated user.
 */
export const getMeV1UsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMeV1UsersMeGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetMeV1UsersMeGetResponses, GetMeV1UsersMeGetErrors, ThrowOnError>({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/me",
    ...options,
  });
};

/**
 * Patch Me
 * Update the details for a user
 */
export const patchMeV1UsersMePatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchMeV1UsersMePatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchMeV1UsersMePatchResponses,
    PatchMeV1UsersMePatchErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Patch Me Password
 * Modify the users password.
 */
export const patchMePasswordV1UsersMePasswordPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchMePasswordV1UsersMePasswordPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchMePasswordV1UsersMePasswordPatchResponses,
    PatchMePasswordV1UsersMePasswordPatchErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/me/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete
 * Delete a user from the database.
 */
export const deleteV1UsersIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1UsersIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteV1UsersIdDeleteResponses,
    DeleteV1UsersIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/{id}",
    ...options,
  });
};

/**
 * Get Id
 * Select a specific user
 */
export const getIdV1UsersIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetIdV1UsersIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetIdV1UsersIdGetResponses, GetIdV1UsersIdGetErrors, ThrowOnError>({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/{id}",
    ...options,
  });
};

/**
 * Patch
 * Admin action to update the details for a user.
 */
export const patchV1UsersIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchV1UsersIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<PatchV1UsersIdPatchResponses, PatchV1UsersIdPatchErrors, ThrowOnError>(
    {
      responseType: "json",
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/v1/users/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    },
  );
};
