// This file is auto-generated by @hey-api/openapi-ts

/**
 * AccessTokenResponse
 * Content for a response returning a JWT.
 */
export type AccessTokenResponse = {
  /**
   * Token Type
   */
  token_type: string;
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Rotation Interval Minutes
   */
  rotation_interval_minutes: number;
};

export type AvailableBootSourceSelection = [string, string, BootAssetLabel, string];

/**
 * BadRequestErrorBodyResponse
 */
export type BadRequestErrorBodyResponse = {
  code?: ExceptionCode;
  /**
   * Message
   */
  message?: string;
  /**
   * Details
   */
  details?: Array<BaseExceptionDetail> | null;
};

/**
 * BadRequestErrorResponseModel
 */
export type BadRequestErrorResponseModel = {
  error: BadRequestErrorBodyResponse;
};

/**
 * BaseExceptionDetail
 * Additional details for an exception.
 */
export type BaseExceptionDetail = {
  /**
   * Reason
   */
  reason: string;
  /**
   * Messages
   */
  messages: Array<string>;
  /**
   * Field
   */
  field?: string | null;
  /**
   * Location
   */
  location?: string | null;
};

/**
 * Body_post_v1_login_post
 */
export type BodyPostV1LoginPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * BootAssetItemGetResponse
 */
export type BootAssetItemGetResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Boot Asset Version Id
   */
  boot_asset_version_id?: number | null;
  ftype: ItemFileType;
  /**
   * Sha256
   */
  sha256: string;
  /**
   * Path
   */
  path: string;
  /**
   * File Size
   */
  file_size: number;
  /**
   * Source Package
   */
  source_package?: string | null;
  /**
   * Source Version
   */
  source_version?: string | null;
  /**
   * Source Release
   */
  source_release?: string | null;
  /**
   * Bytes Synced
   */
  bytes_synced: number;
};

/**
 * BootAssetItemPatchRequest
 */
export type BootAssetItemPatchRequest = {
  /**
   * Ftype
   */
  ftype?: string | null;
  /**
   * Source Package
   */
  source_package?: string | null;
  /**
   * Source Version
   */
  source_version?: string | null;
  /**
   * Source Release
   */
  source_release?: string | null;
  /**
   * Bytes Synced
   */
  bytes_synced?: number | null;
};

/**
 * BootAssetItemPatchResponse
 */
export type BootAssetItemPatchResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Boot Asset Version Id
   */
  boot_asset_version_id?: number | null;
  ftype: ItemFileType;
  /**
   * Sha256
   */
  sha256: string;
  /**
   * Path
   */
  path: string;
  /**
   * File Size
   */
  file_size: number;
  /**
   * Source Package
   */
  source_package?: string | null;
  /**
   * Source Version
   */
  source_version?: string | null;
  /**
   * Source Release
   */
  source_release?: string | null;
  /**
   * Bytes Synced
   */
  bytes_synced: number;
};

/**
 * BootAssetKind
 */
export enum BootAssetKind {
  _0 = 0,
  _1 = 1,
}

/**
 * BootAssetLabel
 */
export enum BootAssetLabel {
  STABLE = "stable",
  CANDIDATE = "candidate",
}

/**
 * BootSource
 */
export type BootSource = {
  /**
   * Id
   */
  id: number;
  /**
   * Priority
   */
  priority: number;
  /**
   * Url
   */
  url: string;
  /**
   * Name
   */
  name: string;
  /**
   * Keyring
   */
  keyring?: string | null;
  /**
   * Sync Interval
   */
  sync_interval: number;
  /**
   * Last Sync
   */
  last_sync: string;
};

/**
 * BootSourceAvailSelectionsPutRequest
 */
export type BootSourceAvailSelectionsPutRequest = {
  /**
   * Available
   */
  available: Array<AvailableBootSourceSelection>;
};

/**
 * BootSourceAvailSelectionsPutResponse
 */
export type BootSourceAvailSelectionsPutResponse = {
  /**
   * Stale
   */
  stale: Array<BootSourceSelection>;
};

/**
 * BootSourceGetResponse
 */
export type BootSourceGetResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Priority
   */
  priority: number;
  /**
   * Url
   */
  url: string;
  /**
   * Name
   */
  name: string;
  /**
   * Keyring
   */
  keyring?: string | null;
  /**
   * Sync Interval
   */
  sync_interval: number;
  /**
   * Last Sync
   */
  last_sync: string;
};

/**
 * BootSourcePatchResponse
 */
export type BootSourcePatchResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Priority
   */
  priority: number;
  /**
   * Url
   */
  url: string;
  /**
   * Name
   */
  name: string;
  /**
   * Keyring
   */
  keyring?: string | null;
  /**
   * Sync Interval
   */
  sync_interval: number;
  /**
   * Last Sync
   */
  last_sync: string;
};

/**
 * BootSourceSelection
 */
export type BootSourceSelection = {
  /**
   * Id
   */
  id: number;
  /**
   * Boot Source Id
   */
  boot_source_id: number;
  label: BootAssetLabel;
  /**
   * Os
   */
  os: string;
  /**
   * Release
   */
  release: string;
  /**
   * Arch
   */
  arch: string;
  /**
   * Selected
   */
  selected: boolean;
};

/**
 * BootSourceSelectionsGetResponse
 */
export type BootSourceSelectionsGetResponse = {
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Items
   */
  items: Array<BootSourceSelection>;
};

/**
 * BootSourcesAssetsPutRequest
 */
export type BootSourcesAssetsPutRequest = {
  /**
   * Products
   */
  products: Array<Product>;
};

/**
 * BootSourcesAssetsPutResponse
 */
export type BootSourcesAssetsPutResponse = {
  /**
   * To Download
   */
  to_download: Array<number>;
};

/**
 * BootSourcesGetResponse
 */
export type BootSourcesGetResponse = {
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Items
   */
  items: Array<BootSource>;
};

/**
 * BootSourcesPatchRequest
 */
export type BootSourcesPatchRequest = {
  /**
   * Priority
   */
  priority?: number | null;
  /**
   * Keyring
   */
  keyring?: string | null;
  /**
   * Sync Interval
   */
  sync_interval?: number | null;
  /**
   * Name
   */
  name?: string | null;
};

/**
 * BootSourcesPostRequest
 */
export type BootSourcesPostRequest = {
  /**
   * Priority
   */
  priority: number;
  /**
   * Url
   */
  url: string;
  /**
   * Keyring
   */
  keyring: string;
  /**
   * Sync Interval
   */
  sync_interval: number;
  /**
   * Name
   */
  name: string;
};

/**
 * BootSourcesPostResponse
 */
export type BootSourcesPostResponse = {
  /**
   * Id
   */
  id: number;
};

/**
 * ConnectionStatus
 */
export enum ConnectionStatus {
  STABLE = "stable",
  LOST = "lost",
  UNKNOWN = "unknown",
}

/**
 * Coordinates
 */
export type Coordinates = {
  /**
   * Latitude
   */
  latitude?: number;
  /**
   * Longitude
   */
  longitude?: number;
};

/**
 * ExceptionCode
 */
export enum ExceptionCode {
  ALREADY_EXISTS = "AlreadyExists",
  INVALID_CREDENTIALS = "InvalidCredentials",
  INVALID_PARAMETERS = "InvalidParameters",
  INVALID_PENDING_SITES = "InvalidPendingSites",
  INVALID_TOKEN = "InvalidToken",
  MISSING_RESOURCE = "MissingResource",
  MISSING_PERMISSIONS = "MissingPermissions",
  NOT_AUTHENTICATED = "NotAuthenticated",
  FILE_TOO_LARGE = "FileTooLarge",
}

/**
 * ForbiddenErrorBodyResponse
 */
export type ForbiddenErrorBodyResponse = {
  code?: ExceptionCode;
  /**
   * Message
   */
  message?: string;
  /**
   * Details
   */
  details?: Array<BaseExceptionDetail> | null;
};

/**
 * ForbiddenErrorResponseModel
 */
export type ForbiddenErrorResponseModel = {
  error: ForbiddenErrorBodyResponse;
};

/**
 * GetImageSourcesResponse
 */
export type GetImageSourcesResponse = {
  /**
   * Items
   */
  items: Array<ImageSource>;
};

/**
 * GetSelectableImagesResponse
 */
export type GetSelectableImagesResponse = {
  /**
   * Items
   */
  items: Array<SelectableImage>;
};

/**
 * GetSelectedImagesResponse
 */
export type GetSelectedImagesResponse = {
  /**
   * Items
   */
  items: Array<SelectedImage>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ImageSource
 */
export type ImageSource = {
  /**
   * Selection Id
   */
  selection_id: number;
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Url
   */
  url: string;
};

/**
 * ImagesPostResponse
 */
export type ImagesPostResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Boot Asset Version Id
   */
  boot_asset_version_id?: number | null;
  ftype: ItemFileType;
  /**
   * Sha256
   */
  sha256: string;
  /**
   * Path
   */
  path: string;
  /**
   * File Size
   */
  file_size: number;
  /**
   * Source Package
   */
  source_package?: string | null;
  /**
   * Source Version
   */
  source_version?: string | null;
  /**
   * Source Release
   */
  source_release?: string | null;
  /**
   * Bytes Synced
   */
  bytes_synced: number;
};

/**
 * ImagesRemovePostRequest
 */
export type ImagesRemovePostRequest = {
  /**
   * Asset Ids
   */
  asset_ids: Array<number>;
};

/**
 * ItemFileType
 */
export enum ItemFileType {
  ROOT_TGZ = "root-tgz",
  ROOT_TBZ = "root-tbz",
  ROOT_TXZ = "root-txz",
  ROOT_DD_TAR = "root-dd.tar",
  ROOT_DD_RAW = "root-dd.raw",
  ROOT_DD_BZ2 = "root-dd.bz2",
  ROOT_DD_GZ = "root-dd.gz",
  ROOT_DD_XZ = "root-dd.xz",
  ROOT_DD_TAR_BZ2 = "root-dd.tar.bz2",
  ROOT_DD_TAR_XZ = "root-dd.tar.xz",
  ROOT_DD = "root-dd",
  ROOT_IMAGE_GZ = "root-image.gz",
  SQUASHFS = "squashfs",
  BOOT_KERNEL = "boot-kernel",
  BOOT_INITRD = "boot-initrd",
  BOOT_DTB = "boot-dtb",
  ARCHIVE_TAR_XZ = "archive.tar.xz",
  MANIFEST = "manifest",
}

/**
 * NotFoundErrorBodyResponse
 */
export type NotFoundErrorBodyResponse = {
  code?: ExceptionCode;
  /**
   * Message
   */
  message?: string;
  /**
   * Details
   */
  details?: Array<BaseExceptionDetail> | null;
};

/**
 * NotFoundErrorResponseModel
 */
export type NotFoundErrorResponseModel = {
  error: NotFoundErrorBodyResponse;
};

/**
 * PendingSite
 * A pending MAAS site.
 */
export type PendingSite = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Url
   */
  url: string;
  /**
   * Cluster Uuid
   */
  cluster_uuid: string;
  /**
   * Created
   */
  created: string;
};

/**
 * PendingSitesGetResponse
 */
export type PendingSitesGetResponse = {
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Items
   */
  items: Array<PendingSite>;
};

/**
 * PendingSitesPostRequest
 * Request to accept/reject sites.
 */
export type PendingSitesPostRequest = {
  /**
   * Ids
   */
  ids: Array<number>;
  /**
   * Accept
   */
  accept: boolean;
};

/**
 * Product
 */
export type Product = {
  kind: BootAssetKind;
  label: BootAssetLabel;
  /**
   * Os
   */
  os: string;
  /**
   * Arch
   */
  arch: string;
  /**
   * Release
   */
  release?: string | null;
  /**
   * Codename
   */
  codename?: string | null;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Subarch
   */
  subarch?: string | null;
  /**
   * Compatibility
   */
  compatibility?: Array<string> | null;
  /**
   * Flavor
   */
  flavor?: string | null;
  /**
   * Base Image
   */
  base_image?: string | null;
  /**
   * Bootloader Type
   */
  bootloader_type?: string | null;
  /**
   * Eol
   */
  eol?: string | null;
  /**
   * Esm Eol
   */
  esm_eol?: string | null;
  /**
   * Signed
   */
  signed?: boolean;
  /**
   * Versions
   */
  versions: {
    [key: string]: Array<ProductItem>;
  };
};

/**
 * ProductItem
 */
export type ProductItem = {
  ftype: ItemFileType;
  /**
   * Sha256
   */
  sha256: string;
  /**
   * Path
   */
  path: string;
  /**
   * File Size
   */
  file_size: number;
  /**
   * Source Package
   */
  source_package?: string | null;
  /**
   * Source Version
   */
  source_version?: string | null;
  /**
   * Source Release
   */
  source_release?: string | null;
};

/**
 * RemoveSelectedImagesPostRequest
 */
export type RemoveSelectedImagesPostRequest = {
  /**
   * Selection Ids
   */
  selection_ids: Array<number>;
};

/**
 * SelectImagesPostRequest
 */
export type SelectImagesPostRequest = {
  /**
   * Selection Ids
   */
  selection_ids: Array<number>;
};

/**
 * SelectableImage
 */
export type SelectableImage = {
  /**
   * Selection Id
   */
  selection_id: number;
  /**
   * Os
   */
  os: string;
  /**
   * Release
   */
  release: string;
  /**
   * Arch
   */
  arch: string;
  /**
   * Boot Source Id
   */
  boot_source_id: number;
  /**
   * Boot Source Name
   */
  boot_source_name: string;
  /**
   * Boot Source Url
   */
  boot_source_url: string;
};

/**
 * SelectedImage
 */
export type SelectedImage = {
  /**
   * Boot Source Id
   */
  boot_source_id: number;
  /**
   * Boot Source Name
   */
  boot_source_name: string;
  /**
   * Boot Source Url
   */
  boot_source_url: string;
  /**
   * Os
   */
  os: string;
  /**
   * Arch
   */
  arch: string;
  /**
   * Release
   */
  release: string;
  /**
   * Size
   */
  size: number;
  /**
   * Downloaded
   */
  downloaded: number;
  /**
   * Custom Image Id
   */
  custom_image_id?: number | null;
  /**
   * Selection Id
   */
  selection_id?: number | null;
};

/**
 * Settings
 * Application settings that can be changed via the API.
 */
export type Settings = {
  /**
   * Max Image Upload Size Gb
   */
  max_image_upload_size_gb?: number;
  /**
   * Service Url
   */
  service_url?: string;
  /**
   * Token Lifetime Minutes
   */
  token_lifetime_minutes?: number;
  /**
   * Token Rotation Interval Minutes
   */
  token_rotation_interval_minutes?: number;
};

/**
 * SettingsUpdate
 * Change application settings.
 */
export type SettingsUpdate = {
  /**
   * Max Image Upload Size Gb
   */
  max_image_upload_size_gb?: number | null;
  /**
   * Service Url
   */
  service_url?: string | null;
  /**
   * Token Lifetime Minutes
   */
  token_lifetime_minutes?: number | null;
  /**
   * Token Rotation Interval Minutes
   */
  token_rotation_interval_minutes?: number | null;
};

/**
 * Site
 * A MAAS installation.
 */
export type Site = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * City
   */
  city?: string;
  /**
   * Country
   */
  country?: string;
  coordinates: Coordinates | null;
  /**
   * Note
   */
  note?: string;
  /**
   * State
   */
  state?: string;
  /**
   * Address
   */
  address?: string;
  /**
   * Postal Code
   */
  postal_code?: string;
  /**
   * Timezone
   */
  timezone?: TimeZone | "";
  /**
   * Url
   */
  url?: string;
  /**
   * Cluster Uuid
   */
  cluster_uuid: string;
  /**
   * Name Unique
   */
  name_unique: boolean;
  connection_status: ConnectionStatus;
  stats?: SiteData | null;
};

/**
 * SiteCoordinates
 * Coordinates for a MAAS site.
 */
export type SiteCoordinates = {
  /**
   * Id
   */
  id: number;
  coordinates?: Coordinates | null;
};

/**
 * SiteData
 * Data for a site.
 */
export type SiteData = {
  /**
   * Machines Total
   */
  machines_total: number;
  /**
   * Machines Allocated
   */
  machines_allocated: number;
  /**
   * Machines Deployed
   */
  machines_deployed: number;
  /**
   * Machines Ready
   */
  machines_ready: number;
  /**
   * Machines Error
   */
  machines_error: number;
  /**
   * Machines Other
   */
  machines_other: number;
  /**
   * Last Seen
   */
  last_seen: string;
};

/**
 * SiteUpdateRequest
 * Update a site.
 */
export type SiteUpdateRequest = {
  /**
   * City
   */
  city?: string | null;
  /**
   * Country
   */
  country?: string | null;
  coordinates?: Coordinates | null;
  /**
   * Note
   */
  note?: string | null;
  /**
   * State
   */
  state?: string | null;
  /**
   * Address
   */
  address?: string | null;
  /**
   * Postal Code
   */
  postal_code?: string | null;
  timezone?: TimeZone | null;
};

/**
 * SitesGetResponse
 * Response with paginated accepted sites.
 */
export type SitesGetResponse = {
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Items
   */
  items: Array<Site>;
};

/**
 * TimeZone
 */
export enum TimeZone {
  AFRICA_ABIDJAN = "Africa/Abidjan",
  AFRICA_ACCRA = "Africa/Accra",
  AFRICA_ADDIS_ABABA = "Africa/Addis_Ababa",
  AFRICA_ALGIERS = "Africa/Algiers",
  AFRICA_ASMARA = "Africa/Asmara",
  AFRICA_ASMERA = "Africa/Asmera",
  AFRICA_BAMAKO = "Africa/Bamako",
  AFRICA_BANGUI = "Africa/Bangui",
  AFRICA_BANJUL = "Africa/Banjul",
  AFRICA_BISSAU = "Africa/Bissau",
  AFRICA_BLANTYRE = "Africa/Blantyre",
  AFRICA_BRAZZAVILLE = "Africa/Brazzaville",
  AFRICA_BUJUMBURA = "Africa/Bujumbura",
  AFRICA_CAIRO = "Africa/Cairo",
  AFRICA_CASABLANCA = "Africa/Casablanca",
  AFRICA_CEUTA = "Africa/Ceuta",
  AFRICA_CONAKRY = "Africa/Conakry",
  AFRICA_DAKAR = "Africa/Dakar",
  AFRICA_DAR_ES_SALAAM = "Africa/Dar_es_Salaam",
  AFRICA_DJIBOUTI = "Africa/Djibouti",
  AFRICA_DOUALA = "Africa/Douala",
  AFRICA_EL_AAIUN = "Africa/El_Aaiun",
  AFRICA_FREETOWN = "Africa/Freetown",
  AFRICA_GABORONE = "Africa/Gaborone",
  AFRICA_HARARE = "Africa/Harare",
  AFRICA_JOHANNESBURG = "Africa/Johannesburg",
  AFRICA_JUBA = "Africa/Juba",
  AFRICA_KAMPALA = "Africa/Kampala",
  AFRICA_KHARTOUM = "Africa/Khartoum",
  AFRICA_KIGALI = "Africa/Kigali",
  AFRICA_KINSHASA = "Africa/Kinshasa",
  AFRICA_LAGOS = "Africa/Lagos",
  AFRICA_LIBREVILLE = "Africa/Libreville",
  AFRICA_LOME = "Africa/Lome",
  AFRICA_LUANDA = "Africa/Luanda",
  AFRICA_LUBUMBASHI = "Africa/Lubumbashi",
  AFRICA_LUSAKA = "Africa/Lusaka",
  AFRICA_MALABO = "Africa/Malabo",
  AFRICA_MAPUTO = "Africa/Maputo",
  AFRICA_MASERU = "Africa/Maseru",
  AFRICA_MBABANE = "Africa/Mbabane",
  AFRICA_MOGADISHU = "Africa/Mogadishu",
  AFRICA_MONROVIA = "Africa/Monrovia",
  AFRICA_NAIROBI = "Africa/Nairobi",
  AFRICA_NDJAMENA = "Africa/Ndjamena",
  AFRICA_NIAMEY = "Africa/Niamey",
  AFRICA_NOUAKCHOTT = "Africa/Nouakchott",
  AFRICA_OUAGADOUGOU = "Africa/Ouagadougou",
  AFRICA_PORTO_NOVO = "Africa/Porto-Novo",
  AFRICA_SAO_TOME = "Africa/Sao_Tome",
  AFRICA_TIMBUKTU = "Africa/Timbuktu",
  AFRICA_TRIPOLI = "Africa/Tripoli",
  AFRICA_TUNIS = "Africa/Tunis",
  AFRICA_WINDHOEK = "Africa/Windhoek",
  AMERICA_ADAK = "America/Adak",
  AMERICA_ANCHORAGE = "America/Anchorage",
  AMERICA_ANGUILLA = "America/Anguilla",
  AMERICA_ANTIGUA = "America/Antigua",
  AMERICA_ARAGUAINA = "America/Araguaina",
  AMERICA_ARGENTINA_BUENOS_AIRES = "America/Argentina/Buenos_Aires",
  AMERICA_ARGENTINA_CATAMARCA = "America/Argentina/Catamarca",
  AMERICA_ARGENTINA_COMOD_RIVADAVIA = "America/Argentina/ComodRivadavia",
  AMERICA_ARGENTINA_CORDOBA = "America/Argentina/Cordoba",
  AMERICA_ARGENTINA_JUJUY = "America/Argentina/Jujuy",
  AMERICA_ARGENTINA_LA_RIOJA = "America/Argentina/La_Rioja",
  AMERICA_ARGENTINA_MENDOZA = "America/Argentina/Mendoza",
  AMERICA_ARGENTINA_RIO_GALLEGOS = "America/Argentina/Rio_Gallegos",
  AMERICA_ARGENTINA_SALTA = "America/Argentina/Salta",
  AMERICA_ARGENTINA_SAN_JUAN = "America/Argentina/San_Juan",
  AMERICA_ARGENTINA_SAN_LUIS = "America/Argentina/San_Luis",
  AMERICA_ARGENTINA_TUCUMAN = "America/Argentina/Tucuman",
  AMERICA_ARGENTINA_USHUAIA = "America/Argentina/Ushuaia",
  AMERICA_ARUBA = "America/Aruba",
  AMERICA_ASUNCION = "America/Asuncion",
  AMERICA_ATIKOKAN = "America/Atikokan",
  AMERICA_ATKA = "America/Atka",
  AMERICA_BAHIA = "America/Bahia",
  AMERICA_BAHIA_BANDERAS = "America/Bahia_Banderas",
  AMERICA_BARBADOS = "America/Barbados",
  AMERICA_BELEM = "America/Belem",
  AMERICA_BELIZE = "America/Belize",
  AMERICA_BLANC_SABLON = "America/Blanc-Sablon",
  AMERICA_BOA_VISTA = "America/Boa_Vista",
  AMERICA_BOGOTA = "America/Bogota",
  AMERICA_BOISE = "America/Boise",
  AMERICA_BUENOS_AIRES = "America/Buenos_Aires",
  AMERICA_CAMBRIDGE_BAY = "America/Cambridge_Bay",
  AMERICA_CAMPO_GRANDE = "America/Campo_Grande",
  AMERICA_CANCUN = "America/Cancun",
  AMERICA_CARACAS = "America/Caracas",
  AMERICA_CATAMARCA = "America/Catamarca",
  AMERICA_CAYENNE = "America/Cayenne",
  AMERICA_CAYMAN = "America/Cayman",
  AMERICA_CHICAGO = "America/Chicago",
  AMERICA_CHIHUAHUA = "America/Chihuahua",
  AMERICA_CIUDAD_JUAREZ = "America/Ciudad_Juarez",
  AMERICA_CORAL_HARBOUR = "America/Coral_Harbour",
  AMERICA_CORDOBA = "America/Cordoba",
  AMERICA_COSTA_RICA = "America/Costa_Rica",
  AMERICA_CRESTON = "America/Creston",
  AMERICA_CUIABA = "America/Cuiaba",
  AMERICA_CURACAO = "America/Curacao",
  AMERICA_DANMARKSHAVN = "America/Danmarkshavn",
  AMERICA_DAWSON = "America/Dawson",
  AMERICA_DAWSON_CREEK = "America/Dawson_Creek",
  AMERICA_DENVER = "America/Denver",
  AMERICA_DETROIT = "America/Detroit",
  AMERICA_DOMINICA = "America/Dominica",
  AMERICA_EDMONTON = "America/Edmonton",
  AMERICA_EIRUNEPE = "America/Eirunepe",
  AMERICA_EL_SALVADOR = "America/El_Salvador",
  AMERICA_ENSENADA = "America/Ensenada",
  AMERICA_FORT_NELSON = "America/Fort_Nelson",
  AMERICA_FORT_WAYNE = "America/Fort_Wayne",
  AMERICA_FORTALEZA = "America/Fortaleza",
  AMERICA_GLACE_BAY = "America/Glace_Bay",
  AMERICA_GODTHAB = "America/Godthab",
  AMERICA_GOOSE_BAY = "America/Goose_Bay",
  AMERICA_GRAND_TURK = "America/Grand_Turk",
  AMERICA_GRENADA = "America/Grenada",
  AMERICA_GUADELOUPE = "America/Guadeloupe",
  AMERICA_GUATEMALA = "America/Guatemala",
  AMERICA_GUAYAQUIL = "America/Guayaquil",
  AMERICA_GUYANA = "America/Guyana",
  AMERICA_HALIFAX = "America/Halifax",
  AMERICA_HAVANA = "America/Havana",
  AMERICA_HERMOSILLO = "America/Hermosillo",
  AMERICA_INDIANA_INDIANAPOLIS = "America/Indiana/Indianapolis",
  AMERICA_INDIANA_KNOX = "America/Indiana/Knox",
  AMERICA_INDIANA_MARENGO = "America/Indiana/Marengo",
  AMERICA_INDIANA_PETERSBURG = "America/Indiana/Petersburg",
  AMERICA_INDIANA_TELL_CITY = "America/Indiana/Tell_City",
  AMERICA_INDIANA_VEVAY = "America/Indiana/Vevay",
  AMERICA_INDIANA_VINCENNES = "America/Indiana/Vincennes",
  AMERICA_INDIANA_WINAMAC = "America/Indiana/Winamac",
  AMERICA_INDIANAPOLIS = "America/Indianapolis",
  AMERICA_INUVIK = "America/Inuvik",
  AMERICA_IQALUIT = "America/Iqaluit",
  AMERICA_JAMAICA = "America/Jamaica",
  AMERICA_JUJUY = "America/Jujuy",
  AMERICA_JUNEAU = "America/Juneau",
  AMERICA_KENTUCKY_LOUISVILLE = "America/Kentucky/Louisville",
  AMERICA_KENTUCKY_MONTICELLO = "America/Kentucky/Monticello",
  AMERICA_KNOX_IN = "America/Knox_IN",
  AMERICA_KRALENDIJK = "America/Kralendijk",
  AMERICA_LA_PAZ = "America/La_Paz",
  AMERICA_LIMA = "America/Lima",
  AMERICA_LOS_ANGELES = "America/Los_Angeles",
  AMERICA_LOUISVILLE = "America/Louisville",
  AMERICA_LOWER_PRINCES = "America/Lower_Princes",
  AMERICA_MACEIO = "America/Maceio",
  AMERICA_MANAGUA = "America/Managua",
  AMERICA_MANAUS = "America/Manaus",
  AMERICA_MARIGOT = "America/Marigot",
  AMERICA_MARTINIQUE = "America/Martinique",
  AMERICA_MATAMOROS = "America/Matamoros",
  AMERICA_MAZATLAN = "America/Mazatlan",
  AMERICA_MENDOZA = "America/Mendoza",
  AMERICA_MENOMINEE = "America/Menominee",
  AMERICA_MERIDA = "America/Merida",
  AMERICA_METLAKATLA = "America/Metlakatla",
  AMERICA_MEXICO_CITY = "America/Mexico_City",
  AMERICA_MIQUELON = "America/Miquelon",
  AMERICA_MONCTON = "America/Moncton",
  AMERICA_MONTERREY = "America/Monterrey",
  AMERICA_MONTEVIDEO = "America/Montevideo",
  AMERICA_MONTREAL = "America/Montreal",
  AMERICA_MONTSERRAT = "America/Montserrat",
  AMERICA_NASSAU = "America/Nassau",
  AMERICA_NEW_YORK = "America/New_York",
  AMERICA_NIPIGON = "America/Nipigon",
  AMERICA_NOME = "America/Nome",
  AMERICA_NORONHA = "America/Noronha",
  AMERICA_NORTH_DAKOTA_BEULAH = "America/North_Dakota/Beulah",
  AMERICA_NORTH_DAKOTA_CENTER = "America/North_Dakota/Center",
  AMERICA_NORTH_DAKOTA_NEW_SALEM = "America/North_Dakota/New_Salem",
  AMERICA_NUUK = "America/Nuuk",
  AMERICA_OJINAGA = "America/Ojinaga",
  AMERICA_PANAMA = "America/Panama",
  AMERICA_PANGNIRTUNG = "America/Pangnirtung",
  AMERICA_PARAMARIBO = "America/Paramaribo",
  AMERICA_PHOENIX = "America/Phoenix",
  AMERICA_PORT_AU_PRINCE = "America/Port-au-Prince",
  AMERICA_PORT_OF_SPAIN = "America/Port_of_Spain",
  AMERICA_PORTO_ACRE = "America/Porto_Acre",
  AMERICA_PORTO_VELHO = "America/Porto_Velho",
  AMERICA_PUERTO_RICO = "America/Puerto_Rico",
  AMERICA_PUNTA_ARENAS = "America/Punta_Arenas",
  AMERICA_RAINY_RIVER = "America/Rainy_River",
  AMERICA_RANKIN_INLET = "America/Rankin_Inlet",
  AMERICA_RECIFE = "America/Recife",
  AMERICA_REGINA = "America/Regina",
  AMERICA_RESOLUTE = "America/Resolute",
  AMERICA_RIO_BRANCO = "America/Rio_Branco",
  AMERICA_ROSARIO = "America/Rosario",
  AMERICA_SANTA_ISABEL = "America/Santa_Isabel",
  AMERICA_SANTAREM = "America/Santarem",
  AMERICA_SANTIAGO = "America/Santiago",
  AMERICA_SANTO_DOMINGO = "America/Santo_Domingo",
  AMERICA_SAO_PAULO = "America/Sao_Paulo",
  AMERICA_SCORESBYSUND = "America/Scoresbysund",
  AMERICA_SHIPROCK = "America/Shiprock",
  AMERICA_SITKA = "America/Sitka",
  AMERICA_ST_BARTHELEMY = "America/St_Barthelemy",
  AMERICA_ST_JOHNS = "America/St_Johns",
  AMERICA_ST_KITTS = "America/St_Kitts",
  AMERICA_ST_LUCIA = "America/St_Lucia",
  AMERICA_ST_THOMAS = "America/St_Thomas",
  AMERICA_ST_VINCENT = "America/St_Vincent",
  AMERICA_SWIFT_CURRENT = "America/Swift_Current",
  AMERICA_TEGUCIGALPA = "America/Tegucigalpa",
  AMERICA_THULE = "America/Thule",
  AMERICA_THUNDER_BAY = "America/Thunder_Bay",
  AMERICA_TIJUANA = "America/Tijuana",
  AMERICA_TORONTO = "America/Toronto",
  AMERICA_TORTOLA = "America/Tortola",
  AMERICA_VANCOUVER = "America/Vancouver",
  AMERICA_VIRGIN = "America/Virgin",
  AMERICA_WHITEHORSE = "America/Whitehorse",
  AMERICA_WINNIPEG = "America/Winnipeg",
  AMERICA_YAKUTAT = "America/Yakutat",
  AMERICA_YELLOWKNIFE = "America/Yellowknife",
  ANTARCTICA_CASEY = "Antarctica/Casey",
  ANTARCTICA_DAVIS = "Antarctica/Davis",
  ANTARCTICA_DUMONT_D_URVILLE = "Antarctica/DumontDUrville",
  ANTARCTICA_MACQUARIE = "Antarctica/Macquarie",
  ANTARCTICA_MAWSON = "Antarctica/Mawson",
  ANTARCTICA_MC_MURDO = "Antarctica/McMurdo",
  ANTARCTICA_PALMER = "Antarctica/Palmer",
  ANTARCTICA_ROTHERA = "Antarctica/Rothera",
  ANTARCTICA_SOUTH_POLE = "Antarctica/South_Pole",
  ANTARCTICA_SYOWA = "Antarctica/Syowa",
  ANTARCTICA_TROLL = "Antarctica/Troll",
  ANTARCTICA_VOSTOK = "Antarctica/Vostok",
  ARCTIC_LONGYEARBYEN = "Arctic/Longyearbyen",
  ASIA_ADEN = "Asia/Aden",
  ASIA_ALMATY = "Asia/Almaty",
  ASIA_AMMAN = "Asia/Amman",
  ASIA_ANADYR = "Asia/Anadyr",
  ASIA_AQTAU = "Asia/Aqtau",
  ASIA_AQTOBE = "Asia/Aqtobe",
  ASIA_ASHGABAT = "Asia/Ashgabat",
  ASIA_ASHKHABAD = "Asia/Ashkhabad",
  ASIA_ATYRAU = "Asia/Atyrau",
  ASIA_BAGHDAD = "Asia/Baghdad",
  ASIA_BAHRAIN = "Asia/Bahrain",
  ASIA_BAKU = "Asia/Baku",
  ASIA_BANGKOK = "Asia/Bangkok",
  ASIA_BARNAUL = "Asia/Barnaul",
  ASIA_BEIRUT = "Asia/Beirut",
  ASIA_BISHKEK = "Asia/Bishkek",
  ASIA_BRUNEI = "Asia/Brunei",
  ASIA_CALCUTTA = "Asia/Calcutta",
  ASIA_CHITA = "Asia/Chita",
  ASIA_CHOIBALSAN = "Asia/Choibalsan",
  ASIA_CHONGQING = "Asia/Chongqing",
  ASIA_CHUNGKING = "Asia/Chungking",
  ASIA_COLOMBO = "Asia/Colombo",
  ASIA_DACCA = "Asia/Dacca",
  ASIA_DAMASCUS = "Asia/Damascus",
  ASIA_DHAKA = "Asia/Dhaka",
  ASIA_DILI = "Asia/Dili",
  ASIA_DUBAI = "Asia/Dubai",
  ASIA_DUSHANBE = "Asia/Dushanbe",
  ASIA_FAMAGUSTA = "Asia/Famagusta",
  ASIA_GAZA = "Asia/Gaza",
  ASIA_HARBIN = "Asia/Harbin",
  ASIA_HEBRON = "Asia/Hebron",
  ASIA_HO_CHI_MINH = "Asia/Ho_Chi_Minh",
  ASIA_HONG_KONG = "Asia/Hong_Kong",
  ASIA_HOVD = "Asia/Hovd",
  ASIA_IRKUTSK = "Asia/Irkutsk",
  ASIA_ISTANBUL = "Asia/Istanbul",
  ASIA_JAKARTA = "Asia/Jakarta",
  ASIA_JAYAPURA = "Asia/Jayapura",
  ASIA_JERUSALEM = "Asia/Jerusalem",
  ASIA_KABUL = "Asia/Kabul",
  ASIA_KAMCHATKA = "Asia/Kamchatka",
  ASIA_KARACHI = "Asia/Karachi",
  ASIA_KASHGAR = "Asia/Kashgar",
  ASIA_KATHMANDU = "Asia/Kathmandu",
  ASIA_KATMANDU = "Asia/Katmandu",
  ASIA_KHANDYGA = "Asia/Khandyga",
  ASIA_KOLKATA = "Asia/Kolkata",
  ASIA_KRASNOYARSK = "Asia/Krasnoyarsk",
  ASIA_KUALA_LUMPUR = "Asia/Kuala_Lumpur",
  ASIA_KUCHING = "Asia/Kuching",
  ASIA_KUWAIT = "Asia/Kuwait",
  ASIA_MACAO = "Asia/Macao",
  ASIA_MACAU = "Asia/Macau",
  ASIA_MAGADAN = "Asia/Magadan",
  ASIA_MAKASSAR = "Asia/Makassar",
  ASIA_MANILA = "Asia/Manila",
  ASIA_MUSCAT = "Asia/Muscat",
  ASIA_NICOSIA = "Asia/Nicosia",
  ASIA_NOVOKUZNETSK = "Asia/Novokuznetsk",
  ASIA_NOVOSIBIRSK = "Asia/Novosibirsk",
  ASIA_OMSK = "Asia/Omsk",
  ASIA_ORAL = "Asia/Oral",
  ASIA_PHNOM_PENH = "Asia/Phnom_Penh",
  ASIA_PONTIANAK = "Asia/Pontianak",
  ASIA_PYONGYANG = "Asia/Pyongyang",
  ASIA_QATAR = "Asia/Qatar",
  ASIA_QOSTANAY = "Asia/Qostanay",
  ASIA_QYZYLORDA = "Asia/Qyzylorda",
  ASIA_RANGOON = "Asia/Rangoon",
  ASIA_RIYADH = "Asia/Riyadh",
  ASIA_SAIGON = "Asia/Saigon",
  ASIA_SAKHALIN = "Asia/Sakhalin",
  ASIA_SAMARKAND = "Asia/Samarkand",
  ASIA_SEOUL = "Asia/Seoul",
  ASIA_SHANGHAI = "Asia/Shanghai",
  ASIA_SINGAPORE = "Asia/Singapore",
  ASIA_SREDNEKOLYMSK = "Asia/Srednekolymsk",
  ASIA_TAIPEI = "Asia/Taipei",
  ASIA_TASHKENT = "Asia/Tashkent",
  ASIA_TBILISI = "Asia/Tbilisi",
  ASIA_TEHRAN = "Asia/Tehran",
  ASIA_TEL_AVIV = "Asia/Tel_Aviv",
  ASIA_THIMBU = "Asia/Thimbu",
  ASIA_THIMPHU = "Asia/Thimphu",
  ASIA_TOKYO = "Asia/Tokyo",
  ASIA_TOMSK = "Asia/Tomsk",
  ASIA_UJUNG_PANDANG = "Asia/Ujung_Pandang",
  ASIA_ULAANBAATAR = "Asia/Ulaanbaatar",
  ASIA_ULAN_BATOR = "Asia/Ulan_Bator",
  ASIA_URUMQI = "Asia/Urumqi",
  ASIA_UST_NERA = "Asia/Ust-Nera",
  ASIA_VIENTIANE = "Asia/Vientiane",
  ASIA_VLADIVOSTOK = "Asia/Vladivostok",
  ASIA_YAKUTSK = "Asia/Yakutsk",
  ASIA_YANGON = "Asia/Yangon",
  ASIA_YEKATERINBURG = "Asia/Yekaterinburg",
  ASIA_YEREVAN = "Asia/Yerevan",
  ATLANTIC_AZORES = "Atlantic/Azores",
  ATLANTIC_BERMUDA = "Atlantic/Bermuda",
  ATLANTIC_CANARY = "Atlantic/Canary",
  ATLANTIC_CAPE_VERDE = "Atlantic/Cape_Verde",
  ATLANTIC_FAEROE = "Atlantic/Faeroe",
  ATLANTIC_FAROE = "Atlantic/Faroe",
  ATLANTIC_JAN_MAYEN = "Atlantic/Jan_Mayen",
  ATLANTIC_MADEIRA = "Atlantic/Madeira",
  ATLANTIC_REYKJAVIK = "Atlantic/Reykjavik",
  ATLANTIC_SOUTH_GEORGIA = "Atlantic/South_Georgia",
  ATLANTIC_ST_HELENA = "Atlantic/St_Helena",
  ATLANTIC_STANLEY = "Atlantic/Stanley",
  AUSTRALIA_ACT = "Australia/ACT",
  AUSTRALIA_ADELAIDE = "Australia/Adelaide",
  AUSTRALIA_BRISBANE = "Australia/Brisbane",
  AUSTRALIA_BROKEN_HILL = "Australia/Broken_Hill",
  AUSTRALIA_CANBERRA = "Australia/Canberra",
  AUSTRALIA_CURRIE = "Australia/Currie",
  AUSTRALIA_DARWIN = "Australia/Darwin",
  AUSTRALIA_EUCLA = "Australia/Eucla",
  AUSTRALIA_HOBART = "Australia/Hobart",
  AUSTRALIA_LHI = "Australia/LHI",
  AUSTRALIA_LINDEMAN = "Australia/Lindeman",
  AUSTRALIA_LORD_HOWE = "Australia/Lord_Howe",
  AUSTRALIA_MELBOURNE = "Australia/Melbourne",
  AUSTRALIA_NSW = "Australia/NSW",
  AUSTRALIA_NORTH = "Australia/North",
  AUSTRALIA_PERTH = "Australia/Perth",
  AUSTRALIA_QUEENSLAND = "Australia/Queensland",
  AUSTRALIA_SOUTH = "Australia/South",
  AUSTRALIA_SYDNEY = "Australia/Sydney",
  AUSTRALIA_TASMANIA = "Australia/Tasmania",
  AUSTRALIA_VICTORIA = "Australia/Victoria",
  AUSTRALIA_WEST = "Australia/West",
  AUSTRALIA_YANCOWINNA = "Australia/Yancowinna",
  BRAZIL_ACRE = "Brazil/Acre",
  BRAZIL_DE_NORONHA = "Brazil/DeNoronha",
  BRAZIL_EAST = "Brazil/East",
  BRAZIL_WEST = "Brazil/West",
  CET = "CET",
  CST6CDT = "CST6CDT",
  CANADA_ATLANTIC = "Canada/Atlantic",
  CANADA_CENTRAL = "Canada/Central",
  CANADA_EASTERN = "Canada/Eastern",
  CANADA_MOUNTAIN = "Canada/Mountain",
  CANADA_NEWFOUNDLAND = "Canada/Newfoundland",
  CANADA_PACIFIC = "Canada/Pacific",
  CANADA_SASKATCHEWAN = "Canada/Saskatchewan",
  CANADA_YUKON = "Canada/Yukon",
  CHILE_CONTINENTAL = "Chile/Continental",
  CHILE_EASTER_ISLAND = "Chile/EasterIsland",
  CUBA = "Cuba",
  EET = "EET",
  EST = "EST",
  EST5EDT = "EST5EDT",
  EGYPT = "Egypt",
  EIRE = "Eire",
  ETC_GMT = "Etc/GMT",
  "ETC_GMT+0" = "Etc/GMT+0",
  "ETC_GMT+1" = "Etc/GMT+1",
  "ETC_GMT+10" = "Etc/GMT+10",
  "ETC_GMT+11" = "Etc/GMT+11",
  "ETC_GMT+12" = "Etc/GMT+12",
  "ETC_GMT+2" = "Etc/GMT+2",
  "ETC_GMT+3" = "Etc/GMT+3",
  "ETC_GMT+4" = "Etc/GMT+4",
  "ETC_GMT+5" = "Etc/GMT+5",
  "ETC_GMT+6" = "Etc/GMT+6",
  "ETC_GMT+7" = "Etc/GMT+7",
  "ETC_GMT+8" = "Etc/GMT+8",
  "ETC_GMT+9" = "Etc/GMT+9",
  ETC_GMT_0 = "Etc/GMT-0",
  ETC_GMT_1 = "Etc/GMT-1",
  ETC_GMT_10 = "Etc/GMT-10",
  ETC_GMT_11 = "Etc/GMT-11",
  ETC_GMT_12 = "Etc/GMT-12",
  ETC_GMT_13 = "Etc/GMT-13",
  ETC_GMT_14 = "Etc/GMT-14",
  ETC_GMT_2 = "Etc/GMT-2",
  ETC_GMT_3 = "Etc/GMT-3",
  ETC_GMT_4 = "Etc/GMT-4",
  ETC_GMT_5 = "Etc/GMT-5",
  ETC_GMT_6 = "Etc/GMT-6",
  ETC_GMT_7 = "Etc/GMT-7",
  ETC_GMT_8 = "Etc/GMT-8",
  ETC_GMT_9 = "Etc/GMT-9",
  ETC_GMT0 = "Etc/GMT0",
  ETC_GREENWICH = "Etc/Greenwich",
  ETC_UCT = "Etc/UCT",
  ETC_UTC = "Etc/UTC",
  ETC_UNIVERSAL = "Etc/Universal",
  ETC_ZULU = "Etc/Zulu",
  EUROPE_AMSTERDAM = "Europe/Amsterdam",
  EUROPE_ANDORRA = "Europe/Andorra",
  EUROPE_ASTRAKHAN = "Europe/Astrakhan",
  EUROPE_ATHENS = "Europe/Athens",
  EUROPE_BELFAST = "Europe/Belfast",
  EUROPE_BELGRADE = "Europe/Belgrade",
  EUROPE_BERLIN = "Europe/Berlin",
  EUROPE_BRATISLAVA = "Europe/Bratislava",
  EUROPE_BRUSSELS = "Europe/Brussels",
  EUROPE_BUCHAREST = "Europe/Bucharest",
  EUROPE_BUDAPEST = "Europe/Budapest",
  EUROPE_BUSINGEN = "Europe/Busingen",
  EUROPE_CHISINAU = "Europe/Chisinau",
  EUROPE_COPENHAGEN = "Europe/Copenhagen",
  EUROPE_DUBLIN = "Europe/Dublin",
  EUROPE_GIBRALTAR = "Europe/Gibraltar",
  EUROPE_GUERNSEY = "Europe/Guernsey",
  EUROPE_HELSINKI = "Europe/Helsinki",
  EUROPE_ISLE_OF_MAN = "Europe/Isle_of_Man",
  EUROPE_ISTANBUL = "Europe/Istanbul",
  EUROPE_JERSEY = "Europe/Jersey",
  EUROPE_KALININGRAD = "Europe/Kaliningrad",
  EUROPE_KIEV = "Europe/Kiev",
  EUROPE_KIROV = "Europe/Kirov",
  EUROPE_KYIV = "Europe/Kyiv",
  EUROPE_LISBON = "Europe/Lisbon",
  EUROPE_LJUBLJANA = "Europe/Ljubljana",
  EUROPE_LONDON = "Europe/London",
  EUROPE_LUXEMBOURG = "Europe/Luxembourg",
  EUROPE_MADRID = "Europe/Madrid",
  EUROPE_MALTA = "Europe/Malta",
  EUROPE_MARIEHAMN = "Europe/Mariehamn",
  EUROPE_MINSK = "Europe/Minsk",
  EUROPE_MONACO = "Europe/Monaco",
  EUROPE_MOSCOW = "Europe/Moscow",
  EUROPE_NICOSIA = "Europe/Nicosia",
  EUROPE_OSLO = "Europe/Oslo",
  EUROPE_PARIS = "Europe/Paris",
  EUROPE_PODGORICA = "Europe/Podgorica",
  EUROPE_PRAGUE = "Europe/Prague",
  EUROPE_RIGA = "Europe/Riga",
  EUROPE_ROME = "Europe/Rome",
  EUROPE_SAMARA = "Europe/Samara",
  EUROPE_SAN_MARINO = "Europe/San_Marino",
  EUROPE_SARAJEVO = "Europe/Sarajevo",
  EUROPE_SARATOV = "Europe/Saratov",
  EUROPE_SIMFEROPOL = "Europe/Simferopol",
  EUROPE_SKOPJE = "Europe/Skopje",
  EUROPE_SOFIA = "Europe/Sofia",
  EUROPE_STOCKHOLM = "Europe/Stockholm",
  EUROPE_TALLINN = "Europe/Tallinn",
  EUROPE_TIRANE = "Europe/Tirane",
  EUROPE_TIRASPOL = "Europe/Tiraspol",
  EUROPE_ULYANOVSK = "Europe/Ulyanovsk",
  EUROPE_UZHGOROD = "Europe/Uzhgorod",
  EUROPE_VADUZ = "Europe/Vaduz",
  EUROPE_VATICAN = "Europe/Vatican",
  EUROPE_VIENNA = "Europe/Vienna",
  EUROPE_VILNIUS = "Europe/Vilnius",
  EUROPE_VOLGOGRAD = "Europe/Volgograd",
  EUROPE_WARSAW = "Europe/Warsaw",
  EUROPE_ZAGREB = "Europe/Zagreb",
  EUROPE_ZAPOROZHYE = "Europe/Zaporozhye",
  EUROPE_ZURICH = "Europe/Zurich",
  GB = "GB",
  GB_EIRE = "GB-Eire",
  GMT = "GMT",
  "GMT+0" = "GMT+0",
  GMT_0 = "GMT-0",
  GMT0 = "GMT0",
  GREENWICH = "Greenwich",
  HST = "HST",
  HONGKONG = "Hongkong",
  ICELAND = "Iceland",
  INDIAN_ANTANANARIVO = "Indian/Antananarivo",
  INDIAN_CHAGOS = "Indian/Chagos",
  INDIAN_CHRISTMAS = "Indian/Christmas",
  INDIAN_COCOS = "Indian/Cocos",
  INDIAN_COMORO = "Indian/Comoro",
  INDIAN_KERGUELEN = "Indian/Kerguelen",
  INDIAN_MAHE = "Indian/Mahe",
  INDIAN_MALDIVES = "Indian/Maldives",
  INDIAN_MAURITIUS = "Indian/Mauritius",
  INDIAN_MAYOTTE = "Indian/Mayotte",
  INDIAN_REUNION = "Indian/Reunion",
  IRAN = "Iran",
  ISRAEL = "Israel",
  JAMAICA = "Jamaica",
  JAPAN = "Japan",
  KWAJALEIN = "Kwajalein",
  LIBYA = "Libya",
  MET = "MET",
  MST = "MST",
  MST7MDT = "MST7MDT",
  MEXICO_BAJA_NORTE = "Mexico/BajaNorte",
  MEXICO_BAJA_SUR = "Mexico/BajaSur",
  MEXICO_GENERAL = "Mexico/General",
  NZ = "NZ",
  NZ_CHAT = "NZ-CHAT",
  NAVAJO = "Navajo",
  PRC = "PRC",
  PST8PDT = "PST8PDT",
  PACIFIC_APIA = "Pacific/Apia",
  PACIFIC_AUCKLAND = "Pacific/Auckland",
  PACIFIC_BOUGAINVILLE = "Pacific/Bougainville",
  PACIFIC_CHATHAM = "Pacific/Chatham",
  PACIFIC_CHUUK = "Pacific/Chuuk",
  PACIFIC_EASTER = "Pacific/Easter",
  PACIFIC_EFATE = "Pacific/Efate",
  PACIFIC_ENDERBURY = "Pacific/Enderbury",
  PACIFIC_FAKAOFO = "Pacific/Fakaofo",
  PACIFIC_FIJI = "Pacific/Fiji",
  PACIFIC_FUNAFUTI = "Pacific/Funafuti",
  PACIFIC_GALAPAGOS = "Pacific/Galapagos",
  PACIFIC_GAMBIER = "Pacific/Gambier",
  PACIFIC_GUADALCANAL = "Pacific/Guadalcanal",
  PACIFIC_GUAM = "Pacific/Guam",
  PACIFIC_HONOLULU = "Pacific/Honolulu",
  PACIFIC_JOHNSTON = "Pacific/Johnston",
  PACIFIC_KANTON = "Pacific/Kanton",
  PACIFIC_KIRITIMATI = "Pacific/Kiritimati",
  PACIFIC_KOSRAE = "Pacific/Kosrae",
  PACIFIC_KWAJALEIN = "Pacific/Kwajalein",
  PACIFIC_MAJURO = "Pacific/Majuro",
  PACIFIC_MARQUESAS = "Pacific/Marquesas",
  PACIFIC_MIDWAY = "Pacific/Midway",
  PACIFIC_NAURU = "Pacific/Nauru",
  PACIFIC_NIUE = "Pacific/Niue",
  PACIFIC_NORFOLK = "Pacific/Norfolk",
  PACIFIC_NOUMEA = "Pacific/Noumea",
  PACIFIC_PAGO_PAGO = "Pacific/Pago_Pago",
  PACIFIC_PALAU = "Pacific/Palau",
  PACIFIC_PITCAIRN = "Pacific/Pitcairn",
  PACIFIC_POHNPEI = "Pacific/Pohnpei",
  PACIFIC_PONAPE = "Pacific/Ponape",
  PACIFIC_PORT_MORESBY = "Pacific/Port_Moresby",
  PACIFIC_RAROTONGA = "Pacific/Rarotonga",
  PACIFIC_SAIPAN = "Pacific/Saipan",
  PACIFIC_SAMOA = "Pacific/Samoa",
  PACIFIC_TAHITI = "Pacific/Tahiti",
  PACIFIC_TARAWA = "Pacific/Tarawa",
  PACIFIC_TONGATAPU = "Pacific/Tongatapu",
  PACIFIC_TRUK = "Pacific/Truk",
  PACIFIC_WAKE = "Pacific/Wake",
  PACIFIC_WALLIS = "Pacific/Wallis",
  PACIFIC_YAP = "Pacific/Yap",
  POLAND = "Poland",
  PORTUGAL = "Portugal",
  ROC = "ROC",
  ROK = "ROK",
  SINGAPORE = "Singapore",
  TURKEY = "Turkey",
  UCT = "UCT",
  US_ALASKA = "US/Alaska",
  US_ALEUTIAN = "US/Aleutian",
  US_ARIZONA = "US/Arizona",
  US_CENTRAL = "US/Central",
  US_EAST_INDIANA = "US/East-Indiana",
  US_EASTERN = "US/Eastern",
  US_HAWAII = "US/Hawaii",
  US_INDIANA_STARKE = "US/Indiana-Starke",
  US_MICHIGAN = "US/Michigan",
  US_MOUNTAIN = "US/Mountain",
  US_PACIFIC = "US/Pacific",
  US_SAMOA = "US/Samoa",
  UTC = "UTC",
  UNIVERSAL = "Universal",
  W_SU = "W-SU",
  WET = "WET",
  ZULU = "Zulu",
}

/**
 * Token
 * A registration token for a site.
 */
export type Token = {
  /**
   * Id
   */
  id: number;
  /**
   * Value
   */
  value: string;
  /**
   * Audience
   */
  audience: string;
  /**
   * Purpose
   */
  purpose: string;
  /**
   * Expired
   */
  expired: string;
  /**
   * Created
   */
  created: string;
  /**
   * Site Id
   */
  site_id?: number | null;
};

/**
 * TokensGetResponse
 * List of existing tokens.
 */
export type TokensGetResponse = {
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Items
   */
  items: Array<Token>;
};

/**
 * TokensPostRequest
 * Request to create one or more tokens, with a certain validity.
 */
export type TokensPostRequest = {
  /**
   * Count
   */
  count?: number;
  /**
   * Duration
   */
  duration: string;
};

/**
 * TokensPostResponse
 * Response containing generated tokens.
 */
export type TokensPostResponse = {
  /**
   * Items
   */
  items: Array<Token>;
};

/**
 * UnauthorizedErrorBodyResponse
 */
export type UnauthorizedErrorBodyResponse = {
  code?: ExceptionCode;
  /**
   * Message
   */
  message?: string;
  /**
   * Details
   */
  details?: Array<BaseExceptionDetail> | null;
};

/**
 * UnauthorizedErrorResponseModel
 */
export type UnauthorizedErrorResponseModel = {
  error: UnauthorizedErrorBodyResponse;
};

/**
 * User
 * A user.
 */
export type User = {
  /**
   * Id
   */
  id: number;
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * Full Name
   */
  full_name: string;
  /**
   * Is Admin
   */
  is_admin: boolean;
};

/**
 * UsersGetResponse
 * List of existing users.
 */
export type UsersGetResponse = {
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Items
   */
  items: Array<User>;
};

/**
 * UsersPasswordPatchRequest
 * User password change schema.
 */
export type UsersPasswordPatchRequest = {
  /**
   * Current Password
   */
  current_password: string;
  /**
   * New Password
   */
  new_password: string;
  /**
   * Confirm Password
   */
  confirm_password: string;
};

/**
 * UsersPatchMeRequest
 * User Edit Details about themselves.
 */
export type UsersPatchMeRequest = {
  /**
   * Username
   */
  username?: string | null;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Email
   */
  email?: string | null;
};

/**
 * UsersPatchRequest
 * Request to edit details for a User.
 */
export type UsersPatchRequest = {
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Username
   */
  username?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Password
   */
  password?: string | null;
  /**
   * Confirm Password
   */
  confirm_password?: string | null;
  /**
   * Is Admin
   */
  is_admin?: boolean | null;
};

/**
 * UsersPostRequest
 * Request to create a User.
 */
export type UsersPostRequest = {
  /**
   * Full Name
   */
  full_name: string;
  /**
   * Username
   */
  username: string;
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Confirm Password
   */
  confirm_password: string;
  /**
   * Is Admin
   */
  is_admin?: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * ValidationErrorBodyResponse
 */
export type ValidationErrorBodyResponse = {
  code?: ExceptionCode;
  /**
   * Message
   */
  message?: string;
  /**
   * Details
   */
  details?: Array<BaseExceptionDetail> | null;
};

/**
 * ValidationErrorResponseModel
 */
export type ValidationErrorResponseModel = {
  error: ValidationErrorBodyResponse;
};

export type GetBootSourcesV1BootassetSourcesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Sort by properties
     */
    sort_by?: string | null;
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
  };
  url: "/v1/bootasset-sources";
};

export type GetBootSourcesV1BootassetSourcesGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetBootSourcesV1BootassetSourcesGetError =
  GetBootSourcesV1BootassetSourcesGetErrors[keyof GetBootSourcesV1BootassetSourcesGetErrors];

export type GetBootSourcesV1BootassetSourcesGetResponses = {
  /**
   * Successful Response
   */
  200: BootSourcesGetResponse;
};

export type GetBootSourcesV1BootassetSourcesGetResponse =
  GetBootSourcesV1BootassetSourcesGetResponses[keyof GetBootSourcesV1BootassetSourcesGetResponses];

export type PostBootSourcesV1BootassetSourcesPostData = {
  body: BootSourcesPostRequest;
  path?: never;
  query?: never;
  url: "/v1/bootasset-sources";
};

export type PostBootSourcesV1BootassetSourcesPostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostBootSourcesV1BootassetSourcesPostError =
  PostBootSourcesV1BootassetSourcesPostErrors[keyof PostBootSourcesV1BootassetSourcesPostErrors];

export type PostBootSourcesV1BootassetSourcesPostResponses = {
  /**
   * Successful Response
   */
  200: BootSourcesPostResponse;
};

export type PostBootSourcesV1BootassetSourcesPostResponse =
  PostBootSourcesV1BootassetSourcesPostResponses[keyof PostBootSourcesV1BootassetSourcesPostResponses];

export type DeleteBootSourceV1BootassetSourcesIdDeleteData = {
  body?: never;
  path: {
    /**
     * The ID of the Boot Source to delete
     */
    id: number;
  };
  query?: never;
  url: "/v1/bootasset-sources/{id}";
};

export type DeleteBootSourceV1BootassetSourcesIdDeleteErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteBootSourceV1BootassetSourcesIdDeleteError =
  DeleteBootSourceV1BootassetSourcesIdDeleteErrors[keyof DeleteBootSourceV1BootassetSourcesIdDeleteErrors];

export type DeleteBootSourceV1BootassetSourcesIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetBootSourceByIdV1BootassetSourcesIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/bootasset-sources/{id}";
};

export type GetBootSourceByIdV1BootassetSourcesIdGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetBootSourceByIdV1BootassetSourcesIdGetError =
  GetBootSourceByIdV1BootassetSourcesIdGetErrors[keyof GetBootSourceByIdV1BootassetSourcesIdGetErrors];

export type GetBootSourceByIdV1BootassetSourcesIdGetResponses = {
  /**
   * Successful Response
   */
  200: BootSourceGetResponse;
};

export type GetBootSourceByIdV1BootassetSourcesIdGetResponse =
  GetBootSourceByIdV1BootassetSourcesIdGetResponses[keyof GetBootSourceByIdV1BootassetSourcesIdGetResponses];

export type PatchBootSourceV1BootassetSourcesIdPatchData = {
  body: BootSourcesPatchRequest;
  path: {
    /**
     * The ID of the Boot Source to update
     */
    id: number;
  };
  query?: never;
  url: "/v1/bootasset-sources/{id}";
};

export type PatchBootSourceV1BootassetSourcesIdPatchErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchBootSourceV1BootassetSourcesIdPatchError =
  PatchBootSourceV1BootassetSourcesIdPatchErrors[keyof PatchBootSourceV1BootassetSourcesIdPatchErrors];

export type PatchBootSourceV1BootassetSourcesIdPatchResponses = {
  /**
   * Successful Response
   */
  200: BootSourcePatchResponse;
};

export type PatchBootSourceV1BootassetSourcesIdPatchResponse =
  PatchBootSourceV1BootassetSourcesIdPatchResponses[keyof PatchBootSourceV1BootassetSourcesIdPatchResponses];

export type GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: {
    /**
     * Sort by properties
     */
    sort_by?: string | null;
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
  };
  url: "/v1/bootasset-sources/{id}/selections";
};

export type GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetError =
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetErrors[keyof GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetErrors];

export type GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponses = {
  /**
   * Successful Response
   */
  200: BootSourceSelectionsGetResponse;
};

export type GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponse =
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponses[keyof GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponses];

export type PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutData = {
  body: BootSourceAvailSelectionsPutRequest;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/bootasset-sources/{id}/available-selections";
};

export type PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutError =
  PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutErrors[keyof PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutErrors];

export type PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutResponses = {
  /**
   * Successful Response
   */
  200: BootSourceAvailSelectionsPutResponse;
};

export type PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutResponse =
  PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutResponses[keyof PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutResponses];

export type PutBootSourceAssetsV1BootassetSourcesIdAssetsPutData = {
  body: BootSourcesAssetsPutRequest;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/bootasset-sources/{id}/assets";
};

export type PutBootSourceAssetsV1BootassetSourcesIdAssetsPutErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PutBootSourceAssetsV1BootassetSourcesIdAssetsPutError =
  PutBootSourceAssetsV1BootassetSourcesIdAssetsPutErrors[keyof PutBootSourceAssetsV1BootassetSourcesIdAssetsPutErrors];

export type PutBootSourceAssetsV1BootassetSourcesIdAssetsPutResponses = {
  /**
   * Successful Response
   */
  200: BootSourcesAssetsPutResponse;
};

export type PutBootSourceAssetsV1BootassetSourcesIdAssetsPutResponse =
  PutBootSourceAssetsV1BootassetSourcesIdAssetsPutResponses[keyof PutBootSourceAssetsV1BootassetSourcesIdAssetsPutResponses];

export type GetBootAssetItemV1BootassetItemsIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/bootasset-items/{id}";
};

export type GetBootAssetItemV1BootassetItemsIdGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetBootAssetItemV1BootassetItemsIdGetError =
  GetBootAssetItemV1BootassetItemsIdGetErrors[keyof GetBootAssetItemV1BootassetItemsIdGetErrors];

export type GetBootAssetItemV1BootassetItemsIdGetResponses = {
  /**
   * Successful Response
   */
  200: BootAssetItemGetResponse;
};

export type GetBootAssetItemV1BootassetItemsIdGetResponse =
  GetBootAssetItemV1BootassetItemsIdGetResponses[keyof GetBootAssetItemV1BootassetItemsIdGetResponses];

export type PatchBootAssetItemsV1BootassetItemsIdPatchData = {
  body: BootAssetItemPatchRequest;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/bootasset-items/{id}";
};

export type PatchBootAssetItemsV1BootassetItemsIdPatchErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchBootAssetItemsV1BootassetItemsIdPatchError =
  PatchBootAssetItemsV1BootassetItemsIdPatchErrors[keyof PatchBootAssetItemsV1BootassetItemsIdPatchErrors];

export type PatchBootAssetItemsV1BootassetItemsIdPatchResponses = {
  /**
   * Successful Response
   */
  200: BootAssetItemPatchResponse;
};

export type PatchBootAssetItemsV1BootassetItemsIdPatchResponse =
  PatchBootAssetItemsV1BootassetItemsIdPatchResponses[keyof PatchBootAssetItemsV1BootassetItemsIdPatchResponses];

export type DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetData = {
  body?: never;
  path: {
    /**
     * Track
     */
    track: string;
    /**
     * Risk
     */
    risk: string;
    /**
     * Index Path
     */
    index_path: string;
  };
  query?: never;
  url: "/v1/images/{track}/{risk}/streams/v1/{index_path}";
};

export type DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetError =
  DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetErrors[keyof DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetErrors];

export type DownloadIndexV1ImagesTrackRiskStreamsV1IndexPathGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DownloadV1ImagesTrackRiskBootSourceIdFilePathGetData = {
  body?: never;
  path: {
    /**
     * Track
     */
    track: string;
    /**
     * Risk
     */
    risk: string;
    /**
     * Boot Source Id
     */
    boot_source_id: number;
    /**
     * File Path
     */
    file_path: string;
  };
  query?: never;
  url: "/v1/images/{track}/{risk}/{boot_source_id}/{file_path}";
};

export type DownloadV1ImagesTrackRiskBootSourceIdFilePathGetErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DownloadV1ImagesTrackRiskBootSourceIdFilePathGetError =
  DownloadV1ImagesTrackRiskBootSourceIdFilePathGetErrors[keyof DownloadV1ImagesTrackRiskBootSourceIdFilePathGetErrors];

export type DownloadV1ImagesTrackRiskBootSourceIdFilePathGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PostImagesV1ImagesPostData = {
  body: {
    os?: string;
    release?: string;
    title?: string;
    arch?: string;
    file_size?: number;
    filename?: string;
    file?: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/v1/images";
};

export type PostImagesV1ImagesPostErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostImagesV1ImagesPostError = PostImagesV1ImagesPostErrors[keyof PostImagesV1ImagesPostErrors];

export type PostImagesV1ImagesPostResponses = {
  /**
   * Successful Response
   */
  200: ImagesPostResponse;
};

export type PostImagesV1ImagesPostResponse = PostImagesV1ImagesPostResponses[keyof PostImagesV1ImagesPostResponses];

export type DeleteImagesV1ImagesRemovePostData = {
  body: ImagesRemovePostRequest;
  path?: never;
  query?: never;
  url: "/v1/images:remove";
};

export type DeleteImagesV1ImagesRemovePostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteImagesV1ImagesRemovePostError =
  DeleteImagesV1ImagesRemovePostErrors[keyof DeleteImagesV1ImagesRemovePostErrors];

export type DeleteImagesV1ImagesRemovePostResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteImagesV1ImagesRemovePostResponse =
  DeleteImagesV1ImagesRemovePostResponses[keyof DeleteImagesV1ImagesRemovePostResponses];

export type RefreshIndexV1RefreshIndexGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/refresh-index";
};

export type RefreshIndexV1RefreshIndexGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PostV1LoginPostData = {
  body: BodyPostV1LoginPost;
  path?: never;
  query?: never;
  url: "/v1/login";
};

export type PostV1LoginPostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostV1LoginPostError = PostV1LoginPostErrors[keyof PostV1LoginPostErrors];

export type PostV1LoginPostResponses = {
  /**
   * Successful Response
   */
  200: AccessTokenResponse;
};

export type PostV1LoginPostResponse = PostV1LoginPostResponses[keyof PostV1LoginPostResponses];

export type SelectImagesV1SelectableImagesSelectPostData = {
  body: SelectImagesPostRequest;
  path?: never;
  query?: never;
  url: "/v1/selectable-images:select";
};

export type SelectImagesV1SelectableImagesSelectPostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type SelectImagesV1SelectableImagesSelectPostError =
  SelectImagesV1SelectableImagesSelectPostErrors[keyof SelectImagesV1SelectableImagesSelectPostErrors];

export type SelectImagesV1SelectableImagesSelectPostResponses = {
  /**
   * Successful Response
   */
  201: unknown;
};

export type GetSelectableImagesV1SelectableImagesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/selectable-images";
};

export type GetSelectableImagesV1SelectableImagesGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
};

export type GetSelectableImagesV1SelectableImagesGetError =
  GetSelectableImagesV1SelectableImagesGetErrors[keyof GetSelectableImagesV1SelectableImagesGetErrors];

export type GetSelectableImagesV1SelectableImagesGetResponses = {
  /**
   * Successful Response
   */
  200: GetSelectableImagesResponse;
};

export type GetSelectableImagesV1SelectableImagesGetResponse =
  GetSelectableImagesV1SelectableImagesGetResponses[keyof GetSelectableImagesV1SelectableImagesGetResponses];

export type GetSelectedImagesV1SelectedImagesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/selected-images";
};

export type GetSelectedImagesV1SelectedImagesGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
};

export type GetSelectedImagesV1SelectedImagesGetError =
  GetSelectedImagesV1SelectedImagesGetErrors[keyof GetSelectedImagesV1SelectedImagesGetErrors];

export type GetSelectedImagesV1SelectedImagesGetResponses = {
  /**
   * Successful Response
   */
  200: GetSelectedImagesResponse;
};

export type GetSelectedImagesV1SelectedImagesGetResponse =
  GetSelectedImagesV1SelectedImagesGetResponses[keyof GetSelectedImagesV1SelectedImagesGetResponses];

export type RemoveSelectionsV1SelectedImagesRemovePostData = {
  body: RemoveSelectedImagesPostRequest;
  path?: never;
  query?: never;
  url: "/v1/selected-images:remove";
};

export type RemoveSelectionsV1SelectedImagesRemovePostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type RemoveSelectionsV1SelectedImagesRemovePostError =
  RemoveSelectionsV1SelectedImagesRemovePostErrors[keyof RemoveSelectionsV1SelectedImagesRemovePostErrors];

export type RemoveSelectionsV1SelectedImagesRemovePostResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type RemoveSelectionsV1SelectedImagesRemovePostResponse =
  RemoveSelectionsV1SelectedImagesRemovePostResponses[keyof RemoveSelectionsV1SelectedImagesRemovePostResponses];

export type GetImageSourcesV1ImageSourcesGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Os
     */
    os: string;
    /**
     * Release
     */
    release: string;
    /**
     * Arch
     */
    arch: string;
  };
  url: "/v1/image-sources";
};

export type GetImageSourcesV1ImageSourcesGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetImageSourcesV1ImageSourcesGetError =
  GetImageSourcesV1ImageSourcesGetErrors[keyof GetImageSourcesV1ImageSourcesGetErrors];

export type GetImageSourcesV1ImageSourcesGetResponses = {
  /**
   * Successful Response
   */
  200: GetImageSourcesResponse;
};

export type GetImageSourcesV1ImageSourcesGetResponse =
  GetImageSourcesV1ImageSourcesGetResponses[keyof GetImageSourcesV1ImageSourcesGetResponses];

export type GetV1SettingsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/settings";
};

export type GetV1SettingsGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
};

export type GetV1SettingsGetError = GetV1SettingsGetErrors[keyof GetV1SettingsGetErrors];

export type GetV1SettingsGetResponses = {
  /**
   * Successful Response
   */
  200: Settings;
};

export type GetV1SettingsGetResponse = GetV1SettingsGetResponses[keyof GetV1SettingsGetResponses];

export type PatchV1SettingsPatchData = {
  body: SettingsUpdate;
  path?: never;
  query?: never;
  url: "/v1/settings";
};

export type PatchV1SettingsPatchErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchV1SettingsPatchError = PatchV1SettingsPatchErrors[keyof PatchV1SettingsPatchErrors];

export type PatchV1SettingsPatchResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetPendingV1SitesPendingGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
  };
  url: "/v1/sites/pending";
};

export type GetPendingV1SitesPendingGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetPendingV1SitesPendingGetError =
  GetPendingV1SitesPendingGetErrors[keyof GetPendingV1SitesPendingGetErrors];

export type GetPendingV1SitesPendingGetResponses = {
  /**
   * Successful Response
   */
  200: PendingSitesGetResponse;
};

export type GetPendingV1SitesPendingGetResponse =
  GetPendingV1SitesPendingGetResponses[keyof GetPendingV1SitesPendingGetResponses];

export type PostPendingV1SitesPendingPostData = {
  body: PendingSitesPostRequest;
  path?: never;
  query?: never;
  url: "/v1/sites/pending";
};

export type PostPendingV1SitesPendingPostErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostPendingV1SitesPendingPostError =
  PostPendingV1SitesPendingPostErrors[keyof PostPendingV1SitesPendingPostErrors];

export type PostPendingV1SitesPendingPostResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type PostPendingV1SitesPendingPostResponse =
  PostPendingV1SitesPendingPostResponses[keyof PostPendingV1SitesPendingPostResponses];

export type DeleteManyV1SitesDeleteData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Ids
     */
    ids: Array<number>;
  };
  url: "/v1/sites";
};

export type DeleteManyV1SitesDeleteErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteManyV1SitesDeleteError = DeleteManyV1SitesDeleteErrors[keyof DeleteManyV1SitesDeleteErrors];

export type DeleteManyV1SitesDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteManyV1SitesDeleteResponse = DeleteManyV1SitesDeleteResponses[keyof DeleteManyV1SitesDeleteResponses];

export type GetV1SitesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter for site with coordinates
     */
    coordinates?: boolean | null;
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Filter for cities
     */
    city?: Array<string> | null;
    /**
     * Filter for country
     */
    country?: Array<string> | null;
    /**
     * Filter for names
     */
    name?: Array<string> | null;
    /**
     * Filter for notes
     */
    note?: Array<string> | null;
    /**
     * Filter for administrative regions
     */
    state?: Array<string> | null;
    /**
     * Filter for streets
     */
    address?: Array<string> | null;
    /**
     * Filter for postal code
     */
    postal_code?: Array<string> | null;
    /**
     * Filter for timezones
     */
    timezone?: Array<string> | null;
    /**
     * Filter for urls
     */
    url?: Array<string> | null;
    /**
     * Filter for MAAS UUIDs
     */
    cluster_uuid?: Array<string> | null;
    /**
     * Search for query in string fields
     */
    q?: string | null;
    /**
     * Sort by properties
     */
    sort_by?: string | null;
  };
  url: "/v1/sites";
};

export type GetV1SitesGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetV1SitesGetError = GetV1SitesGetErrors[keyof GetV1SitesGetErrors];

export type GetV1SitesGetResponses = {
  /**
   * Successful Response
   */
  200: SitesGetResponse;
};

export type GetV1SitesGetResponse = GetV1SitesGetResponses[keyof GetV1SitesGetResponses];

export type GetCoordinatesV1SitesCoordinatesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter for cities
     */
    city?: Array<string> | null;
    /**
     * Filter for country
     */
    country?: Array<string> | null;
    /**
     * Filter for names
     */
    name?: Array<string> | null;
    /**
     * Filter for notes
     */
    note?: Array<string> | null;
    /**
     * Filter for administrative regions
     */
    state?: Array<string> | null;
    /**
     * Filter for streets
     */
    address?: Array<string> | null;
    /**
     * Filter for postal code
     */
    postal_code?: Array<string> | null;
    /**
     * Filter for timezones
     */
    timezone?: Array<string> | null;
    /**
     * Filter for urls
     */
    url?: Array<string> | null;
    /**
     * Filter for MAAS UUIDs
     */
    cluster_uuid?: Array<string> | null;
    /**
     * Search for query in string fields
     */
    q?: string | null;
  };
  url: "/v1/sites/coordinates";
};

export type GetCoordinatesV1SitesCoordinatesGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetCoordinatesV1SitesCoordinatesGetError =
  GetCoordinatesV1SitesCoordinatesGetErrors[keyof GetCoordinatesV1SitesCoordinatesGetErrors];

export type GetCoordinatesV1SitesCoordinatesGetResponses = {
  /**
   * Response Get Coordinates V1 Sites Coordinates Get
   * Successful Response
   */
  200: Array<SiteCoordinates>;
};

export type GetCoordinatesV1SitesCoordinatesGetResponse =
  GetCoordinatesV1SitesCoordinatesGetResponses[keyof GetCoordinatesV1SitesCoordinatesGetResponses];

export type DeleteV1SitesIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/sites/{id}";
};

export type DeleteV1SitesIdDeleteErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteV1SitesIdDeleteError = DeleteV1SitesIdDeleteErrors[keyof DeleteV1SitesIdDeleteErrors];

export type DeleteV1SitesIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteV1SitesIdDeleteResponse = DeleteV1SitesIdDeleteResponses[keyof DeleteV1SitesIdDeleteResponses];

export type GetIdV1SitesIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/sites/{id}";
};

export type GetIdV1SitesIdGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetIdV1SitesIdGetError = GetIdV1SitesIdGetErrors[keyof GetIdV1SitesIdGetErrors];

export type GetIdV1SitesIdGetResponses = {
  /**
   * Successful Response
   */
  200: Site;
};

export type GetIdV1SitesIdGetResponse = GetIdV1SitesIdGetResponses[keyof GetIdV1SitesIdGetResponses];

export type PatchV1SitesIdPatchData = {
  body: SiteUpdateRequest;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/sites/{id}";
};

export type PatchV1SitesIdPatchErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchV1SitesIdPatchError = PatchV1SitesIdPatchErrors[keyof PatchV1SitesIdPatchErrors];

export type PatchV1SitesIdPatchResponses = {
  /**
   * Successful Response
   */
  200: Site;
};

export type PatchV1SitesIdPatchResponse = PatchV1SitesIdPatchResponses[keyof PatchV1SitesIdPatchResponses];

export type DeleteManyV1TokensDeleteData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Ids
     */
    ids: Array<number>;
  };
  url: "/v1/tokens";
};

export type DeleteManyV1TokensDeleteErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteManyV1TokensDeleteError = DeleteManyV1TokensDeleteErrors[keyof DeleteManyV1TokensDeleteErrors];

export type DeleteManyV1TokensDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteManyV1TokensDeleteResponse =
  DeleteManyV1TokensDeleteResponses[keyof DeleteManyV1TokensDeleteResponses];

export type GetV1TokensGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Filter for token IDs
     */
    id?: Array<number> | null;
    /**
     * Filter for tokens
     */
    value?: Array<string> | null;
    /**
     * Filter for site IDs the token authenticated
     */
    site_id?: Array<number> | null;
  };
  url: "/v1/tokens";
};

export type GetV1TokensGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetV1TokensGetError = GetV1TokensGetErrors[keyof GetV1TokensGetErrors];

export type GetV1TokensGetResponses = {
  /**
   * Successful Response
   */
  200: TokensGetResponse;
};

export type GetV1TokensGetResponse = GetV1TokensGetResponses[keyof GetV1TokensGetResponses];

export type PostV1TokensPostData = {
  body: TokensPostRequest;
  path?: never;
  query?: never;
  url: "/v1/tokens";
};

export type PostV1TokensPostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostV1TokensPostError = PostV1TokensPostErrors[keyof PostV1TokensPostErrors];

export type PostV1TokensPostResponses = {
  /**
   * Successful Response
   */
  200: TokensPostResponse;
};

export type PostV1TokensPostResponse = PostV1TokensPostResponses[keyof PostV1TokensPostResponses];

export type GetExportV1TokensExportGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Filter for token IDs
     */
    id?: Array<number> | null;
    /**
     * Filter for tokens
     */
    value?: Array<string> | null;
    /**
     * Filter for site IDs the token authenticated
     */
    site_id?: Array<number> | null;
  };
  url: "/v1/tokens/export";
};

export type GetExportV1TokensExportGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetExportV1TokensExportGetError = GetExportV1TokensExportGetErrors[keyof GetExportV1TokensExportGetErrors];

export type GetExportV1TokensExportGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteV1TokensIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/tokens/{id}";
};

export type DeleteV1TokensIdDeleteErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteV1TokensIdDeleteError = DeleteV1TokensIdDeleteErrors[keyof DeleteV1TokensIdDeleteErrors];

export type DeleteV1TokensIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteV1TokensIdDeleteResponse = DeleteV1TokensIdDeleteResponses[keyof DeleteV1TokensIdDeleteResponses];

export type GetV1UsersGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Filter for email address
     */
    email?: Array<string> | null;
    /**
     * Filter for username
     */
    username?: Array<string> | null;
    /**
     * Filter for full name
     */
    full_name?: Array<string> | null;
    /**
     * Filter for admin status
     */
    is_admin?: Array<boolean> | null;
    /**
     * Sort by properties
     */
    sort_by?: string | null;
    /**
     * Search Text
     */
    search_text?: string;
  };
  url: "/v1/users";
};

export type GetV1UsersGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetV1UsersGetError = GetV1UsersGetErrors[keyof GetV1UsersGetErrors];

export type GetV1UsersGetResponses = {
  /**
   * Successful Response
   */
  200: UsersGetResponse;
};

export type GetV1UsersGetResponse = GetV1UsersGetResponses[keyof GetV1UsersGetResponses];

export type PostV1UsersPostData = {
  body: UsersPostRequest;
  path?: never;
  query?: never;
  url: "/v1/users";
};

export type PostV1UsersPostErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostV1UsersPostError = PostV1UsersPostErrors[keyof PostV1UsersPostErrors];

export type PostV1UsersPostResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type PostV1UsersPostResponse = PostV1UsersPostResponses[keyof PostV1UsersPostResponses];

export type GetMeV1UsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/users/me";
};

export type GetMeV1UsersMeGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
};

export type GetMeV1UsersMeGetError = GetMeV1UsersMeGetErrors[keyof GetMeV1UsersMeGetErrors];

export type GetMeV1UsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type GetMeV1UsersMeGetResponse = GetMeV1UsersMeGetResponses[keyof GetMeV1UsersMeGetResponses];

export type PatchMeV1UsersMePatchData = {
  body: UsersPatchMeRequest;
  path?: never;
  query?: never;
  url: "/v1/users/me";
};

export type PatchMeV1UsersMePatchErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchMeV1UsersMePatchError = PatchMeV1UsersMePatchErrors[keyof PatchMeV1UsersMePatchErrors];

export type PatchMeV1UsersMePatchResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type PatchMeV1UsersMePatchResponse = PatchMeV1UsersMePatchResponses[keyof PatchMeV1UsersMePatchResponses];

export type PatchMePasswordV1UsersMePasswordPatchData = {
  body: UsersPasswordPatchRequest;
  path?: never;
  query?: never;
  url: "/v1/users/me/password";
};

export type PatchMePasswordV1UsersMePasswordPatchErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchMePasswordV1UsersMePasswordPatchError =
  PatchMePasswordV1UsersMePasswordPatchErrors[keyof PatchMePasswordV1UsersMePasswordPatchErrors];

export type PatchMePasswordV1UsersMePasswordPatchResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteV1UsersIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/users/{id}";
};

export type DeleteV1UsersIdDeleteErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteV1UsersIdDeleteError = DeleteV1UsersIdDeleteErrors[keyof DeleteV1UsersIdDeleteErrors];

export type DeleteV1UsersIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteV1UsersIdDeleteResponse = DeleteV1UsersIdDeleteResponses[keyof DeleteV1UsersIdDeleteResponses];

export type GetIdV1UsersIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/users/{id}";
};

export type GetIdV1UsersIdGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetIdV1UsersIdGetError = GetIdV1UsersIdGetErrors[keyof GetIdV1UsersIdGetErrors];

export type GetIdV1UsersIdGetResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type GetIdV1UsersIdGetResponse = GetIdV1UsersIdGetResponses[keyof GetIdV1UsersIdGetResponses];

export type PatchV1UsersIdPatchData = {
  body: UsersPatchRequest;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/v1/users/{id}";
};

export type PatchV1UsersIdPatchErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchV1UsersIdPatchError = PatchV1UsersIdPatchErrors[keyof PatchV1UsersIdPatchErrors];

export type PatchV1UsersIdPatchResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type PatchV1UsersIdPatchResponse = PatchV1UsersIdPatchResponses[keyof PatchV1UsersIdPatchResponses];

export type ClientOptions = {
  baseURL: `${string}://${string}/api` | (string & {});
};
