"""multiple_tokens_per_site

Revision ID: 0004
Revises: 0003
Create Date: 2024-06-13 21:18:27.912361+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_site_auth_id", table_name="site")
    op.drop_column("site", "auth_id")
    op.add_column("token", sa.Column("audience", sa.Text(), nullable=False))
    op.add_column("token", sa.Column("purpose", sa.Text(), nullable=False))
    op.add_column("token", sa.Column("site_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_token_audience"),
        "token",
        ["audience", "purpose"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_token_site_id_site"),
        "token",
        "site",
        ["site_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_token_site_id_site"), "token", type_="foreignkey"
    )
    op.drop_index(op.f("ix_token_audience"), table_name="token")
    op.drop_column("token", "site_id")
    op.drop_column("token", "purpose")
    op.drop_column("token", "audience")
    op.add_column(
        "site",
        sa.Column("auth_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_index("ix_site_auth_id", "site", ["auth_id"], unique=True)
    # ### end Alembic commands ###
