"""images

Revision ID: 0005
Revises: 0004
Create Date: 2025-01-09 16:46:26.665697+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boot_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("keyring", sa.Text(), nullable=True),
        sa.Column("sync_interval", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boot_source")),
    )
    op.create_table(
        "boot_asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("boot_source_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("os", sa.Text(), nullable=False),
        sa.Column("release", sa.Text(), nullable=False),
        sa.Column("codename", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("arch", sa.Text(), nullable=False),
        sa.Column("subarch", sa.Text(), nullable=False),
        sa.Column("compatibility", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("flavor", sa.Text(), nullable=False),
        sa.Column("base_image", sa.Text(), nullable=False),
        sa.Column("eol", sa.DateTime(), nullable=False),
        sa.Column("esm_eol", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["boot_source_id"],
            ["boot_source.id"],
            name=op.f("fk_boot_asset_boot_source_id_boot_source"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boot_asset")),
    )
    op.create_table(
        "boot_source_selection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("boot_source_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("os", sa.Text(), nullable=False),
        sa.Column("release", sa.Text(), nullable=False),
        sa.Column("arches", sa.ARRAY(sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["boot_source_id"],
            ["boot_source.id"],
            name=op.f("fk_boot_source_selection_boot_source_id_boot_source"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boot_source_selection")),
    )
    op.create_table(
        "boot_asset_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("boot_asset_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["boot_asset_id"],
            ["boot_asset.id"],
            name=op.f("fk_boot_asset_version_boot_asset_id_boot_asset"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boot_asset_version")),
    )
    op.create_table(
        "boot_asset_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("boot_asset_version_id", sa.Integer(), nullable=False),
        sa.Column("ftype", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("source_package", sa.Text(), nullable=True),
        sa.Column("source_version", sa.Text(), nullable=True),
        sa.Column("source_release", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["boot_asset_version_id"],
            ["boot_asset_version.id"],
            name=op.f(
                "fk_boot_asset_item_boot_asset_version_id_boot_asset_version"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boot_asset_item")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("boot_asset_item")
    op.drop_table("boot_asset_version")
    op.drop_table("boot_source_selection")
    op.drop_table("boot_asset")
    op.drop_table("boot_source")
    # ### end Alembic commands ###
