"""add_bytes_synced

Revision ID: 0007
Revises: 0006
Create Date: 2025-03-10 19:34:58.729162+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boot_asset_item",
        sa.Column("bytes_synced", sa.BigInteger(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boot_asset_item", "bytes_synced")
    # ### end Alembic commands ###
