"""rename_item_size

Revision ID: 0008
Revises: 0007
Create Date: 2025-04-16 16:16:19.204414+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boot_asset_item",
        sa.Column("file_size", sa.BigInteger(), nullable=False),
    )
    op.drop_column("boot_asset_item", "size")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boot_asset_item",
        sa.Column("size", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_column("boot_asset_item", "file_size")
    # ### end Alembic commands ###
