"""images-unique-constraints

Revision ID: 0009
Revises: 0008
Create Date: 2025-04-25 19:24:14.786362+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_boot_asset_boot_source_id"),
        "boot_asset",
        ["boot_source_id", "os", "release", "arch", "subarch"],
    )
    op.create_unique_constraint(
        op.f("uq_boot_asset_item_boot_asset_version_id"),
        "boot_asset_item",
        ["boot_asset_version_id", "ftype"],
    )
    op.create_unique_constraint(
        op.f("uq_boot_asset_version_boot_asset_id"),
        "boot_asset_version",
        ["boot_asset_id", "version"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_boot_asset_version_boot_asset_id"),
        "boot_asset_version",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_boot_asset_item_boot_asset_version_id"),
        "boot_asset_item",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_boot_asset_boot_source_id"), "boot_asset", type_="unique"
    )
    # ### end Alembic commands ###
