"""nullable-asset-fields

Revision ID: 0011
Revises: 0010
Create Date: 2025-05-19 20:58:01.071508+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "boot_asset", "release", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "boot_asset", "codename", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "boot_asset", "title", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "boot_asset", "subarch", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "boot_asset",
        "compatibility",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        nullable=True,
    )
    op.alter_column(
        "boot_asset", "flavor", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "boot_asset", "base_image", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "boot_asset",
        "eol",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "boot_asset",
        "esm_eol",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "boot_asset",
        "esm_eol",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "boot_asset",
        "eol",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "boot_asset", "base_image", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "boot_asset", "flavor", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "boot_asset",
        "compatibility",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        nullable=False,
    )
    op.alter_column(
        "boot_asset", "subarch", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "boot_asset", "title", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "boot_asset", "codename", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "boot_asset", "release", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
