"""add available selections

Revision ID: 0013
Revises: 0012
Create Date: 2025-06-18 20:01:04.181190+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boot_source_selection",
        sa.Column("available", sa.ARRAY(sa.Text()), nullable=False),
    )
    op.add_column(
        "boot_source_selection",
        sa.Column("selected", sa.ARRAY(sa.Text()), nullable=False),
    )
    op.drop_column("boot_source_selection", "arches")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boot_source_selection",
        sa.Column(
            "arches",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("boot_source_selection", "selected")
    op.drop_column("boot_source_selection", "available")
    # ### end Alembic commands ###
