"""fix_item_constraint

Revision ID: 0016
Revises: 0015
Create Date: 2025-06-26 19:56:02.726941+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_boot_asset_item_boot_asset_version_id",
        "boot_asset_item",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_boot_asset_item_boot_asset_version_id"),
        "boot_asset_item",
        ["boot_asset_version_id", "ftype", "path"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_boot_asset_item_boot_asset_version_id"),
        "boot_asset_item",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_boot_asset_item_boot_asset_version_id",
        "boot_asset_item",
        ["boot_asset_version_id", "ftype"],
    )
    # ### end Alembic commands ###
