"""fk-delete-restrict

Revision ID: 0017
Revises: 0016
Create Date: 2025-07-23 17:37:52.579230+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_boot_asset_boot_source_id_boot_source",
        "boot_asset",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_boot_asset_boot_source_id_boot_source"),
        "boot_asset",
        "boot_source",
        ["boot_source_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        "fk_boot_asset_item_boot_asset_version_id_boot_asset_version",
        "boot_asset_item",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_boot_asset_item_boot_asset_version_id_boot_asset_version"),
        "boot_asset_item",
        "boot_asset_version",
        ["boot_asset_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        "fk_boot_asset_version_boot_asset_id_boot_asset",
        "boot_asset_version",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_boot_asset_version_boot_asset_id_boot_asset"),
        "boot_asset_version",
        "boot_asset",
        ["boot_asset_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        "fk_boot_source_selection_boot_source_id_boot_source",
        "boot_source_selection",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_boot_source_selection_boot_source_id_boot_source"),
        "boot_source_selection",
        "boot_source",
        ["boot_source_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_boot_source_selection_boot_source_id_boot_source"),
        "boot_source_selection",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_boot_source_selection_boot_source_id_boot_source",
        "boot_source_selection",
        "boot_source",
        ["boot_source_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_boot_asset_version_boot_asset_id_boot_asset"),
        "boot_asset_version",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_boot_asset_version_boot_asset_id_boot_asset",
        "boot_asset_version",
        "boot_asset",
        ["boot_asset_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_boot_asset_item_boot_asset_version_id_boot_asset_version"),
        "boot_asset_item",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_boot_asset_item_boot_asset_version_id_boot_asset_version",
        "boot_asset_item",
        "boot_asset_version",
        ["boot_asset_version_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_boot_asset_boot_source_id_boot_source"),
        "boot_asset",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_boot_asset_boot_source_id_boot_source",
        "boot_asset",
        "boot_source",
        ["boot_source_id"],
        ["id"],
    )
    # ### end Alembic commands ###
