"""Add timestamps to help with stale image detection

Revision ID: 0018
Revises: 0017
Create Date: 2025-08-01 19:37:45.926375+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boot_asset_version",
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "boot_source",
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boot_source", "last_sync")
    op.drop_column("boot_asset_version", "last_seen")
    # ### end Alembic commands ###
