"""single-arch-selection

Revision ID: 0019
Revises: 0018
Create Date: 2025-08-21 18:00:16.348626+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boot_source_selection", sa.Column("arch", sa.Text(), nullable=False)
    )
    op.drop_column("boot_source_selection", "selected")
    op.add_column(
        "boot_source_selection",
        sa.Column("selected", sa.Boolean(), nullable=False),
    )
    op.drop_column("boot_source_selection", "available")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boot_source_selection",
        sa.Column(
            "available",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("boot_source_selection", "selected")
    op.add_column(
        "boot_source_selection",
        sa.Column("selected", postgresql.ARRAY(sa.TEXT()), nullable=False),
    )
    op.drop_column("boot_source_selection", "arch")
    # ### end Alembic commands ###
