user root;
daemon off;
worker_processes auto;
pid {{ data_dir }}/nginx.pid;
error_log stderr info;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    gzip on;

    include {{ base_dir }}/etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format log_request_id '$time_iso8601 $request_id $remote_addr "$request" "$http_user_agent" $status $bytes_sent $request_time';
    access_log {{ data_dir }}/access.log log_request_id;

    client_body_temp_path {{ data_dir }}/body;
    fastcgi_temp_path {{ data_dir }}/fastcgi;
    proxy_temp_path {{ data_dir }}/proxy;
    scgi_temp_path {{ data_dir }}/scgi;
    uwsgi_temp_path {{ data_dir }}/uwsgi;

    upstream app {
        server unix:{{ api_socket }};
    }

    server {
        listen {{ port }};
        listen [::]:{{ port }};

        root {{ base_dir }}/static;
        index index.html;

        add_header X-Request-Id $request_id always;

        location / {
            proxy_pass http://app;
        }
    }
}
