// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, infiniteQueryOptions, type InfiniteData, type UseMutationOptions } from "@tanstack/react-query";
import type { AxiosError } from "axios";

import { client as _heyApiClient } from "../client.gen";
import {
  type Options,
  getBootAssetsV1BootassetsGet,
  postBootAssetsV1BootassetsPost,
  getBootSourcesV1BootassetSourcesGet,
  postBootSourcesV1BootassetSourcesPost,
  deleteBootSourceV1BootassetSourcesIdDelete,
  getBootSourceByIdV1BootassetSourcesIdGet,
  patchBootSourceV1BootassetSourcesIdPatch,
  getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet,
  postBootAssetVersionV1BootassetsIdVersionsPost,
  getBootAssetVersionsV1BootassetVersionsGet,
  postBootAssetItemV1BootassetVersionsIdItemsPost,
  getBootAssetItemsV1BootassetItemsGet,
  deleteImagesV1BootassetItemsIdDelete,
  patchBootAssetItemsV1BootassetItemsIdPatch,
  postImagesV1ImagesPost,
  downloadV1ImagesTrackRiskFilePathGet,
  postV1LoginPost,
  getV1SettingsGet,
  patchV1SettingsPatch,
  getPendingV1SitesPendingGet,
  postPendingV1SitesPendingPost,
  deleteManyV1SitesDelete,
  getV1SitesGet,
  getCoordinatesV1SitesCoordinatesGet,
  deleteV1SitesIdDelete,
  getIdV1SitesIdGet,
  patchV1SitesIdPatch,
  deleteManyV1TokensDelete,
  getV1TokensGet,
  postV1TokensPost,
  getExportV1TokensExportGet,
  deleteV1TokensIdDelete,
  getV1UsersGet,
  postV1UsersPost,
  getMeV1UsersMeGet,
  patchMeV1UsersMePatch,
  patchMePasswordV1UsersMePasswordPatch,
  deleteV1UsersIdDelete,
  getIdV1UsersIdGet,
  patchV1UsersIdPatch,
} from "../sdk.gen";
import type {
  GetBootAssetsV1BootassetsGetData,
  GetBootAssetsV1BootassetsGetError,
  GetBootAssetsV1BootassetsGetResponse,
  PostBootAssetsV1BootassetsPostData,
  PostBootAssetsV1BootassetsPostError,
  PostBootAssetsV1BootassetsPostResponse,
  GetBootSourcesV1BootassetSourcesGetData,
  GetBootSourcesV1BootassetSourcesGetError,
  GetBootSourcesV1BootassetSourcesGetResponse,
  PostBootSourcesV1BootassetSourcesPostData,
  PostBootSourcesV1BootassetSourcesPostError,
  PostBootSourcesV1BootassetSourcesPostResponse,
  DeleteBootSourceV1BootassetSourcesIdDeleteData,
  DeleteBootSourceV1BootassetSourcesIdDeleteError,
  GetBootSourceByIdV1BootassetSourcesIdGetData,
  PatchBootSourceV1BootassetSourcesIdPatchData,
  PatchBootSourceV1BootassetSourcesIdPatchError,
  PatchBootSourceV1BootassetSourcesIdPatchResponse,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetError,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponse,
  PostBootAssetVersionV1BootassetsIdVersionsPostData,
  PostBootAssetVersionV1BootassetsIdVersionsPostError,
  PostBootAssetVersionV1BootassetsIdVersionsPostResponse,
  GetBootAssetVersionsV1BootassetVersionsGetData,
  GetBootAssetVersionsV1BootassetVersionsGetError,
  GetBootAssetVersionsV1BootassetVersionsGetResponse,
  PostBootAssetItemV1BootassetVersionsIdItemsPostData,
  PostBootAssetItemV1BootassetVersionsIdItemsPostError,
  PostBootAssetItemV1BootassetVersionsIdItemsPostResponse,
  GetBootAssetItemsV1BootassetItemsGetData,
  GetBootAssetItemsV1BootassetItemsGetError,
  GetBootAssetItemsV1BootassetItemsGetResponse,
  DeleteImagesV1BootassetItemsIdDeleteData,
  DeleteImagesV1BootassetItemsIdDeleteError,
  PatchBootAssetItemsV1BootassetItemsIdPatchData,
  PatchBootAssetItemsV1BootassetItemsIdPatchError,
  PatchBootAssetItemsV1BootassetItemsIdPatchResponse,
  PostImagesV1ImagesPostData,
  PostImagesV1ImagesPostError,
  PostImagesV1ImagesPostResponse,
  DownloadV1ImagesTrackRiskFilePathGetData,
  PostV1LoginPostData,
  PostV1LoginPostError,
  PostV1LoginPostResponse,
  GetV1SettingsGetData,
  PatchV1SettingsPatchData,
  PatchV1SettingsPatchError,
  GetPendingV1SitesPendingGetData,
  GetPendingV1SitesPendingGetError,
  GetPendingV1SitesPendingGetResponse,
  PostPendingV1SitesPendingPostData,
  PostPendingV1SitesPendingPostError,
  PostPendingV1SitesPendingPostResponse,
  DeleteManyV1SitesDeleteData,
  DeleteManyV1SitesDeleteError,
  DeleteManyV1SitesDeleteResponse,
  GetV1SitesGetData,
  GetV1SitesGetError,
  GetV1SitesGetResponse,
  GetCoordinatesV1SitesCoordinatesGetData,
  DeleteV1SitesIdDeleteData,
  DeleteV1SitesIdDeleteError,
  DeleteV1SitesIdDeleteResponse,
  GetIdV1SitesIdGetData,
  PatchV1SitesIdPatchData,
  PatchV1SitesIdPatchError,
  PatchV1SitesIdPatchResponse,
  DeleteManyV1TokensDeleteData,
  DeleteManyV1TokensDeleteError,
  DeleteManyV1TokensDeleteResponse,
  GetV1TokensGetData,
  GetV1TokensGetError,
  GetV1TokensGetResponse,
  PostV1TokensPostData,
  PostV1TokensPostError,
  PostV1TokensPostResponse,
  GetExportV1TokensExportGetData,
  GetExportV1TokensExportGetError,
  DeleteV1TokensIdDeleteData,
  DeleteV1TokensIdDeleteError,
  DeleteV1TokensIdDeleteResponse,
  GetV1UsersGetData,
  GetV1UsersGetError,
  GetV1UsersGetResponse,
  PostV1UsersPostData,
  PostV1UsersPostError,
  PostV1UsersPostResponse,
  GetMeV1UsersMeGetData,
  PatchMeV1UsersMePatchData,
  PatchMeV1UsersMePatchError,
  PatchMeV1UsersMePatchResponse,
  PatchMePasswordV1UsersMePasswordPatchData,
  PatchMePasswordV1UsersMePasswordPatchError,
  DeleteV1UsersIdDeleteData,
  DeleteV1UsersIdDeleteError,
  DeleteV1UsersIdDeleteResponse,
  GetIdV1UsersIdGetData,
  PatchV1UsersIdPatchData,
  PatchV1UsersIdPatchError,
  PatchV1UsersIdPatchResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? _heyApiClient).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getBootAssetsV1BootassetsGetQueryKey = (options?: Options<GetBootAssetsV1BootassetsGetData>) =>
  createQueryKey("getBootAssetsV1BootassetsGet", options);

export const getBootAssetsV1BootassetsGetOptions = (options?: Options<GetBootAssetsV1BootassetsGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBootAssetsV1BootassetsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBootAssetsV1BootassetsGetQueryKey(options),
  });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = queryKey[0];
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getBootAssetsV1BootassetsGetInfiniteQueryKey = (
  options?: Options<GetBootAssetsV1BootassetsGetData>,
): QueryKey<Options<GetBootAssetsV1BootassetsGetData>> => createQueryKey("getBootAssetsV1BootassetsGet", options, true);

export const getBootAssetsV1BootassetsGetInfiniteOptions = (options?: Options<GetBootAssetsV1BootassetsGetData>) => {
  return infiniteQueryOptions<
    GetBootAssetsV1BootassetsGetResponse,
    AxiosError<GetBootAssetsV1BootassetsGetError>,
    InfiniteData<GetBootAssetsV1BootassetsGetResponse>,
    QueryKey<Options<GetBootAssetsV1BootassetsGetData>>,
    number | Pick<QueryKey<Options<GetBootAssetsV1BootassetsGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetBootAssetsV1BootassetsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getBootAssetsV1BootassetsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getBootAssetsV1BootassetsGetInfiniteQueryKey(options),
    },
  );
};

export const postBootAssetsV1BootassetsPostQueryKey = (options: Options<PostBootAssetsV1BootassetsPostData>) =>
  createQueryKey("postBootAssetsV1BootassetsPost", options);

export const postBootAssetsV1BootassetsPostOptions = (options: Options<PostBootAssetsV1BootassetsPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postBootAssetsV1BootassetsPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postBootAssetsV1BootassetsPostQueryKey(options),
  });
};

export const postBootAssetsV1BootassetsPostMutation = (
  options?: Partial<Options<PostBootAssetsV1BootassetsPostData>>,
): UseMutationOptions<
  PostBootAssetsV1BootassetsPostResponse,
  AxiosError<PostBootAssetsV1BootassetsPostError>,
  Options<PostBootAssetsV1BootassetsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PostBootAssetsV1BootassetsPostResponse,
    AxiosError<PostBootAssetsV1BootassetsPostError>,
    Options<PostBootAssetsV1BootassetsPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postBootAssetsV1BootassetsPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBootSourcesV1BootassetSourcesGetQueryKey = (
  options?: Options<GetBootSourcesV1BootassetSourcesGetData>,
) => createQueryKey("getBootSourcesV1BootassetSourcesGet", options);

export const getBootSourcesV1BootassetSourcesGetOptions = (
  options?: Options<GetBootSourcesV1BootassetSourcesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBootSourcesV1BootassetSourcesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBootSourcesV1BootassetSourcesGetQueryKey(options),
  });
};

export const getBootSourcesV1BootassetSourcesGetInfiniteQueryKey = (
  options?: Options<GetBootSourcesV1BootassetSourcesGetData>,
): QueryKey<Options<GetBootSourcesV1BootassetSourcesGetData>> =>
  createQueryKey("getBootSourcesV1BootassetSourcesGet", options, true);

export const getBootSourcesV1BootassetSourcesGetInfiniteOptions = (
  options?: Options<GetBootSourcesV1BootassetSourcesGetData>,
) => {
  return infiniteQueryOptions<
    GetBootSourcesV1BootassetSourcesGetResponse,
    AxiosError<GetBootSourcesV1BootassetSourcesGetError>,
    InfiniteData<GetBootSourcesV1BootassetSourcesGetResponse>,
    QueryKey<Options<GetBootSourcesV1BootassetSourcesGetData>>,
    number | Pick<QueryKey<Options<GetBootSourcesV1BootassetSourcesGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetBootSourcesV1BootassetSourcesGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getBootSourcesV1BootassetSourcesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getBootSourcesV1BootassetSourcesGetInfiniteQueryKey(options),
    },
  );
};

export const postBootSourcesV1BootassetSourcesPostQueryKey = (
  options: Options<PostBootSourcesV1BootassetSourcesPostData>,
) => createQueryKey("postBootSourcesV1BootassetSourcesPost", options);

export const postBootSourcesV1BootassetSourcesPostOptions = (
  options: Options<PostBootSourcesV1BootassetSourcesPostData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postBootSourcesV1BootassetSourcesPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postBootSourcesV1BootassetSourcesPostQueryKey(options),
  });
};

export const postBootSourcesV1BootassetSourcesPostMutation = (
  options?: Partial<Options<PostBootSourcesV1BootassetSourcesPostData>>,
): UseMutationOptions<
  PostBootSourcesV1BootassetSourcesPostResponse,
  AxiosError<PostBootSourcesV1BootassetSourcesPostError>,
  Options<PostBootSourcesV1BootassetSourcesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PostBootSourcesV1BootassetSourcesPostResponse,
    AxiosError<PostBootSourcesV1BootassetSourcesPostError>,
    Options<PostBootSourcesV1BootassetSourcesPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postBootSourcesV1BootassetSourcesPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteBootSourceV1BootassetSourcesIdDeleteMutation = (
  options?: Partial<Options<DeleteBootSourceV1BootassetSourcesIdDeleteData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DeleteBootSourceV1BootassetSourcesIdDeleteError>,
  Options<DeleteBootSourceV1BootassetSourcesIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DeleteBootSourceV1BootassetSourcesIdDeleteError>,
    Options<DeleteBootSourceV1BootassetSourcesIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteBootSourceV1BootassetSourcesIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBootSourceByIdV1BootassetSourcesIdGetQueryKey = (
  options: Options<GetBootSourceByIdV1BootassetSourcesIdGetData>,
) => createQueryKey("getBootSourceByIdV1BootassetSourcesIdGet", options);

export const getBootSourceByIdV1BootassetSourcesIdGetOptions = (
  options: Options<GetBootSourceByIdV1BootassetSourcesIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBootSourceByIdV1BootassetSourcesIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBootSourceByIdV1BootassetSourcesIdGetQueryKey(options),
  });
};

export const patchBootSourceV1BootassetSourcesIdPatchMutation = (
  options?: Partial<Options<PatchBootSourceV1BootassetSourcesIdPatchData>>,
): UseMutationOptions<
  PatchBootSourceV1BootassetSourcesIdPatchResponse,
  AxiosError<PatchBootSourceV1BootassetSourcesIdPatchError>,
  Options<PatchBootSourceV1BootassetSourcesIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchBootSourceV1BootassetSourcesIdPatchResponse,
    AxiosError<PatchBootSourceV1BootassetSourcesIdPatchError>,
    Options<PatchBootSourceV1BootassetSourcesIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchBootSourceV1BootassetSourcesIdPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetQueryKey = (
  options: Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>,
) => createQueryKey("getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet", options);

export const getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetOptions = (
  options: Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetQueryKey(options),
  });
};

export const getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetInfiniteQueryKey = (
  options: Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>,
): QueryKey<Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>> =>
  createQueryKey("getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet", options, true);

export const getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetInfiniteOptions = (
  options: Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>,
) => {
  return infiniteQueryOptions<
    GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponse,
    AxiosError<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetError>,
    InfiniteData<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponse>,
    QueryKey<Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetInfiniteQueryKey(options),
    },
  );
};

export const postBootAssetVersionV1BootassetsIdVersionsPostQueryKey = (
  options: Options<PostBootAssetVersionV1BootassetsIdVersionsPostData>,
) => createQueryKey("postBootAssetVersionV1BootassetsIdVersionsPost", options);

export const postBootAssetVersionV1BootassetsIdVersionsPostOptions = (
  options: Options<PostBootAssetVersionV1BootassetsIdVersionsPostData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postBootAssetVersionV1BootassetsIdVersionsPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postBootAssetVersionV1BootassetsIdVersionsPostQueryKey(options),
  });
};

export const postBootAssetVersionV1BootassetsIdVersionsPostMutation = (
  options?: Partial<Options<PostBootAssetVersionV1BootassetsIdVersionsPostData>>,
): UseMutationOptions<
  PostBootAssetVersionV1BootassetsIdVersionsPostResponse,
  AxiosError<PostBootAssetVersionV1BootassetsIdVersionsPostError>,
  Options<PostBootAssetVersionV1BootassetsIdVersionsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PostBootAssetVersionV1BootassetsIdVersionsPostResponse,
    AxiosError<PostBootAssetVersionV1BootassetsIdVersionsPostError>,
    Options<PostBootAssetVersionV1BootassetsIdVersionsPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postBootAssetVersionV1BootassetsIdVersionsPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBootAssetVersionsV1BootassetVersionsGetQueryKey = (
  options?: Options<GetBootAssetVersionsV1BootassetVersionsGetData>,
) => createQueryKey("getBootAssetVersionsV1BootassetVersionsGet", options);

export const getBootAssetVersionsV1BootassetVersionsGetOptions = (
  options?: Options<GetBootAssetVersionsV1BootassetVersionsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBootAssetVersionsV1BootassetVersionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBootAssetVersionsV1BootassetVersionsGetQueryKey(options),
  });
};

export const getBootAssetVersionsV1BootassetVersionsGetInfiniteQueryKey = (
  options?: Options<GetBootAssetVersionsV1BootassetVersionsGetData>,
): QueryKey<Options<GetBootAssetVersionsV1BootassetVersionsGetData>> =>
  createQueryKey("getBootAssetVersionsV1BootassetVersionsGet", options, true);

export const getBootAssetVersionsV1BootassetVersionsGetInfiniteOptions = (
  options?: Options<GetBootAssetVersionsV1BootassetVersionsGetData>,
) => {
  return infiniteQueryOptions<
    GetBootAssetVersionsV1BootassetVersionsGetResponse,
    AxiosError<GetBootAssetVersionsV1BootassetVersionsGetError>,
    InfiniteData<GetBootAssetVersionsV1BootassetVersionsGetResponse>,
    QueryKey<Options<GetBootAssetVersionsV1BootassetVersionsGetData>>,
    | number
    | Pick<QueryKey<Options<GetBootAssetVersionsV1BootassetVersionsGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetBootAssetVersionsV1BootassetVersionsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getBootAssetVersionsV1BootassetVersionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getBootAssetVersionsV1BootassetVersionsGetInfiniteQueryKey(options),
    },
  );
};

export const postBootAssetItemV1BootassetVersionsIdItemsPostQueryKey = (
  options: Options<PostBootAssetItemV1BootassetVersionsIdItemsPostData>,
) => createQueryKey("postBootAssetItemV1BootassetVersionsIdItemsPost", options);

export const postBootAssetItemV1BootassetVersionsIdItemsPostOptions = (
  options: Options<PostBootAssetItemV1BootassetVersionsIdItemsPostData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postBootAssetItemV1BootassetVersionsIdItemsPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postBootAssetItemV1BootassetVersionsIdItemsPostQueryKey(options),
  });
};

export const postBootAssetItemV1BootassetVersionsIdItemsPostMutation = (
  options?: Partial<Options<PostBootAssetItemV1BootassetVersionsIdItemsPostData>>,
): UseMutationOptions<
  PostBootAssetItemV1BootassetVersionsIdItemsPostResponse,
  AxiosError<PostBootAssetItemV1BootassetVersionsIdItemsPostError>,
  Options<PostBootAssetItemV1BootassetVersionsIdItemsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PostBootAssetItemV1BootassetVersionsIdItemsPostResponse,
    AxiosError<PostBootAssetItemV1BootassetVersionsIdItemsPostError>,
    Options<PostBootAssetItemV1BootassetVersionsIdItemsPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postBootAssetItemV1BootassetVersionsIdItemsPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBootAssetItemsV1BootassetItemsGetQueryKey = (
  options?: Options<GetBootAssetItemsV1BootassetItemsGetData>,
) => createQueryKey("getBootAssetItemsV1BootassetItemsGet", options);

export const getBootAssetItemsV1BootassetItemsGetOptions = (
  options?: Options<GetBootAssetItemsV1BootassetItemsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBootAssetItemsV1BootassetItemsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBootAssetItemsV1BootassetItemsGetQueryKey(options),
  });
};

export const getBootAssetItemsV1BootassetItemsGetInfiniteQueryKey = (
  options?: Options<GetBootAssetItemsV1BootassetItemsGetData>,
): QueryKey<Options<GetBootAssetItemsV1BootassetItemsGetData>> =>
  createQueryKey("getBootAssetItemsV1BootassetItemsGet", options, true);

export const getBootAssetItemsV1BootassetItemsGetInfiniteOptions = (
  options?: Options<GetBootAssetItemsV1BootassetItemsGetData>,
) => {
  return infiniteQueryOptions<
    GetBootAssetItemsV1BootassetItemsGetResponse,
    AxiosError<GetBootAssetItemsV1BootassetItemsGetError>,
    InfiniteData<GetBootAssetItemsV1BootassetItemsGetResponse>,
    QueryKey<Options<GetBootAssetItemsV1BootassetItemsGetData>>,
    number | Pick<QueryKey<Options<GetBootAssetItemsV1BootassetItemsGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetBootAssetItemsV1BootassetItemsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getBootAssetItemsV1BootassetItemsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getBootAssetItemsV1BootassetItemsGetInfiniteQueryKey(options),
    },
  );
};

export const deleteImagesV1BootassetItemsIdDeleteMutation = (
  options?: Partial<Options<DeleteImagesV1BootassetItemsIdDeleteData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DeleteImagesV1BootassetItemsIdDeleteError>,
  Options<DeleteImagesV1BootassetItemsIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DeleteImagesV1BootassetItemsIdDeleteError>,
    Options<DeleteImagesV1BootassetItemsIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteImagesV1BootassetItemsIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const patchBootAssetItemsV1BootassetItemsIdPatchMutation = (
  options?: Partial<Options<PatchBootAssetItemsV1BootassetItemsIdPatchData>>,
): UseMutationOptions<
  PatchBootAssetItemsV1BootassetItemsIdPatchResponse,
  AxiosError<PatchBootAssetItemsV1BootassetItemsIdPatchError>,
  Options<PatchBootAssetItemsV1BootassetItemsIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchBootAssetItemsV1BootassetItemsIdPatchResponse,
    AxiosError<PatchBootAssetItemsV1BootassetItemsIdPatchError>,
    Options<PatchBootAssetItemsV1BootassetItemsIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchBootAssetItemsV1BootassetItemsIdPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postImagesV1ImagesPostQueryKey = (options: Options<PostImagesV1ImagesPostData>) =>
  createQueryKey("postImagesV1ImagesPost", options);

export const postImagesV1ImagesPostOptions = (options: Options<PostImagesV1ImagesPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postImagesV1ImagesPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postImagesV1ImagesPostQueryKey(options),
  });
};

export const postImagesV1ImagesPostMutation = (
  options?: Partial<Options<PostImagesV1ImagesPostData>>,
): UseMutationOptions<
  PostImagesV1ImagesPostResponse,
  AxiosError<PostImagesV1ImagesPostError>,
  Options<PostImagesV1ImagesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PostImagesV1ImagesPostResponse,
    AxiosError<PostImagesV1ImagesPostError>,
    Options<PostImagesV1ImagesPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postImagesV1ImagesPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const downloadV1ImagesTrackRiskFilePathGetQueryKey = (
  options: Options<DownloadV1ImagesTrackRiskFilePathGetData>,
) => createQueryKey("downloadV1ImagesTrackRiskFilePathGet", options);

export const downloadV1ImagesTrackRiskFilePathGetOptions = (
  options: Options<DownloadV1ImagesTrackRiskFilePathGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await downloadV1ImagesTrackRiskFilePathGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: downloadV1ImagesTrackRiskFilePathGetQueryKey(options),
  });
};

export const postV1LoginPostQueryKey = (options: Options<PostV1LoginPostData>) =>
  createQueryKey("postV1LoginPost", options);

export const postV1LoginPostOptions = (options: Options<PostV1LoginPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postV1LoginPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postV1LoginPostQueryKey(options),
  });
};

export const postV1LoginPostMutation = (
  options?: Partial<Options<PostV1LoginPostData>>,
): UseMutationOptions<PostV1LoginPostResponse, AxiosError<PostV1LoginPostError>, Options<PostV1LoginPostData>> => {
  const mutationOptions: UseMutationOptions<
    PostV1LoginPostResponse,
    AxiosError<PostV1LoginPostError>,
    Options<PostV1LoginPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postV1LoginPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getV1SettingsGetQueryKey = (options?: Options<GetV1SettingsGetData>) =>
  createQueryKey("getV1SettingsGet", options);

export const getV1SettingsGetOptions = (options?: Options<GetV1SettingsGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1SettingsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1SettingsGetQueryKey(options),
  });
};

export const patchV1SettingsPatchMutation = (
  options?: Partial<Options<PatchV1SettingsPatchData>>,
): UseMutationOptions<unknown, AxiosError<PatchV1SettingsPatchError>, Options<PatchV1SettingsPatchData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<PatchV1SettingsPatchError>,
    Options<PatchV1SettingsPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchV1SettingsPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPendingV1SitesPendingGetQueryKey = (options?: Options<GetPendingV1SitesPendingGetData>) =>
  createQueryKey("getPendingV1SitesPendingGet", options);

export const getPendingV1SitesPendingGetOptions = (options?: Options<GetPendingV1SitesPendingGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPendingV1SitesPendingGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPendingV1SitesPendingGetQueryKey(options),
  });
};

export const getPendingV1SitesPendingGetInfiniteQueryKey = (
  options?: Options<GetPendingV1SitesPendingGetData>,
): QueryKey<Options<GetPendingV1SitesPendingGetData>> => createQueryKey("getPendingV1SitesPendingGet", options, true);

export const getPendingV1SitesPendingGetInfiniteOptions = (options?: Options<GetPendingV1SitesPendingGetData>) => {
  return infiniteQueryOptions<
    GetPendingV1SitesPendingGetResponse,
    AxiosError<GetPendingV1SitesPendingGetError>,
    InfiniteData<GetPendingV1SitesPendingGetResponse>,
    QueryKey<Options<GetPendingV1SitesPendingGetData>>,
    number | Pick<QueryKey<Options<GetPendingV1SitesPendingGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetPendingV1SitesPendingGetData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPendingV1SitesPendingGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getPendingV1SitesPendingGetInfiniteQueryKey(options),
    },
  );
};

export const postPendingV1SitesPendingPostQueryKey = (options: Options<PostPendingV1SitesPendingPostData>) =>
  createQueryKey("postPendingV1SitesPendingPost", options);

export const postPendingV1SitesPendingPostOptions = (options: Options<PostPendingV1SitesPendingPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postPendingV1SitesPendingPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postPendingV1SitesPendingPostQueryKey(options),
  });
};

export const postPendingV1SitesPendingPostMutation = (
  options?: Partial<Options<PostPendingV1SitesPendingPostData>>,
): UseMutationOptions<
  PostPendingV1SitesPendingPostResponse,
  AxiosError<PostPendingV1SitesPendingPostError>,
  Options<PostPendingV1SitesPendingPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PostPendingV1SitesPendingPostResponse,
    AxiosError<PostPendingV1SitesPendingPostError>,
    Options<PostPendingV1SitesPendingPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postPendingV1SitesPendingPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteManyV1SitesDeleteMutation = (
  options?: Partial<Options<DeleteManyV1SitesDeleteData>>,
): UseMutationOptions<
  DeleteManyV1SitesDeleteResponse,
  AxiosError<DeleteManyV1SitesDeleteError>,
  Options<DeleteManyV1SitesDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteManyV1SitesDeleteResponse,
    AxiosError<DeleteManyV1SitesDeleteError>,
    Options<DeleteManyV1SitesDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteManyV1SitesDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getV1SitesGetQueryKey = (options?: Options<GetV1SitesGetData>) => createQueryKey("getV1SitesGet", options);

export const getV1SitesGetOptions = (options?: Options<GetV1SitesGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1SitesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1SitesGetQueryKey(options),
  });
};

export const getV1SitesGetInfiniteQueryKey = (
  options?: Options<GetV1SitesGetData>,
): QueryKey<Options<GetV1SitesGetData>> => createQueryKey("getV1SitesGet", options, true);

export const getV1SitesGetInfiniteOptions = (options?: Options<GetV1SitesGetData>) => {
  return infiniteQueryOptions<
    GetV1SitesGetResponse,
    AxiosError<GetV1SitesGetError>,
    InfiniteData<GetV1SitesGetResponse>,
    QueryKey<Options<GetV1SitesGetData>>,
    number | Pick<QueryKey<Options<GetV1SitesGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetV1SitesGetData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getV1SitesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getV1SitesGetInfiniteQueryKey(options),
    },
  );
};

export const getCoordinatesV1SitesCoordinatesGetQueryKey = (
  options?: Options<GetCoordinatesV1SitesCoordinatesGetData>,
) => createQueryKey("getCoordinatesV1SitesCoordinatesGet", options);

export const getCoordinatesV1SitesCoordinatesGetOptions = (
  options?: Options<GetCoordinatesV1SitesCoordinatesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCoordinatesV1SitesCoordinatesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCoordinatesV1SitesCoordinatesGetQueryKey(options),
  });
};

export const deleteV1SitesIdDeleteMutation = (
  options?: Partial<Options<DeleteV1SitesIdDeleteData>>,
): UseMutationOptions<
  DeleteV1SitesIdDeleteResponse,
  AxiosError<DeleteV1SitesIdDeleteError>,
  Options<DeleteV1SitesIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteV1SitesIdDeleteResponse,
    AxiosError<DeleteV1SitesIdDeleteError>,
    Options<DeleteV1SitesIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteV1SitesIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getIdV1SitesIdGetQueryKey = (options: Options<GetIdV1SitesIdGetData>) =>
  createQueryKey("getIdV1SitesIdGet", options);

export const getIdV1SitesIdGetOptions = (options: Options<GetIdV1SitesIdGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getIdV1SitesIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getIdV1SitesIdGetQueryKey(options),
  });
};

export const patchV1SitesIdPatchMutation = (
  options?: Partial<Options<PatchV1SitesIdPatchData>>,
): UseMutationOptions<
  PatchV1SitesIdPatchResponse,
  AxiosError<PatchV1SitesIdPatchError>,
  Options<PatchV1SitesIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchV1SitesIdPatchResponse,
    AxiosError<PatchV1SitesIdPatchError>,
    Options<PatchV1SitesIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchV1SitesIdPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteManyV1TokensDeleteMutation = (
  options?: Partial<Options<DeleteManyV1TokensDeleteData>>,
): UseMutationOptions<
  DeleteManyV1TokensDeleteResponse,
  AxiosError<DeleteManyV1TokensDeleteError>,
  Options<DeleteManyV1TokensDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteManyV1TokensDeleteResponse,
    AxiosError<DeleteManyV1TokensDeleteError>,
    Options<DeleteManyV1TokensDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteManyV1TokensDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getV1TokensGetQueryKey = (options?: Options<GetV1TokensGetData>) =>
  createQueryKey("getV1TokensGet", options);

export const getV1TokensGetOptions = (options?: Options<GetV1TokensGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1TokensGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1TokensGetQueryKey(options),
  });
};

export const getV1TokensGetInfiniteQueryKey = (
  options?: Options<GetV1TokensGetData>,
): QueryKey<Options<GetV1TokensGetData>> => createQueryKey("getV1TokensGet", options, true);

export const getV1TokensGetInfiniteOptions = (options?: Options<GetV1TokensGetData>) => {
  return infiniteQueryOptions<
    GetV1TokensGetResponse,
    AxiosError<GetV1TokensGetError>,
    InfiniteData<GetV1TokensGetResponse>,
    QueryKey<Options<GetV1TokensGetData>>,
    number | Pick<QueryKey<Options<GetV1TokensGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetV1TokensGetData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getV1TokensGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getV1TokensGetInfiniteQueryKey(options),
    },
  );
};

export const postV1TokensPostQueryKey = (options: Options<PostV1TokensPostData>) =>
  createQueryKey("postV1TokensPost", options);

export const postV1TokensPostOptions = (options: Options<PostV1TokensPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postV1TokensPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postV1TokensPostQueryKey(options),
  });
};

export const postV1TokensPostMutation = (
  options?: Partial<Options<PostV1TokensPostData>>,
): UseMutationOptions<PostV1TokensPostResponse, AxiosError<PostV1TokensPostError>, Options<PostV1TokensPostData>> => {
  const mutationOptions: UseMutationOptions<
    PostV1TokensPostResponse,
    AxiosError<PostV1TokensPostError>,
    Options<PostV1TokensPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postV1TokensPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExportV1TokensExportGetQueryKey = (options?: Options<GetExportV1TokensExportGetData>) =>
  createQueryKey("getExportV1TokensExportGet", options);

export const getExportV1TokensExportGetOptions = (options?: Options<GetExportV1TokensExportGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExportV1TokensExportGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExportV1TokensExportGetQueryKey(options),
  });
};

export const getExportV1TokensExportGetInfiniteQueryKey = (
  options?: Options<GetExportV1TokensExportGetData>,
): QueryKey<Options<GetExportV1TokensExportGetData>> => createQueryKey("getExportV1TokensExportGet", options, true);

export const getExportV1TokensExportGetInfiniteOptions = (options?: Options<GetExportV1TokensExportGetData>) => {
  return infiniteQueryOptions<
    unknown,
    AxiosError<GetExportV1TokensExportGetError>,
    InfiniteData<unknown>,
    QueryKey<Options<GetExportV1TokensExportGetData>>,
    number | Pick<QueryKey<Options<GetExportV1TokensExportGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetExportV1TokensExportGetData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getExportV1TokensExportGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getExportV1TokensExportGetInfiniteQueryKey(options),
    },
  );
};

export const deleteV1TokensIdDeleteMutation = (
  options?: Partial<Options<DeleteV1TokensIdDeleteData>>,
): UseMutationOptions<
  DeleteV1TokensIdDeleteResponse,
  AxiosError<DeleteV1TokensIdDeleteError>,
  Options<DeleteV1TokensIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteV1TokensIdDeleteResponse,
    AxiosError<DeleteV1TokensIdDeleteError>,
    Options<DeleteV1TokensIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteV1TokensIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getV1UsersGetQueryKey = (options?: Options<GetV1UsersGetData>) => createQueryKey("getV1UsersGet", options);

export const getV1UsersGetOptions = (options?: Options<GetV1UsersGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1UsersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1UsersGetQueryKey(options),
  });
};

export const getV1UsersGetInfiniteQueryKey = (
  options?: Options<GetV1UsersGetData>,
): QueryKey<Options<GetV1UsersGetData>> => createQueryKey("getV1UsersGet", options, true);

export const getV1UsersGetInfiniteOptions = (options?: Options<GetV1UsersGetData>) => {
  return infiniteQueryOptions<
    GetV1UsersGetResponse,
    AxiosError<GetV1UsersGetError>,
    InfiniteData<GetV1UsersGetResponse>,
    QueryKey<Options<GetV1UsersGetData>>,
    number | Pick<QueryKey<Options<GetV1UsersGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetV1UsersGetData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getV1UsersGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getV1UsersGetInfiniteQueryKey(options),
    },
  );
};

export const postV1UsersPostQueryKey = (options: Options<PostV1UsersPostData>) =>
  createQueryKey("postV1UsersPost", options);

export const postV1UsersPostOptions = (options: Options<PostV1UsersPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postV1UsersPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postV1UsersPostQueryKey(options),
  });
};

export const postV1UsersPostMutation = (
  options?: Partial<Options<PostV1UsersPostData>>,
): UseMutationOptions<PostV1UsersPostResponse, AxiosError<PostV1UsersPostError>, Options<PostV1UsersPostData>> => {
  const mutationOptions: UseMutationOptions<
    PostV1UsersPostResponse,
    AxiosError<PostV1UsersPostError>,
    Options<PostV1UsersPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postV1UsersPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMeV1UsersMeGetQueryKey = (options?: Options<GetMeV1UsersMeGetData>) =>
  createQueryKey("getMeV1UsersMeGet", options);

export const getMeV1UsersMeGetOptions = (options?: Options<GetMeV1UsersMeGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMeV1UsersMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMeV1UsersMeGetQueryKey(options),
  });
};

export const patchMeV1UsersMePatchMutation = (
  options?: Partial<Options<PatchMeV1UsersMePatchData>>,
): UseMutationOptions<
  PatchMeV1UsersMePatchResponse,
  AxiosError<PatchMeV1UsersMePatchError>,
  Options<PatchMeV1UsersMePatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchMeV1UsersMePatchResponse,
    AxiosError<PatchMeV1UsersMePatchError>,
    Options<PatchMeV1UsersMePatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchMeV1UsersMePatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const patchMePasswordV1UsersMePasswordPatchMutation = (
  options?: Partial<Options<PatchMePasswordV1UsersMePasswordPatchData>>,
): UseMutationOptions<
  unknown,
  AxiosError<PatchMePasswordV1UsersMePasswordPatchError>,
  Options<PatchMePasswordV1UsersMePasswordPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<PatchMePasswordV1UsersMePasswordPatchError>,
    Options<PatchMePasswordV1UsersMePasswordPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchMePasswordV1UsersMePasswordPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteV1UsersIdDeleteMutation = (
  options?: Partial<Options<DeleteV1UsersIdDeleteData>>,
): UseMutationOptions<
  DeleteV1UsersIdDeleteResponse,
  AxiosError<DeleteV1UsersIdDeleteError>,
  Options<DeleteV1UsersIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteV1UsersIdDeleteResponse,
    AxiosError<DeleteV1UsersIdDeleteError>,
    Options<DeleteV1UsersIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteV1UsersIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getIdV1UsersIdGetQueryKey = (options: Options<GetIdV1UsersIdGetData>) =>
  createQueryKey("getIdV1UsersIdGet", options);

export const getIdV1UsersIdGetOptions = (options: Options<GetIdV1UsersIdGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getIdV1UsersIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getIdV1UsersIdGetQueryKey(options),
  });
};

export const patchV1UsersIdPatchMutation = (
  options?: Partial<Options<PatchV1UsersIdPatchData>>,
): UseMutationOptions<
  PatchV1UsersIdPatchResponse,
  AxiosError<PatchV1UsersIdPatchError>,
  Options<PatchV1UsersIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchV1UsersIdPatchResponse,
    AxiosError<PatchV1UsersIdPatchError>,
    Options<PatchV1UsersIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchV1UsersIdPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
