// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  getBootSourcesV1BootassetSourcesGet,
  postBootSourcesV1BootassetSourcesPost,
  deleteBootSourceV1BootassetSourcesIdDelete,
  getBootSourceByIdV1BootassetSourcesIdGet,
  patchBootSourceV1BootassetSourcesIdPatch,
  removeVersionsV1BootassetVersionsRemovePost,
  getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet,
  putBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPut,
  getSourceAssetsV1BootassetSourcesIdVersionsGet,
  putBootSourceAssetsV1BootassetSourcesIdAssetsPut,
  getBootAssetItemV1BootassetItemsIdGet,
  patchBootAssetItemsV1BootassetItemsIdPatch,
  postImagesV1ImagesPost,
  deleteImagesV1ImagesRemovePost,
  refreshIndexV1RefreshIndexGet,
  postV1LoginPost,
  selectImagesV1SelectableImagesSelectPost,
  getSelectableImagesV1SelectableImagesGet,
  getSelectedImagesV1SelectedImagesGet,
  removeSelectionsV1SelectedImagesRemovePost,
  getImageSourcesV1ImageSourcesGet,
  getV1SettingsGet,
  patchV1SettingsPatch,
  getPendingV1SitesPendingGet,
  postPendingV1SitesPendingPost,
  deleteManyV1SitesDelete,
  getV1SitesGet,
  getCoordinatesV1SitesCoordinatesGet,
  deleteV1SitesIdDelete,
  getIdV1SitesIdGet,
  patchV1SitesIdPatch,
  deleteManyV1TokensDelete,
  getV1TokensGet,
  postV1TokensPost,
  getExportV1TokensExportGet,
  deleteV1TokensIdDelete,
  getV1UsersGet,
  postV1UsersPost,
  getMeV1UsersMeGet,
  patchMeV1UsersMePatch,
  patchMePasswordV1UsersMePasswordPatch,
  deleteV1UsersIdDelete,
  getIdV1UsersIdGet,
  patchV1UsersIdPatch,
} from "../sdk.gen";
import { queryOptions, infiniteQueryOptions, type InfiniteData, type UseMutationOptions } from "@tanstack/react-query";
import type {
  GetBootSourcesV1BootassetSourcesGetData,
  GetBootSourcesV1BootassetSourcesGetError,
  GetBootSourcesV1BootassetSourcesGetResponse,
  PostBootSourcesV1BootassetSourcesPostData,
  PostBootSourcesV1BootassetSourcesPostError,
  PostBootSourcesV1BootassetSourcesPostResponse,
  DeleteBootSourceV1BootassetSourcesIdDeleteData,
  DeleteBootSourceV1BootassetSourcesIdDeleteError,
  GetBootSourceByIdV1BootassetSourcesIdGetData,
  PatchBootSourceV1BootassetSourcesIdPatchData,
  PatchBootSourceV1BootassetSourcesIdPatchError,
  PatchBootSourceV1BootassetSourcesIdPatchResponse,
  RemoveVersionsV1BootassetVersionsRemovePostData,
  RemoveVersionsV1BootassetVersionsRemovePostError,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetError,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponse,
  PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutData,
  PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutError,
  PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutResponse,
  GetSourceAssetsV1BootassetSourcesIdVersionsGetData,
  PutBootSourceAssetsV1BootassetSourcesIdAssetsPutData,
  PutBootSourceAssetsV1BootassetSourcesIdAssetsPutError,
  PutBootSourceAssetsV1BootassetSourcesIdAssetsPutResponse,
  GetBootAssetItemV1BootassetItemsIdGetData,
  PatchBootAssetItemsV1BootassetItemsIdPatchData,
  PatchBootAssetItemsV1BootassetItemsIdPatchError,
  PatchBootAssetItemsV1BootassetItemsIdPatchResponse,
  PostImagesV1ImagesPostData,
  PostImagesV1ImagesPostError,
  PostImagesV1ImagesPostResponse,
  DeleteImagesV1ImagesRemovePostData,
  DeleteImagesV1ImagesRemovePostError,
  DeleteImagesV1ImagesRemovePostResponse,
  RefreshIndexV1RefreshIndexGetData,
  PostV1LoginPostData,
  PostV1LoginPostError,
  PostV1LoginPostResponse,
  SelectImagesV1SelectableImagesSelectPostData,
  SelectImagesV1SelectableImagesSelectPostError,
  GetSelectableImagesV1SelectableImagesGetData,
  GetSelectedImagesV1SelectedImagesGetData,
  RemoveSelectionsV1SelectedImagesRemovePostData,
  RemoveSelectionsV1SelectedImagesRemovePostError,
  RemoveSelectionsV1SelectedImagesRemovePostResponse,
  GetImageSourcesV1ImageSourcesGetData,
  GetV1SettingsGetData,
  PatchV1SettingsPatchData,
  PatchV1SettingsPatchError,
  GetPendingV1SitesPendingGetData,
  GetPendingV1SitesPendingGetError,
  GetPendingV1SitesPendingGetResponse,
  PostPendingV1SitesPendingPostData,
  PostPendingV1SitesPendingPostError,
  PostPendingV1SitesPendingPostResponse,
  DeleteManyV1SitesDeleteData,
  DeleteManyV1SitesDeleteError,
  DeleteManyV1SitesDeleteResponse,
  GetV1SitesGetData,
  GetV1SitesGetError,
  GetV1SitesGetResponse,
  GetCoordinatesV1SitesCoordinatesGetData,
  DeleteV1SitesIdDeleteData,
  DeleteV1SitesIdDeleteError,
  DeleteV1SitesIdDeleteResponse,
  GetIdV1SitesIdGetData,
  PatchV1SitesIdPatchData,
  PatchV1SitesIdPatchError,
  PatchV1SitesIdPatchResponse,
  DeleteManyV1TokensDeleteData,
  DeleteManyV1TokensDeleteError,
  DeleteManyV1TokensDeleteResponse,
  GetV1TokensGetData,
  GetV1TokensGetError,
  GetV1TokensGetResponse,
  PostV1TokensPostData,
  PostV1TokensPostError,
  PostV1TokensPostResponse,
  GetExportV1TokensExportGetData,
  GetExportV1TokensExportGetError,
  DeleteV1TokensIdDeleteData,
  DeleteV1TokensIdDeleteError,
  DeleteV1TokensIdDeleteResponse,
  GetV1UsersGetData,
  GetV1UsersGetError,
  GetV1UsersGetResponse,
  PostV1UsersPostData,
  PostV1UsersPostError,
  PostV1UsersPostResponse,
  GetMeV1UsersMeGetData,
  PatchMeV1UsersMePatchData,
  PatchMeV1UsersMePatchError,
  PatchMeV1UsersMePatchResponse,
  PatchMePasswordV1UsersMePasswordPatchData,
  PatchMePasswordV1UsersMePasswordPatchError,
  DeleteV1UsersIdDeleteData,
  DeleteV1UsersIdDeleteError,
  DeleteV1UsersIdDeleteResponse,
  GetIdV1UsersIdGetData,
  PatchV1UsersIdPatchData,
  PatchV1UsersIdPatchError,
  PatchV1UsersIdPatchResponse,
} from "../types.gen";
import type { AxiosError } from "axios";
import { client as _heyApiClient } from "../client.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? _heyApiClient).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getBootSourcesV1BootassetSourcesGetQueryKey = (
  options?: Options<GetBootSourcesV1BootassetSourcesGetData>,
) => createQueryKey("getBootSourcesV1BootassetSourcesGet", options);

/**
 * Get Boot Sources
 * Return boot sources.
 */
export const getBootSourcesV1BootassetSourcesGetOptions = (
  options?: Options<GetBootSourcesV1BootassetSourcesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBootSourcesV1BootassetSourcesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBootSourcesV1BootassetSourcesGetQueryKey(options),
  });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getBootSourcesV1BootassetSourcesGetInfiniteQueryKey = (
  options?: Options<GetBootSourcesV1BootassetSourcesGetData>,
): QueryKey<Options<GetBootSourcesV1BootassetSourcesGetData>> =>
  createQueryKey("getBootSourcesV1BootassetSourcesGet", options, true);

/**
 * Get Boot Sources
 * Return boot sources.
 */
export const getBootSourcesV1BootassetSourcesGetInfiniteOptions = (
  options?: Options<GetBootSourcesV1BootassetSourcesGetData>,
) => {
  return infiniteQueryOptions<
    GetBootSourcesV1BootassetSourcesGetResponse,
    AxiosError<GetBootSourcesV1BootassetSourcesGetError>,
    InfiniteData<GetBootSourcesV1BootassetSourcesGetResponse>,
    QueryKey<Options<GetBootSourcesV1BootassetSourcesGetData>>,
    number | Pick<QueryKey<Options<GetBootSourcesV1BootassetSourcesGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetBootSourcesV1BootassetSourcesGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getBootSourcesV1BootassetSourcesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getBootSourcesV1BootassetSourcesGetInfiniteQueryKey(options),
    },
  );
};

export const postBootSourcesV1BootassetSourcesPostQueryKey = (
  options: Options<PostBootSourcesV1BootassetSourcesPostData>,
) => createQueryKey("postBootSourcesV1BootassetSourcesPost", options);

/**
 * Post Boot Sources
 */
export const postBootSourcesV1BootassetSourcesPostOptions = (
  options: Options<PostBootSourcesV1BootassetSourcesPostData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postBootSourcesV1BootassetSourcesPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postBootSourcesV1BootassetSourcesPostQueryKey(options),
  });
};

/**
 * Post Boot Sources
 */
export const postBootSourcesV1BootassetSourcesPostMutation = (
  options?: Partial<Options<PostBootSourcesV1BootassetSourcesPostData>>,
): UseMutationOptions<
  PostBootSourcesV1BootassetSourcesPostResponse,
  AxiosError<PostBootSourcesV1BootassetSourcesPostError>,
  Options<PostBootSourcesV1BootassetSourcesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PostBootSourcesV1BootassetSourcesPostResponse,
    AxiosError<PostBootSourcesV1BootassetSourcesPostError>,
    Options<PostBootSourcesV1BootassetSourcesPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postBootSourcesV1BootassetSourcesPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Boot Source
 */
export const deleteBootSourceV1BootassetSourcesIdDeleteMutation = (
  options?: Partial<Options<DeleteBootSourceV1BootassetSourcesIdDeleteData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DeleteBootSourceV1BootassetSourcesIdDeleteError>,
  Options<DeleteBootSourceV1BootassetSourcesIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DeleteBootSourceV1BootassetSourcesIdDeleteError>,
    Options<DeleteBootSourceV1BootassetSourcesIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteBootSourceV1BootassetSourcesIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBootSourceByIdV1BootassetSourcesIdGetQueryKey = (
  options: Options<GetBootSourceByIdV1BootassetSourcesIdGetData>,
) => createQueryKey("getBootSourceByIdV1BootassetSourcesIdGet", options);

/**
 * Get Boot Source By Id
 */
export const getBootSourceByIdV1BootassetSourcesIdGetOptions = (
  options: Options<GetBootSourceByIdV1BootassetSourcesIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBootSourceByIdV1BootassetSourcesIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBootSourceByIdV1BootassetSourcesIdGetQueryKey(options),
  });
};

/**
 * Patch Boot Source
 */
export const patchBootSourceV1BootassetSourcesIdPatchMutation = (
  options?: Partial<Options<PatchBootSourceV1BootassetSourcesIdPatchData>>,
): UseMutationOptions<
  PatchBootSourceV1BootassetSourcesIdPatchResponse,
  AxiosError<PatchBootSourceV1BootassetSourcesIdPatchError>,
  Options<PatchBootSourceV1BootassetSourcesIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchBootSourceV1BootassetSourcesIdPatchResponse,
    AxiosError<PatchBootSourceV1BootassetSourcesIdPatchError>,
    Options<PatchBootSourceV1BootassetSourcesIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchBootSourceV1BootassetSourcesIdPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const removeVersionsV1BootassetVersionsRemovePostQueryKey = (
  options: Options<RemoveVersionsV1BootassetVersionsRemovePostData>,
) => createQueryKey("removeVersionsV1BootassetVersionsRemovePost", options);

/**
 * Remove Versions
 */
export const removeVersionsV1BootassetVersionsRemovePostOptions = (
  options: Options<RemoveVersionsV1BootassetVersionsRemovePostData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await removeVersionsV1BootassetVersionsRemovePost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: removeVersionsV1BootassetVersionsRemovePostQueryKey(options),
  });
};

/**
 * Remove Versions
 */
export const removeVersionsV1BootassetVersionsRemovePostMutation = (
  options?: Partial<Options<RemoveVersionsV1BootassetVersionsRemovePostData>>,
): UseMutationOptions<
  unknown,
  AxiosError<RemoveVersionsV1BootassetVersionsRemovePostError>,
  Options<RemoveVersionsV1BootassetVersionsRemovePostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<RemoveVersionsV1BootassetVersionsRemovePostError>,
    Options<RemoveVersionsV1BootassetVersionsRemovePostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await removeVersionsV1BootassetVersionsRemovePost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetQueryKey = (
  options: Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>,
) => createQueryKey("getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet", options);

/**
 * Get Boot Source Selections
 * Return boot source selections.
 */
export const getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetOptions = (
  options: Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetQueryKey(options),
  });
};

export const getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetInfiniteQueryKey = (
  options: Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>,
): QueryKey<Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>> =>
  createQueryKey("getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet", options, true);

/**
 * Get Boot Source Selections
 * Return boot source selections.
 */
export const getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetInfiniteOptions = (
  options: Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>,
) => {
  return infiniteQueryOptions<
    GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponse,
    AxiosError<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetError>,
    InfiniteData<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponse>,
    QueryKey<Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getBootSourceSelectionsV1BootassetSourcesIdSelectionsGetInfiniteQueryKey(options),
    },
  );
};

/**
 * Put Boot Source Avail Selections
 */
export const putBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutMutation = (
  options?: Partial<Options<PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutData>>,
): UseMutationOptions<
  PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutResponse,
  AxiosError<PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutError>,
  Options<PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutData>
> => {
  const mutationOptions: UseMutationOptions<
    PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutResponse,
    AxiosError<PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutError>,
    Options<PutBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await putBootSourceAvailSelectionsV1BootassetSourcesIdAvailableSelectionsPut({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSourceAssetsV1BootassetSourcesIdVersionsGetQueryKey = (
  options: Options<GetSourceAssetsV1BootassetSourcesIdVersionsGetData>,
) => createQueryKey("getSourceAssetsV1BootassetSourcesIdVersionsGet", options);

/**
 * Get Source Assets
 * Return a list of assets, with their versions.
 */
export const getSourceAssetsV1BootassetSourcesIdVersionsGetOptions = (
  options: Options<GetSourceAssetsV1BootassetSourcesIdVersionsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSourceAssetsV1BootassetSourcesIdVersionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSourceAssetsV1BootassetSourcesIdVersionsGetQueryKey(options),
  });
};

/**
 * Put Boot Source Assets
 */
export const putBootSourceAssetsV1BootassetSourcesIdAssetsPutMutation = (
  options?: Partial<Options<PutBootSourceAssetsV1BootassetSourcesIdAssetsPutData>>,
): UseMutationOptions<
  PutBootSourceAssetsV1BootassetSourcesIdAssetsPutResponse,
  AxiosError<PutBootSourceAssetsV1BootassetSourcesIdAssetsPutError>,
  Options<PutBootSourceAssetsV1BootassetSourcesIdAssetsPutData>
> => {
  const mutationOptions: UseMutationOptions<
    PutBootSourceAssetsV1BootassetSourcesIdAssetsPutResponse,
    AxiosError<PutBootSourceAssetsV1BootassetSourcesIdAssetsPutError>,
    Options<PutBootSourceAssetsV1BootassetSourcesIdAssetsPutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await putBootSourceAssetsV1BootassetSourcesIdAssetsPut({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBootAssetItemV1BootassetItemsIdGetQueryKey = (
  options: Options<GetBootAssetItemV1BootassetItemsIdGetData>,
) => createQueryKey("getBootAssetItemV1BootassetItemsIdGet", options);

/**
 * Get Boot Asset Item
 */
export const getBootAssetItemV1BootassetItemsIdGetOptions = (
  options: Options<GetBootAssetItemV1BootassetItemsIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBootAssetItemV1BootassetItemsIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBootAssetItemV1BootassetItemsIdGetQueryKey(options),
  });
};

/**
 * Patch Boot Asset Items
 */
export const patchBootAssetItemsV1BootassetItemsIdPatchMutation = (
  options?: Partial<Options<PatchBootAssetItemsV1BootassetItemsIdPatchData>>,
): UseMutationOptions<
  PatchBootAssetItemsV1BootassetItemsIdPatchResponse,
  AxiosError<PatchBootAssetItemsV1BootassetItemsIdPatchError>,
  Options<PatchBootAssetItemsV1BootassetItemsIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchBootAssetItemsV1BootassetItemsIdPatchResponse,
    AxiosError<PatchBootAssetItemsV1BootassetItemsIdPatchError>,
    Options<PatchBootAssetItemsV1BootassetItemsIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchBootAssetItemsV1BootassetItemsIdPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postImagesV1ImagesPostQueryKey = (options: Options<PostImagesV1ImagesPostData>) =>
  createQueryKey("postImagesV1ImagesPost", options);

/**
 * Post Images
 */
export const postImagesV1ImagesPostOptions = (options: Options<PostImagesV1ImagesPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postImagesV1ImagesPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postImagesV1ImagesPostQueryKey(options),
  });
};

/**
 * Post Images
 */
export const postImagesV1ImagesPostMutation = (
  options?: Partial<Options<PostImagesV1ImagesPostData>>,
): UseMutationOptions<
  PostImagesV1ImagesPostResponse,
  AxiosError<PostImagesV1ImagesPostError>,
  Options<PostImagesV1ImagesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PostImagesV1ImagesPostResponse,
    AxiosError<PostImagesV1ImagesPostError>,
    Options<PostImagesV1ImagesPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postImagesV1ImagesPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteImagesV1ImagesRemovePostQueryKey = (options: Options<DeleteImagesV1ImagesRemovePostData>) =>
  createQueryKey("deleteImagesV1ImagesRemovePost", options);

/**
 * Delete Images
 */
export const deleteImagesV1ImagesRemovePostOptions = (options: Options<DeleteImagesV1ImagesRemovePostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await deleteImagesV1ImagesRemovePost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: deleteImagesV1ImagesRemovePostQueryKey(options),
  });
};

/**
 * Delete Images
 */
export const deleteImagesV1ImagesRemovePostMutation = (
  options?: Partial<Options<DeleteImagesV1ImagesRemovePostData>>,
): UseMutationOptions<
  DeleteImagesV1ImagesRemovePostResponse,
  AxiosError<DeleteImagesV1ImagesRemovePostError>,
  Options<DeleteImagesV1ImagesRemovePostData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteImagesV1ImagesRemovePostResponse,
    AxiosError<DeleteImagesV1ImagesRemovePostError>,
    Options<DeleteImagesV1ImagesRemovePostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteImagesV1ImagesRemovePost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const refreshIndexV1RefreshIndexGetQueryKey = (options?: Options<RefreshIndexV1RefreshIndexGetData>) =>
  createQueryKey("refreshIndexV1RefreshIndexGet", options);

/**
 * Refresh Index
 */
export const refreshIndexV1RefreshIndexGetOptions = (options?: Options<RefreshIndexV1RefreshIndexGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await refreshIndexV1RefreshIndexGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: refreshIndexV1RefreshIndexGetQueryKey(options),
  });
};

export const postV1LoginPostQueryKey = (options: Options<PostV1LoginPostData>) =>
  createQueryKey("postV1LoginPost", options);

/**
 * Post
 */
export const postV1LoginPostOptions = (options: Options<PostV1LoginPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postV1LoginPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postV1LoginPostQueryKey(options),
  });
};

/**
 * Post
 */
export const postV1LoginPostMutation = (
  options?: Partial<Options<PostV1LoginPostData>>,
): UseMutationOptions<PostV1LoginPostResponse, AxiosError<PostV1LoginPostError>, Options<PostV1LoginPostData>> => {
  const mutationOptions: UseMutationOptions<
    PostV1LoginPostResponse,
    AxiosError<PostV1LoginPostError>,
    Options<PostV1LoginPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postV1LoginPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const selectImagesV1SelectableImagesSelectPostQueryKey = (
  options: Options<SelectImagesV1SelectableImagesSelectPostData>,
) => createQueryKey("selectImagesV1SelectableImagesSelectPost", options);

/**
 * Select Images
 */
export const selectImagesV1SelectableImagesSelectPostOptions = (
  options: Options<SelectImagesV1SelectableImagesSelectPostData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await selectImagesV1SelectableImagesSelectPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: selectImagesV1SelectableImagesSelectPostQueryKey(options),
  });
};

/**
 * Select Images
 */
export const selectImagesV1SelectableImagesSelectPostMutation = (
  options?: Partial<Options<SelectImagesV1SelectableImagesSelectPostData>>,
): UseMutationOptions<
  unknown,
  AxiosError<SelectImagesV1SelectableImagesSelectPostError>,
  Options<SelectImagesV1SelectableImagesSelectPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<SelectImagesV1SelectableImagesSelectPostError>,
    Options<SelectImagesV1SelectableImagesSelectPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await selectImagesV1SelectableImagesSelectPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSelectableImagesV1SelectableImagesGetQueryKey = (
  options?: Options<GetSelectableImagesV1SelectableImagesGetData>,
) => createQueryKey("getSelectableImagesV1SelectableImagesGet", options);

/**
 * Get Selectable Images
 */
export const getSelectableImagesV1SelectableImagesGetOptions = (
  options?: Options<GetSelectableImagesV1SelectableImagesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSelectableImagesV1SelectableImagesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSelectableImagesV1SelectableImagesGetQueryKey(options),
  });
};

export const getSelectedImagesV1SelectedImagesGetQueryKey = (
  options?: Options<GetSelectedImagesV1SelectedImagesGetData>,
) => createQueryKey("getSelectedImagesV1SelectedImagesGet", options);

/**
 * Get Selected Images
 */
export const getSelectedImagesV1SelectedImagesGetOptions = (
  options?: Options<GetSelectedImagesV1SelectedImagesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSelectedImagesV1SelectedImagesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSelectedImagesV1SelectedImagesGetQueryKey(options),
  });
};

export const removeSelectionsV1SelectedImagesRemovePostQueryKey = (
  options: Options<RemoveSelectionsV1SelectedImagesRemovePostData>,
) => createQueryKey("removeSelectionsV1SelectedImagesRemovePost", options);

/**
 * Remove Selections
 */
export const removeSelectionsV1SelectedImagesRemovePostOptions = (
  options: Options<RemoveSelectionsV1SelectedImagesRemovePostData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await removeSelectionsV1SelectedImagesRemovePost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: removeSelectionsV1SelectedImagesRemovePostQueryKey(options),
  });
};

/**
 * Remove Selections
 */
export const removeSelectionsV1SelectedImagesRemovePostMutation = (
  options?: Partial<Options<RemoveSelectionsV1SelectedImagesRemovePostData>>,
): UseMutationOptions<
  RemoveSelectionsV1SelectedImagesRemovePostResponse,
  AxiosError<RemoveSelectionsV1SelectedImagesRemovePostError>,
  Options<RemoveSelectionsV1SelectedImagesRemovePostData>
> => {
  const mutationOptions: UseMutationOptions<
    RemoveSelectionsV1SelectedImagesRemovePostResponse,
    AxiosError<RemoveSelectionsV1SelectedImagesRemovePostError>,
    Options<RemoveSelectionsV1SelectedImagesRemovePostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await removeSelectionsV1SelectedImagesRemovePost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getImageSourcesV1ImageSourcesGetQueryKey = (options: Options<GetImageSourcesV1ImageSourcesGetData>) =>
  createQueryKey("getImageSourcesV1ImageSourcesGet", options);

/**
 * Get Image Sources
 */
export const getImageSourcesV1ImageSourcesGetOptions = (options: Options<GetImageSourcesV1ImageSourcesGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getImageSourcesV1ImageSourcesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getImageSourcesV1ImageSourcesGetQueryKey(options),
  });
};

export const getV1SettingsGetQueryKey = (options?: Options<GetV1SettingsGetData>) =>
  createQueryKey("getV1SettingsGet", options);

/**
 * Get
 * Return service settings.
 */
export const getV1SettingsGetOptions = (options?: Options<GetV1SettingsGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1SettingsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1SettingsGetQueryKey(options),
  });
};

/**
 * Patch
 */
export const patchV1SettingsPatchMutation = (
  options?: Partial<Options<PatchV1SettingsPatchData>>,
): UseMutationOptions<unknown, AxiosError<PatchV1SettingsPatchError>, Options<PatchV1SettingsPatchData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<PatchV1SettingsPatchError>,
    Options<PatchV1SettingsPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchV1SettingsPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPendingV1SitesPendingGetQueryKey = (options?: Options<GetPendingV1SitesPendingGetData>) =>
  createQueryKey("getPendingV1SitesPendingGet", options);

/**
 * Get Pending
 * Return pending sites.
 */
export const getPendingV1SitesPendingGetOptions = (options?: Options<GetPendingV1SitesPendingGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPendingV1SitesPendingGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPendingV1SitesPendingGetQueryKey(options),
  });
};

export const getPendingV1SitesPendingGetInfiniteQueryKey = (
  options?: Options<GetPendingV1SitesPendingGetData>,
): QueryKey<Options<GetPendingV1SitesPendingGetData>> => createQueryKey("getPendingV1SitesPendingGet", options, true);

/**
 * Get Pending
 * Return pending sites.
 */
export const getPendingV1SitesPendingGetInfiniteOptions = (options?: Options<GetPendingV1SitesPendingGetData>) => {
  return infiniteQueryOptions<
    GetPendingV1SitesPendingGetResponse,
    AxiosError<GetPendingV1SitesPendingGetError>,
    InfiniteData<GetPendingV1SitesPendingGetResponse>,
    QueryKey<Options<GetPendingV1SitesPendingGetData>>,
    number | Pick<QueryKey<Options<GetPendingV1SitesPendingGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetPendingV1SitesPendingGetData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPendingV1SitesPendingGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getPendingV1SitesPendingGetInfiniteQueryKey(options),
    },
  );
};

export const postPendingV1SitesPendingPostQueryKey = (options: Options<PostPendingV1SitesPendingPostData>) =>
  createQueryKey("postPendingV1SitesPendingPost", options);

/**
 * Post Pending
 * Accept or reject pending sites.
 */
export const postPendingV1SitesPendingPostOptions = (options: Options<PostPendingV1SitesPendingPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postPendingV1SitesPendingPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postPendingV1SitesPendingPostQueryKey(options),
  });
};

/**
 * Post Pending
 * Accept or reject pending sites.
 */
export const postPendingV1SitesPendingPostMutation = (
  options?: Partial<Options<PostPendingV1SitesPendingPostData>>,
): UseMutationOptions<
  PostPendingV1SitesPendingPostResponse,
  AxiosError<PostPendingV1SitesPendingPostError>,
  Options<PostPendingV1SitesPendingPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PostPendingV1SitesPendingPostResponse,
    AxiosError<PostPendingV1SitesPendingPostError>,
    Options<PostPendingV1SitesPendingPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postPendingV1SitesPendingPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Many
 * Delete multiple sites from the database.
 */
export const deleteManyV1SitesDeleteMutation = (
  options?: Partial<Options<DeleteManyV1SitesDeleteData>>,
): UseMutationOptions<
  DeleteManyV1SitesDeleteResponse,
  AxiosError<DeleteManyV1SitesDeleteError>,
  Options<DeleteManyV1SitesDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteManyV1SitesDeleteResponse,
    AxiosError<DeleteManyV1SitesDeleteError>,
    Options<DeleteManyV1SitesDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteManyV1SitesDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getV1SitesGetQueryKey = (options?: Options<GetV1SitesGetData>) => createQueryKey("getV1SitesGet", options);

/**
 * Get
 * Return accepted sites.
 */
export const getV1SitesGetOptions = (options?: Options<GetV1SitesGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1SitesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1SitesGetQueryKey(options),
  });
};

export const getV1SitesGetInfiniteQueryKey = (
  options?: Options<GetV1SitesGetData>,
): QueryKey<Options<GetV1SitesGetData>> => createQueryKey("getV1SitesGet", options, true);

/**
 * Get
 * Return accepted sites.
 */
export const getV1SitesGetInfiniteOptions = (options?: Options<GetV1SitesGetData>) => {
  return infiniteQueryOptions<
    GetV1SitesGetResponse,
    AxiosError<GetV1SitesGetError>,
    InfiniteData<GetV1SitesGetResponse>,
    QueryKey<Options<GetV1SitesGetData>>,
    number | Pick<QueryKey<Options<GetV1SitesGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetV1SitesGetData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getV1SitesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getV1SitesGetInfiniteQueryKey(options),
    },
  );
};

export const getCoordinatesV1SitesCoordinatesGetQueryKey = (
  options?: Options<GetCoordinatesV1SitesCoordinatesGetData>,
) => createQueryKey("getCoordinatesV1SitesCoordinatesGet", options);

/**
 * Get Coordinates
 * Return coordinates for all accepted sites.
 */
export const getCoordinatesV1SitesCoordinatesGetOptions = (
  options?: Options<GetCoordinatesV1SitesCoordinatesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCoordinatesV1SitesCoordinatesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCoordinatesV1SitesCoordinatesGetQueryKey(options),
  });
};

/**
 * Delete
 * Delete a site from the database.
 */
export const deleteV1SitesIdDeleteMutation = (
  options?: Partial<Options<DeleteV1SitesIdDeleteData>>,
): UseMutationOptions<
  DeleteV1SitesIdDeleteResponse,
  AxiosError<DeleteV1SitesIdDeleteError>,
  Options<DeleteV1SitesIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteV1SitesIdDeleteResponse,
    AxiosError<DeleteV1SitesIdDeleteError>,
    Options<DeleteV1SitesIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteV1SitesIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getIdV1SitesIdGetQueryKey = (options: Options<GetIdV1SitesIdGetData>) =>
  createQueryKey("getIdV1SitesIdGet", options);

/**
 * Get Id
 * Return a specific site.
 */
export const getIdV1SitesIdGetOptions = (options: Options<GetIdV1SitesIdGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getIdV1SitesIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getIdV1SitesIdGetQueryKey(options),
  });
};

/**
 * Patch
 * Modify a site.
 */
export const patchV1SitesIdPatchMutation = (
  options?: Partial<Options<PatchV1SitesIdPatchData>>,
): UseMutationOptions<
  PatchV1SitesIdPatchResponse,
  AxiosError<PatchV1SitesIdPatchError>,
  Options<PatchV1SitesIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchV1SitesIdPatchResponse,
    AxiosError<PatchV1SitesIdPatchError>,
    Options<PatchV1SitesIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchV1SitesIdPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Many
 * Delete several tokens from the database
 */
export const deleteManyV1TokensDeleteMutation = (
  options?: Partial<Options<DeleteManyV1TokensDeleteData>>,
): UseMutationOptions<
  DeleteManyV1TokensDeleteResponse,
  AxiosError<DeleteManyV1TokensDeleteError>,
  Options<DeleteManyV1TokensDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteManyV1TokensDeleteResponse,
    AxiosError<DeleteManyV1TokensDeleteError>,
    Options<DeleteManyV1TokensDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteManyV1TokensDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getV1TokensGetQueryKey = (options?: Options<GetV1TokensGetData>) =>
  createQueryKey("getV1TokensGet", options);

/**
 * Get
 * Return all tokens.
 */
export const getV1TokensGetOptions = (options?: Options<GetV1TokensGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1TokensGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1TokensGetQueryKey(options),
  });
};

export const getV1TokensGetInfiniteQueryKey = (
  options?: Options<GetV1TokensGetData>,
): QueryKey<Options<GetV1TokensGetData>> => createQueryKey("getV1TokensGet", options, true);

/**
 * Get
 * Return all tokens.
 */
export const getV1TokensGetInfiniteOptions = (options?: Options<GetV1TokensGetData>) => {
  return infiniteQueryOptions<
    GetV1TokensGetResponse,
    AxiosError<GetV1TokensGetError>,
    InfiniteData<GetV1TokensGetResponse>,
    QueryKey<Options<GetV1TokensGetData>>,
    number | Pick<QueryKey<Options<GetV1TokensGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetV1TokensGetData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getV1TokensGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getV1TokensGetInfiniteQueryKey(options),
    },
  );
};

export const postV1TokensPostQueryKey = (options: Options<PostV1TokensPostData>) =>
  createQueryKey("postV1TokensPost", options);

/**
 * Post
 * Create enrollment tokens for sites.
 *
 * Token duration (TTL) is expressed as an ISO-8601 duration string.
 */
export const postV1TokensPostOptions = (options: Options<PostV1TokensPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postV1TokensPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postV1TokensPostQueryKey(options),
  });
};

/**
 * Post
 * Create enrollment tokens for sites.
 *
 * Token duration (TTL) is expressed as an ISO-8601 duration string.
 */
export const postV1TokensPostMutation = (
  options?: Partial<Options<PostV1TokensPostData>>,
): UseMutationOptions<PostV1TokensPostResponse, AxiosError<PostV1TokensPostError>, Options<PostV1TokensPostData>> => {
  const mutationOptions: UseMutationOptions<
    PostV1TokensPostResponse,
    AxiosError<PostV1TokensPostError>,
    Options<PostV1TokensPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postV1TokensPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExportV1TokensExportGetQueryKey = (options?: Options<GetExportV1TokensExportGetData>) =>
  createQueryKey("getExportV1TokensExportGet", options);

/**
 * Get Export
 * Return the list of active tokens in CSV format.
 */
export const getExportV1TokensExportGetOptions = (options?: Options<GetExportV1TokensExportGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExportV1TokensExportGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExportV1TokensExportGetQueryKey(options),
  });
};

export const getExportV1TokensExportGetInfiniteQueryKey = (
  options?: Options<GetExportV1TokensExportGetData>,
): QueryKey<Options<GetExportV1TokensExportGetData>> => createQueryKey("getExportV1TokensExportGet", options, true);

/**
 * Get Export
 * Return the list of active tokens in CSV format.
 */
export const getExportV1TokensExportGetInfiniteOptions = (options?: Options<GetExportV1TokensExportGetData>) => {
  return infiniteQueryOptions<
    unknown,
    AxiosError<GetExportV1TokensExportGetError>,
    InfiniteData<unknown>,
    QueryKey<Options<GetExportV1TokensExportGetData>>,
    number | Pick<QueryKey<Options<GetExportV1TokensExportGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetExportV1TokensExportGetData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getExportV1TokensExportGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getExportV1TokensExportGetInfiniteQueryKey(options),
    },
  );
};

/**
 * Delete
 * Delete a token from the database.
 */
export const deleteV1TokensIdDeleteMutation = (
  options?: Partial<Options<DeleteV1TokensIdDeleteData>>,
): UseMutationOptions<
  DeleteV1TokensIdDeleteResponse,
  AxiosError<DeleteV1TokensIdDeleteError>,
  Options<DeleteV1TokensIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteV1TokensIdDeleteResponse,
    AxiosError<DeleteV1TokensIdDeleteError>,
    Options<DeleteV1TokensIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteV1TokensIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getV1UsersGetQueryKey = (options?: Options<GetV1UsersGetData>) => createQueryKey("getV1UsersGet", options);

/**
 * Get
 * Return all users
 */
export const getV1UsersGetOptions = (options?: Options<GetV1UsersGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1UsersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1UsersGetQueryKey(options),
  });
};

export const getV1UsersGetInfiniteQueryKey = (
  options?: Options<GetV1UsersGetData>,
): QueryKey<Options<GetV1UsersGetData>> => createQueryKey("getV1UsersGet", options, true);

/**
 * Get
 * Return all users
 */
export const getV1UsersGetInfiniteOptions = (options?: Options<GetV1UsersGetData>) => {
  return infiniteQueryOptions<
    GetV1UsersGetResponse,
    AxiosError<GetV1UsersGetError>,
    InfiniteData<GetV1UsersGetResponse>,
    QueryKey<Options<GetV1UsersGetData>>,
    number | Pick<QueryKey<Options<GetV1UsersGetData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetV1UsersGetData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getV1UsersGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getV1UsersGetInfiniteQueryKey(options),
    },
  );
};

export const postV1UsersPostQueryKey = (options: Options<PostV1UsersPostData>) =>
  createQueryKey("postV1UsersPost", options);

/**
 * Post
 * Create a user.
 */
export const postV1UsersPostOptions = (options: Options<PostV1UsersPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postV1UsersPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postV1UsersPostQueryKey(options),
  });
};

/**
 * Post
 * Create a user.
 */
export const postV1UsersPostMutation = (
  options?: Partial<Options<PostV1UsersPostData>>,
): UseMutationOptions<PostV1UsersPostResponse, AxiosError<PostV1UsersPostError>, Options<PostV1UsersPostData>> => {
  const mutationOptions: UseMutationOptions<
    PostV1UsersPostResponse,
    AxiosError<PostV1UsersPostError>,
    Options<PostV1UsersPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postV1UsersPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMeV1UsersMeGetQueryKey = (options?: Options<GetMeV1UsersMeGetData>) =>
  createQueryKey("getMeV1UsersMeGet", options);

/**
 * Get Me
 * Render info about the authenticated user.
 */
export const getMeV1UsersMeGetOptions = (options?: Options<GetMeV1UsersMeGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMeV1UsersMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMeV1UsersMeGetQueryKey(options),
  });
};

/**
 * Patch Me
 * Update the details for a user
 */
export const patchMeV1UsersMePatchMutation = (
  options?: Partial<Options<PatchMeV1UsersMePatchData>>,
): UseMutationOptions<
  PatchMeV1UsersMePatchResponse,
  AxiosError<PatchMeV1UsersMePatchError>,
  Options<PatchMeV1UsersMePatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchMeV1UsersMePatchResponse,
    AxiosError<PatchMeV1UsersMePatchError>,
    Options<PatchMeV1UsersMePatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchMeV1UsersMePatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Patch Me Password
 * Modify the users password.
 */
export const patchMePasswordV1UsersMePasswordPatchMutation = (
  options?: Partial<Options<PatchMePasswordV1UsersMePasswordPatchData>>,
): UseMutationOptions<
  unknown,
  AxiosError<PatchMePasswordV1UsersMePasswordPatchError>,
  Options<PatchMePasswordV1UsersMePasswordPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<PatchMePasswordV1UsersMePasswordPatchError>,
    Options<PatchMePasswordV1UsersMePasswordPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchMePasswordV1UsersMePasswordPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete
 * Delete a user from the database.
 */
export const deleteV1UsersIdDeleteMutation = (
  options?: Partial<Options<DeleteV1UsersIdDeleteData>>,
): UseMutationOptions<
  DeleteV1UsersIdDeleteResponse,
  AxiosError<DeleteV1UsersIdDeleteError>,
  Options<DeleteV1UsersIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteV1UsersIdDeleteResponse,
    AxiosError<DeleteV1UsersIdDeleteError>,
    Options<DeleteV1UsersIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteV1UsersIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getIdV1UsersIdGetQueryKey = (options: Options<GetIdV1UsersIdGetData>) =>
  createQueryKey("getIdV1UsersIdGet", options);

/**
 * Get Id
 * Select a specific user
 */
export const getIdV1UsersIdGetOptions = (options: Options<GetIdV1UsersIdGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getIdV1UsersIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getIdV1UsersIdGetQueryKey(options),
  });
};

/**
 * Patch
 * Admin action to update the details for a user.
 */
export const patchV1UsersIdPatchMutation = (
  options?: Partial<Options<PatchV1UsersIdPatchData>>,
): UseMutationOptions<
  PatchV1UsersIdPatchResponse,
  AxiosError<PatchV1UsersIdPatchError>,
  Options<PatchV1UsersIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchV1UsersIdPatchResponse,
    AxiosError<PatchV1UsersIdPatchError>,
    Options<PatchV1UsersIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchV1UsersIdPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
