"""unique_cluster_id

Revision ID: 0003
Revises: 0002
Create Date: 2024-06-12 15:11:08.415307+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_site_cluster_uuid"), "site", ["cluster_uuid"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_site_cluster_uuid"), "site", type_="unique")
    # ### end Alembic commands ###
