name: maas-site-manager
summary: MAAS site manager
description: |
  MAAS site manager
website: https://maas.io
contact: maas-devel@lists.ubuntu.com
license: Proprietary
adopt-info: snap-metadata

grade: stable
confinement: strict
base: core24

environment:
  LD_PRELOAD: $SNAP/usr/lib/snap-preload.so
  MSM_API_SOCKET: $SNAP_DATA/api.sock

hooks:
  configure:
    plugs:
      - network

apps:
  maas-site-manager:
    command: bin/msm-admin
    plugs:
      - network

  api:
    daemon: simple
    command: bin/msm-api
    install-mode: disable
    plugs:
      - network
      - network-bind

  nginx:
    daemon: simple
    command: usr/sbin/nginx -c $SNAP_DATA/nginx.conf
    install-mode: disable
    plugs:
      - network
      - network-bind

parts:
  backend:
    plugin: python
    source: backend
    python-packages:
      - .
    override-build: |
      craftctl default
      snap-helpers write-hooks
    prime:
      - -bin/activate*
      - -bin/Activate*
      - -include

  frontend:
    plugin: nil
    source: .
    build-snaps:
      - node/20/stable
    override-build: |
      cd frontend
      npm install -g yarn
      yarn install
      yarn run build
      cp -a dist $SNAPCRAFT_PART_INSTALL/static

  nginx:
    plugin: nil
    stage-packages:
      - nginx-core
    prime:
      - etc/nginx
      - -etc/nginx/modules-*
      - -etc/nginx/nginx.conf
      - -etc/nginx/sites-*
      - usr/sbin/nginx

  snap-preload:
    plugin: make
    source: https://github.com/maas/snap-preload
    source-type: git

  snap-metadata:
    plugin: nil
    source: .
    after:
      - backend
    override-build: |
      craftctl set version="$(snap/local/package-version)"
