// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  urlSearchParamsBodySerializer,
} from "@hey-api/client-axios";

import { client as _heyApiClient } from "./client.gen";
import type {
  GetBootAssetsV1BootassetsGetData,
  GetBootAssetsV1BootassetsGetResponse,
  GetBootAssetsV1BootassetsGetError,
  PostBootAssetsV1BootassetsPostData,
  PostBootAssetsV1BootassetsPostResponse,
  PostBootAssetsV1BootassetsPostError,
  GetBootSourcesV1BootassetSourcesGetData,
  GetBootSourcesV1BootassetSourcesGetResponse,
  GetBootSourcesV1BootassetSourcesGetError,
  PostBootSourcesV1BootassetSourcesPostData,
  PostBootSourcesV1BootassetSourcesPostResponse,
  PostBootSourcesV1BootassetSourcesPostError,
  DeleteBootSourceV1BootassetSourcesIdDeleteData,
  DeleteBootSourceV1BootassetSourcesIdDeleteError,
  GetBootSourceByIdV1BootassetSourcesIdGetData,
  GetBootSourceByIdV1BootassetSourcesIdGetResponse,
  GetBootSourceByIdV1BootassetSourcesIdGetError,
  PatchBootSourceV1BootassetSourcesIdPatchData,
  PatchBootSourceV1BootassetSourcesIdPatchResponse,
  PatchBootSourceV1BootassetSourcesIdPatchError,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponse,
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetError,
  PostBootAssetVersionV1BootassetsIdVersionsPostData,
  PostBootAssetVersionV1BootassetsIdVersionsPostResponse,
  PostBootAssetVersionV1BootassetsIdVersionsPostError,
  GetBootAssetVersionsV1BootassetVersionsGetData,
  GetBootAssetVersionsV1BootassetVersionsGetResponse,
  GetBootAssetVersionsV1BootassetVersionsGetError,
  PostBootAssetItemV1BootassetVersionsIdItemsPostData,
  PostBootAssetItemV1BootassetVersionsIdItemsPostResponse,
  PostBootAssetItemV1BootassetVersionsIdItemsPostError,
  GetBootAssetItemsV1BootassetItemsGetData,
  GetBootAssetItemsV1BootassetItemsGetResponse,
  GetBootAssetItemsV1BootassetItemsGetError,
  DeleteImagesV1BootassetItemsIdDeleteData,
  DeleteImagesV1BootassetItemsIdDeleteError,
  PatchBootAssetItemsV1BootassetItemsIdPatchData,
  PatchBootAssetItemsV1BootassetItemsIdPatchResponse,
  PatchBootAssetItemsV1BootassetItemsIdPatchError,
  PostImagesV1ImagesPostData,
  PostImagesV1ImagesPostResponse,
  PostImagesV1ImagesPostError,
  PostV1LoginPostData,
  PostV1LoginPostResponse,
  PostV1LoginPostError,
  GetV1SettingsGetData,
  GetV1SettingsGetResponse,
  GetV1SettingsGetError,
  PatchV1SettingsPatchData,
  PatchV1SettingsPatchError,
  GetPendingV1SitesPendingGetData,
  GetPendingV1SitesPendingGetResponse,
  GetPendingV1SitesPendingGetError,
  PostPendingV1SitesPendingPostData,
  PostPendingV1SitesPendingPostResponse,
  PostPendingV1SitesPendingPostError,
  DeleteManyV1SitesDeleteData,
  DeleteManyV1SitesDeleteResponse,
  DeleteManyV1SitesDeleteError,
  GetV1SitesGetData,
  GetV1SitesGetResponse,
  GetV1SitesGetError,
  GetCoordinatesV1SitesCoordinatesGetData,
  GetCoordinatesV1SitesCoordinatesGetResponse,
  GetCoordinatesV1SitesCoordinatesGetError,
  DeleteV1SitesIdDeleteData,
  DeleteV1SitesIdDeleteResponse,
  DeleteV1SitesIdDeleteError,
  GetIdV1SitesIdGetData,
  GetIdV1SitesIdGetResponse,
  GetIdV1SitesIdGetError,
  PatchV1SitesIdPatchData,
  PatchV1SitesIdPatchResponse,
  PatchV1SitesIdPatchError,
  DeleteManyV1TokensDeleteData,
  DeleteManyV1TokensDeleteResponse,
  DeleteManyV1TokensDeleteError,
  GetV1TokensGetData,
  GetV1TokensGetResponse,
  GetV1TokensGetError,
  PostV1TokensPostData,
  PostV1TokensPostResponse,
  PostV1TokensPostError,
  GetExportV1TokensExportGetData,
  GetExportV1TokensExportGetError,
  DeleteV1TokensIdDeleteData,
  DeleteV1TokensIdDeleteResponse,
  DeleteV1TokensIdDeleteError,
  GetV1UsersGetData,
  GetV1UsersGetResponse,
  GetV1UsersGetError,
  PostV1UsersPostData,
  PostV1UsersPostResponse,
  PostV1UsersPostError,
  GetMeV1UsersMeGetData,
  GetMeV1UsersMeGetResponse,
  GetMeV1UsersMeGetError,
  PatchMeV1UsersMePatchData,
  PatchMeV1UsersMePatchResponse,
  PatchMeV1UsersMePatchError,
  PatchMePasswordV1UsersMePasswordPatchData,
  PatchMePasswordV1UsersMePasswordPatchError,
  DeleteV1UsersIdDeleteData,
  DeleteV1UsersIdDeleteResponse,
  DeleteV1UsersIdDeleteError,
  GetIdV1UsersIdGetData,
  GetIdV1UsersIdGetResponse,
  GetIdV1UsersIdGetError,
  PatchV1UsersIdPatchData,
  PatchV1UsersIdPatchResponse,
  PatchV1UsersIdPatchError,
} from "./types.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Boot Assets
 * Return boot assets.
 */
export const getBootAssetsV1BootassetsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetBootAssetsV1BootassetsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetBootAssetsV1BootassetsGetResponse,
    GetBootAssetsV1BootassetsGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootassets",
    ...options,
  });
};

/**
 * Post Boot Assets
 */
export const postBootAssetsV1BootassetsPost = <ThrowOnError extends boolean = false>(
  options: Options<PostBootAssetsV1BootassetsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostBootAssetsV1BootassetsPostResponse,
    PostBootAssetsV1BootassetsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootassets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Get Boot Sources
 * Return boot sources.
 */
export const getBootSourcesV1BootassetSourcesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetBootSourcesV1BootassetSourcesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetBootSourcesV1BootassetSourcesGetResponse,
    GetBootSourcesV1BootassetSourcesGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources",
    ...options,
  });
};

/**
 * Post Boot Sources
 */
export const postBootSourcesV1BootassetSourcesPost = <ThrowOnError extends boolean = false>(
  options: Options<PostBootSourcesV1BootassetSourcesPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostBootSourcesV1BootassetSourcesPostResponse,
    PostBootSourcesV1BootassetSourcesPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Boot Source
 */
export const deleteBootSourceV1BootassetSourcesIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBootSourceV1BootassetSourcesIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    unknown,
    DeleteBootSourceV1BootassetSourcesIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources/{id}",
    ...options,
  });
};

/**
 * Get Boot Source By Id
 */
export const getBootSourceByIdV1BootassetSourcesIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetBootSourceByIdV1BootassetSourcesIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBootSourceByIdV1BootassetSourcesIdGetResponse,
    GetBootSourceByIdV1BootassetSourcesIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources/{id}",
    ...options,
  });
};

/**
 * Patch Boot Source
 */
export const patchBootSourceV1BootassetSourcesIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchBootSourceV1BootassetSourcesIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchBootSourceV1BootassetSourcesIdPatchResponse,
    PatchBootSourceV1BootassetSourcesIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Get Boot Source Selections
 * Return boot source selections.
 */
export const getBootSourceSelectionsV1BootassetSourcesIdSelectionsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponse,
    GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-sources/{id}/selections",
    ...options,
  });
};

/**
 * Post Boot Asset Version
 */
export const postBootAssetVersionV1BootassetsIdVersionsPost = <ThrowOnError extends boolean = false>(
  options: Options<PostBootAssetVersionV1BootassetsIdVersionsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostBootAssetVersionV1BootassetsIdVersionsPostResponse,
    PostBootAssetVersionV1BootassetsIdVersionsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootassets/{id}/versions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Get Boot Asset Versions
 * Return Boot Asset Versions
 */
export const getBootAssetVersionsV1BootassetVersionsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetBootAssetVersionsV1BootassetVersionsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetBootAssetVersionsV1BootassetVersionsGetResponse,
    GetBootAssetVersionsV1BootassetVersionsGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-versions",
    ...options,
  });
};

/**
 * Post Boot Asset Item
 */
export const postBootAssetItemV1BootassetVersionsIdItemsPost = <ThrowOnError extends boolean = false>(
  options: Options<PostBootAssetItemV1BootassetVersionsIdItemsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostBootAssetItemV1BootassetVersionsIdItemsPostResponse,
    PostBootAssetItemV1BootassetVersionsIdItemsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-versions/{id}/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Get Boot Asset Items
 */
export const getBootAssetItemsV1BootassetItemsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetBootAssetItemsV1BootassetItemsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetBootAssetItemsV1BootassetItemsGetResponse,
    GetBootAssetItemsV1BootassetItemsGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-items",
    ...options,
  });
};

/**
 * Delete Images
 */
export const deleteImagesV1BootassetItemsIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteImagesV1BootassetItemsIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<unknown, DeleteImagesV1BootassetItemsIdDeleteError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-items/{id}",
    ...options,
  });
};

/**
 * Patch Boot Asset Items
 */
export const patchBootAssetItemsV1BootassetItemsIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchBootAssetItemsV1BootassetItemsIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchBootAssetItemsV1BootassetItemsIdPatchResponse,
    PatchBootAssetItemsV1BootassetItemsIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/bootasset-items/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Post Images
 */
export const postImagesV1ImagesPost = <ThrowOnError extends boolean = false>(
  options?: Options<PostImagesV1ImagesPostData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostImagesV1ImagesPostResponse,
    PostImagesV1ImagesPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/images",
    ...options,
  });
};

/**
 * Post
 */
export const postV1LoginPost = <ThrowOnError extends boolean = false>(
  options: Options<PostV1LoginPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<PostV1LoginPostResponse, PostV1LoginPostError, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: "/v1/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
  });
};

/**
 * Get
 * Return service settings.
 */
export const getV1SettingsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1SettingsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetV1SettingsGetResponse, GetV1SettingsGetError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/settings",
    ...options,
  });
};

/**
 * Patch
 */
export const patchV1SettingsPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchV1SettingsPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<unknown, PatchV1SettingsPatchError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/settings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Get Pending
 * Return pending sites.
 */
export const getPendingV1SitesPendingGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetPendingV1SitesPendingGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetPendingV1SitesPendingGetResponse,
    GetPendingV1SitesPendingGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/pending",
    ...options,
  });
};

/**
 * Post Pending
 * Accept or reject pending sites.
 */
export const postPendingV1SitesPendingPost = <ThrowOnError extends boolean = false>(
  options: Options<PostPendingV1SitesPendingPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostPendingV1SitesPendingPostResponse,
    PostPendingV1SitesPendingPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/pending",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Many
 * Delete multiple sites from the database.
 */
export const deleteManyV1SitesDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteManyV1SitesDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteManyV1SitesDeleteResponse,
    DeleteManyV1SitesDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites",
    ...options,
  });
};

/**
 * Get
 * Return accepted sites.
 */
export const getV1SitesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1SitesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetV1SitesGetResponse, GetV1SitesGetError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites",
    ...options,
  });
};

/**
 * Get Coordinates
 * Return coordinates for all accepted sites.
 */
export const getCoordinatesV1SitesCoordinatesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetCoordinatesV1SitesCoordinatesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCoordinatesV1SitesCoordinatesGetResponse,
    GetCoordinatesV1SitesCoordinatesGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/coordinates",
    ...options,
  });
};

/**
 * Delete
 * Delete a site from the database.
 */
export const deleteV1SitesIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1SitesIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteV1SitesIdDeleteResponse,
    DeleteV1SitesIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/{id}",
    ...options,
  });
};

/**
 * Get Id
 * Return a specific site.
 */
export const getIdV1SitesIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetIdV1SitesIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetIdV1SitesIdGetResponse, GetIdV1SitesIdGetError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/{id}",
    ...options,
  });
};

/**
 * Patch
 * Modify a site.
 */
export const patchV1SitesIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchV1SitesIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<PatchV1SitesIdPatchResponse, PatchV1SitesIdPatchError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/sites/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Many
 * Delete several tokens from the database
 */
export const deleteManyV1TokensDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteManyV1TokensDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteManyV1TokensDeleteResponse,
    DeleteManyV1TokensDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/tokens",
    ...options,
  });
};

/**
 * Get
 * Return all tokens.
 */
export const getV1TokensGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1TokensGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetV1TokensGetResponse, GetV1TokensGetError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/tokens",
    ...options,
  });
};

/**
 * Post
 * Create enrollment tokens for sites.
 *
 * Token duration (TTL) is expressed as an ISO-8601 duration string.
 */
export const postV1TokensPost = <ThrowOnError extends boolean = false>(
  options: Options<PostV1TokensPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<PostV1TokensPostResponse, PostV1TokensPostError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/tokens",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Get Export
 * Return the list of active tokens in CSV format.
 */
export const getExportV1TokensExportGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetExportV1TokensExportGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<unknown, GetExportV1TokensExportGetError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/tokens/export",
    ...options,
  });
};

/**
 * Delete
 * Delete a token from the database.
 */
export const deleteV1TokensIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1TokensIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteV1TokensIdDeleteResponse,
    DeleteV1TokensIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/tokens/{id}",
    ...options,
  });
};

/**
 * Get
 * Return all users
 */
export const getV1UsersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1UsersGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetV1UsersGetResponse, GetV1UsersGetError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users",
    ...options,
  });
};

/**
 * Post
 * Create a user.
 */
export const postV1UsersPost = <ThrowOnError extends boolean = false>(
  options: Options<PostV1UsersPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<PostV1UsersPostResponse, PostV1UsersPostError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Get Me
 * Render info about the authenticated user.
 */
export const getMeV1UsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMeV1UsersMeGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetMeV1UsersMeGetResponse, GetMeV1UsersMeGetError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/me",
    ...options,
  });
};

/**
 * Patch Me
 * Update the details for a user
 */
export const patchMeV1UsersMePatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchMeV1UsersMePatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchMeV1UsersMePatchResponse,
    PatchMeV1UsersMePatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Patch Me Password
 * Modify the users password.
 */
export const patchMePasswordV1UsersMePasswordPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchMePasswordV1UsersMePasswordPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<unknown, PatchMePasswordV1UsersMePasswordPatchError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/me/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete
 * Delete a user from the database.
 */
export const deleteV1UsersIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1UsersIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteV1UsersIdDeleteResponse,
    DeleteV1UsersIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/{id}",
    ...options,
  });
};

/**
 * Get Id
 * Select a specific user
 */
export const getIdV1UsersIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetIdV1UsersIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetIdV1UsersIdGetResponse, GetIdV1UsersIdGetError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/{id}",
    ...options,
  });
};

/**
 * Patch
 * Admin action to update the details for a user.
 */
export const patchV1UsersIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<PatchV1UsersIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<PatchV1UsersIdPatchResponse, PatchV1UsersIdPatchError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};
