// This file is auto-generated by @hey-api/openapi-ts

/**
 * Content for a response returning a JWT.
 */
export type AccessTokenResponse = {
  token_type: string;
  access_token: string;
  rotation_interval_minutes: number;
};

export type BadRequestErrorBodyResponse = {
  code?: ExceptionCode;
  message?: string;
  details?: Array<BaseExceptionDetail> | null;
};

export type BadRequestErrorResponseModel = {
  error: BadRequestErrorBodyResponse;
};

/**
 * Additional details for an exception.
 */
export type BaseExceptionDetail = {
  reason: string;
  messages: Array<string>;
  field?: string | null;
  location?: string | null;
};

export type BodyPostV1LoginPost = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type BootAsset = {
  id: number;
  boot_source_id: number;
  kind: BootAssetKind;
  label: BootAssetLabel;
  os: string;
  release: string;
  codename: string;
  title: string;
  arch: string;
  subarch: string;
  compatibility: Array<string>;
  flavor: string;
  base_image: string;
  eol: string;
  esm_eol: string;
};

export type BootAssetItem = {
  id: number;
  boot_asset_version_id: number;
  ftype: string;
  sha256: string;
  path: string;
  file_size: number;
  source_package?: string | null;
  source_version?: string | null;
  source_release?: string | null;
  bytes_synced: number;
};

export type BootAssetItemPatchRequest = {
  ftype?: string | null;
  source_package?: string | null;
  source_version?: string | null;
  source_release?: string | null;
  bytes_synced?: number | null;
};

export type BootAssetItemPostRequest = {
  ftype: string;
  sha256: string;
  path: string;
  file_size: number;
  source_package?: string | null;
  source_version?: string | null;
  source_release?: string | null;
};

export type BootAssetItemPostResponse = {
  id: number;
};

export type BootAssetItemsGetResponse = {
  total: number;
  page: number;
  size: number;
  items: Array<BootAssetItem>;
};

export enum BootAssetKind {
  _0 = 0,
  _1 = 1,
}

export enum BootAssetLabel {
  STABLE = "stable",
  CANDIDATE = "candidate",
}

export type BootAssetVersion = {
  id: number;
  boot_asset_id: number;
  version: string;
};

export type BootAssetVersionPostRequest = {
  version: string;
};

export type BootAssetVersionPostResponse = {
  id: number;
};

export type BootAssetVersionsGetResponse = {
  total: number;
  page: number;
  size: number;
  items: Array<BootAssetVersion>;
};

export type BootAssetsGetResponse = {
  total: number;
  page: number;
  size: number;
  items: Array<BootAsset>;
};

export type BootAssetsPostRequest = {
  boot_source_id: number;
  kind: BootAssetKind;
  label: BootAssetLabel;
  os: string;
  release: string;
  codename: string;
  title: string;
  arch: string;
  subarch: string;
  compatibility: Array<string>;
  flavor: string;
  base_image: string;
  eol: string;
  esm_eol: string;
};

export type BootAssetsPostResponse = {
  id: number;
};

export type BootSource = {
  id: number;
  priority: number;
  url: string;
  keyring?: string | null;
  sync_interval: number;
};

export type BootSourceSelection = {
  id: number;
  boot_source_id: number;
  label: BootAssetLabel;
  os: string;
  release: string;
  arches: Array<string>;
};

export type BootSourceSelectionsGetResponse = {
  total: number;
  page: number;
  size: number;
  items: Array<BootSourceSelection>;
};

export type BootSourcesGetResponse = {
  total: number;
  page: number;
  size: number;
  items: Array<BootSource>;
};

export type BootSourcesPostRequest = {
  priority: number;
  url: string;
  keyring: string;
  sync_interval: number;
};

export type BootSourcesPostResponse = {
  id: number;
};

export enum ConnectionStatus {
  STABLE = "stable",
  LOST = "lost",
  UNKNOWN = "unknown",
}

export type Coordinates = {
  latitude?: number;
  longitude?: number;
};

export enum ExceptionCode {
  ALREADY_EXISTS = "AlreadyExists",
  INVALID_CREDENTIALS = "InvalidCredentials",
  INVALID_PARAMETERS = "InvalidParameters",
  INVALID_PENDING_SITES = "InvalidPendingSites",
  INVALID_TOKEN = "InvalidToken",
  MISSING_RESOURCE = "MissingResource",
  MISSING_PERMISSIONS = "MissingPermissions",
  NOT_AUTHENTICATED = "NotAuthenticated",
  FILE_TOO_LARGE = "FileTooLarge",
}

export type ForbiddenErrorBodyResponse = {
  code?: ExceptionCode;
  message?: string;
  details?: Array<BaseExceptionDetail> | null;
};

export type ForbiddenErrorResponseModel = {
  error: ForbiddenErrorBodyResponse;
};

export type NotFoundErrorBodyResponse = {
  code?: ExceptionCode;
  message?: string;
  details?: Array<BaseExceptionDetail> | null;
};

export type NotFoundErrorResponseModel = {
  error: NotFoundErrorBodyResponse;
};

/**
 * A pending MAAS site.
 */
export type PendingSite = {
  id: number;
  name: string;
  url: string;
  cluster_uuid: string;
  created: string;
};

export type PendingSitesGetResponse = {
  total: number;
  page: number;
  size: number;
  items: Array<PendingSite>;
};

/**
 * Request to accept/reject sites.
 */
export type PendingSitesPostRequest = {
  ids: Array<number>;
  accept: boolean;
};

/**
 * Application settings that can be changed via the API.
 */
export type Settings = {
  max_image_upload_size_gb?: number;
  service_url?: string;
  token_lifetime_minutes?: number;
  token_rotation_interval_minutes?: number;
};

/**
 * Change application settings.
 */
export type SettingsUpdate = {
  max_image_upload_size_gb?: number | null;
  service_url?: string | null;
  token_lifetime_minutes?: number | null;
  token_rotation_interval_minutes?: number | null;
};

/**
 * A MAAS installation.
 */
export type Site = {
  id: number;
  name: string;
  city?: string;
  country?: string;
  coordinates: Coordinates | null;
  note?: string;
  state?: string;
  address?: string;
  postal_code?: string;
  timezone?: TimeZone | "";
  url?: string;
  cluster_uuid: string;
  name_unique: boolean;
  connection_status: ConnectionStatus;
  stats?: SiteData | null;
};

/**
 * Coordinates for a MAAS site.
 */
export type SiteCoordinates = {
  id: number;
  coordinates?: Coordinates | null;
};

/**
 * Data for a site.
 */
export type SiteData = {
  machines_total: number;
  machines_allocated: number;
  machines_deployed: number;
  machines_ready: number;
  machines_error: number;
  machines_other: number;
  last_seen: string;
};

/**
 * Update a site.
 */
export type SiteUpdateRequest = {
  city?: string | null;
  country?: string | null;
  coordinates?: Coordinates | null;
  note?: string | null;
  state?: string | null;
  address?: string | null;
  postal_code?: string | null;
  timezone?: TimeZone | null;
};

/**
 * Response with paginated accepted sites.
 */
export type SitesGetResponse = {
  total: number;
  page: number;
  size: number;
  items: Array<Site>;
};

export enum TimeZone {
  AFRICA_ABIDJAN = "Africa/Abidjan",
  AFRICA_ACCRA = "Africa/Accra",
  AFRICA_ADDIS_ABABA = "Africa/Addis_Ababa",
  AFRICA_ALGIERS = "Africa/Algiers",
  AFRICA_ASMARA = "Africa/Asmara",
  AFRICA_ASMERA = "Africa/Asmera",
  AFRICA_BAMAKO = "Africa/Bamako",
  AFRICA_BANGUI = "Africa/Bangui",
  AFRICA_BANJUL = "Africa/Banjul",
  AFRICA_BISSAU = "Africa/Bissau",
  AFRICA_BLANTYRE = "Africa/Blantyre",
  AFRICA_BRAZZAVILLE = "Africa/Brazzaville",
  AFRICA_BUJUMBURA = "Africa/Bujumbura",
  AFRICA_CAIRO = "Africa/Cairo",
  AFRICA_CASABLANCA = "Africa/Casablanca",
  AFRICA_CEUTA = "Africa/Ceuta",
  AFRICA_CONAKRY = "Africa/Conakry",
  AFRICA_DAKAR = "Africa/Dakar",
  AFRICA_DAR_ES_SALAAM = "Africa/Dar_es_Salaam",
  AFRICA_DJIBOUTI = "Africa/Djibouti",
  AFRICA_DOUALA = "Africa/Douala",
  AFRICA_EL_AAIUN = "Africa/El_Aaiun",
  AFRICA_FREETOWN = "Africa/Freetown",
  AFRICA_GABORONE = "Africa/Gaborone",
  AFRICA_HARARE = "Africa/Harare",
  AFRICA_JOHANNESBURG = "Africa/Johannesburg",
  AFRICA_JUBA = "Africa/Juba",
  AFRICA_KAMPALA = "Africa/Kampala",
  AFRICA_KHARTOUM = "Africa/Khartoum",
  AFRICA_KIGALI = "Africa/Kigali",
  AFRICA_KINSHASA = "Africa/Kinshasa",
  AFRICA_LAGOS = "Africa/Lagos",
  AFRICA_LIBREVILLE = "Africa/Libreville",
  AFRICA_LOME = "Africa/Lome",
  AFRICA_LUANDA = "Africa/Luanda",
  AFRICA_LUBUMBASHI = "Africa/Lubumbashi",
  AFRICA_LUSAKA = "Africa/Lusaka",
  AFRICA_MALABO = "Africa/Malabo",
  AFRICA_MAPUTO = "Africa/Maputo",
  AFRICA_MASERU = "Africa/Maseru",
  AFRICA_MBABANE = "Africa/Mbabane",
  AFRICA_MOGADISHU = "Africa/Mogadishu",
  AFRICA_MONROVIA = "Africa/Monrovia",
  AFRICA_NAIROBI = "Africa/Nairobi",
  AFRICA_NDJAMENA = "Africa/Ndjamena",
  AFRICA_NIAMEY = "Africa/Niamey",
  AFRICA_NOUAKCHOTT = "Africa/Nouakchott",
  AFRICA_OUAGADOUGOU = "Africa/Ouagadougou",
  AFRICA_PORTO_NOVO = "Africa/Porto-Novo",
  AFRICA_SAO_TOME = "Africa/Sao_Tome",
  AFRICA_TIMBUKTU = "Africa/Timbuktu",
  AFRICA_TRIPOLI = "Africa/Tripoli",
  AFRICA_TUNIS = "Africa/Tunis",
  AFRICA_WINDHOEK = "Africa/Windhoek",
  AMERICA_ADAK = "America/Adak",
  AMERICA_ANCHORAGE = "America/Anchorage",
  AMERICA_ANGUILLA = "America/Anguilla",
  AMERICA_ANTIGUA = "America/Antigua",
  AMERICA_ARAGUAINA = "America/Araguaina",
  AMERICA_ARGENTINA_BUENOS_AIRES = "America/Argentina/Buenos_Aires",
  AMERICA_ARGENTINA_CATAMARCA = "America/Argentina/Catamarca",
  AMERICA_ARGENTINA_COMOD_RIVADAVIA = "America/Argentina/ComodRivadavia",
  AMERICA_ARGENTINA_CORDOBA = "America/Argentina/Cordoba",
  AMERICA_ARGENTINA_JUJUY = "America/Argentina/Jujuy",
  AMERICA_ARGENTINA_LA_RIOJA = "America/Argentina/La_Rioja",
  AMERICA_ARGENTINA_MENDOZA = "America/Argentina/Mendoza",
  AMERICA_ARGENTINA_RIO_GALLEGOS = "America/Argentina/Rio_Gallegos",
  AMERICA_ARGENTINA_SALTA = "America/Argentina/Salta",
  AMERICA_ARGENTINA_SAN_JUAN = "America/Argentina/San_Juan",
  AMERICA_ARGENTINA_SAN_LUIS = "America/Argentina/San_Luis",
  AMERICA_ARGENTINA_TUCUMAN = "America/Argentina/Tucuman",
  AMERICA_ARGENTINA_USHUAIA = "America/Argentina/Ushuaia",
  AMERICA_ARUBA = "America/Aruba",
  AMERICA_ASUNCION = "America/Asuncion",
  AMERICA_ATIKOKAN = "America/Atikokan",
  AMERICA_ATKA = "America/Atka",
  AMERICA_BAHIA = "America/Bahia",
  AMERICA_BAHIA_BANDERAS = "America/Bahia_Banderas",
  AMERICA_BARBADOS = "America/Barbados",
  AMERICA_BELEM = "America/Belem",
  AMERICA_BELIZE = "America/Belize",
  AMERICA_BLANC_SABLON = "America/Blanc-Sablon",
  AMERICA_BOA_VISTA = "America/Boa_Vista",
  AMERICA_BOGOTA = "America/Bogota",
  AMERICA_BOISE = "America/Boise",
  AMERICA_BUENOS_AIRES = "America/Buenos_Aires",
  AMERICA_CAMBRIDGE_BAY = "America/Cambridge_Bay",
  AMERICA_CAMPO_GRANDE = "America/Campo_Grande",
  AMERICA_CANCUN = "America/Cancun",
  AMERICA_CARACAS = "America/Caracas",
  AMERICA_CATAMARCA = "America/Catamarca",
  AMERICA_CAYENNE = "America/Cayenne",
  AMERICA_CAYMAN = "America/Cayman",
  AMERICA_CHICAGO = "America/Chicago",
  AMERICA_CHIHUAHUA = "America/Chihuahua",
  AMERICA_CIUDAD_JUAREZ = "America/Ciudad_Juarez",
  AMERICA_CORAL_HARBOUR = "America/Coral_Harbour",
  AMERICA_CORDOBA = "America/Cordoba",
  AMERICA_COSTA_RICA = "America/Costa_Rica",
  AMERICA_CRESTON = "America/Creston",
  AMERICA_CUIABA = "America/Cuiaba",
  AMERICA_CURACAO = "America/Curacao",
  AMERICA_DANMARKSHAVN = "America/Danmarkshavn",
  AMERICA_DAWSON = "America/Dawson",
  AMERICA_DAWSON_CREEK = "America/Dawson_Creek",
  AMERICA_DENVER = "America/Denver",
  AMERICA_DETROIT = "America/Detroit",
  AMERICA_DOMINICA = "America/Dominica",
  AMERICA_EDMONTON = "America/Edmonton",
  AMERICA_EIRUNEPE = "America/Eirunepe",
  AMERICA_EL_SALVADOR = "America/El_Salvador",
  AMERICA_ENSENADA = "America/Ensenada",
  AMERICA_FORT_NELSON = "America/Fort_Nelson",
  AMERICA_FORT_WAYNE = "America/Fort_Wayne",
  AMERICA_FORTALEZA = "America/Fortaleza",
  AMERICA_GLACE_BAY = "America/Glace_Bay",
  AMERICA_GODTHAB = "America/Godthab",
  AMERICA_GOOSE_BAY = "America/Goose_Bay",
  AMERICA_GRAND_TURK = "America/Grand_Turk",
  AMERICA_GRENADA = "America/Grenada",
  AMERICA_GUADELOUPE = "America/Guadeloupe",
  AMERICA_GUATEMALA = "America/Guatemala",
  AMERICA_GUAYAQUIL = "America/Guayaquil",
  AMERICA_GUYANA = "America/Guyana",
  AMERICA_HALIFAX = "America/Halifax",
  AMERICA_HAVANA = "America/Havana",
  AMERICA_HERMOSILLO = "America/Hermosillo",
  AMERICA_INDIANA_INDIANAPOLIS = "America/Indiana/Indianapolis",
  AMERICA_INDIANA_KNOX = "America/Indiana/Knox",
  AMERICA_INDIANA_MARENGO = "America/Indiana/Marengo",
  AMERICA_INDIANA_PETERSBURG = "America/Indiana/Petersburg",
  AMERICA_INDIANA_TELL_CITY = "America/Indiana/Tell_City",
  AMERICA_INDIANA_VEVAY = "America/Indiana/Vevay",
  AMERICA_INDIANA_VINCENNES = "America/Indiana/Vincennes",
  AMERICA_INDIANA_WINAMAC = "America/Indiana/Winamac",
  AMERICA_INDIANAPOLIS = "America/Indianapolis",
  AMERICA_INUVIK = "America/Inuvik",
  AMERICA_IQALUIT = "America/Iqaluit",
  AMERICA_JAMAICA = "America/Jamaica",
  AMERICA_JUJUY = "America/Jujuy",
  AMERICA_JUNEAU = "America/Juneau",
  AMERICA_KENTUCKY_LOUISVILLE = "America/Kentucky/Louisville",
  AMERICA_KENTUCKY_MONTICELLO = "America/Kentucky/Monticello",
  AMERICA_KNOX_IN = "America/Knox_IN",
  AMERICA_KRALENDIJK = "America/Kralendijk",
  AMERICA_LA_PAZ = "America/La_Paz",
  AMERICA_LIMA = "America/Lima",
  AMERICA_LOS_ANGELES = "America/Los_Angeles",
  AMERICA_LOUISVILLE = "America/Louisville",
  AMERICA_LOWER_PRINCES = "America/Lower_Princes",
  AMERICA_MACEIO = "America/Maceio",
  AMERICA_MANAGUA = "America/Managua",
  AMERICA_MANAUS = "America/Manaus",
  AMERICA_MARIGOT = "America/Marigot",
  AMERICA_MARTINIQUE = "America/Martinique",
  AMERICA_MATAMOROS = "America/Matamoros",
  AMERICA_MAZATLAN = "America/Mazatlan",
  AMERICA_MENDOZA = "America/Mendoza",
  AMERICA_MENOMINEE = "America/Menominee",
  AMERICA_MERIDA = "America/Merida",
  AMERICA_METLAKATLA = "America/Metlakatla",
  AMERICA_MEXICO_CITY = "America/Mexico_City",
  AMERICA_MIQUELON = "America/Miquelon",
  AMERICA_MONCTON = "America/Moncton",
  AMERICA_MONTERREY = "America/Monterrey",
  AMERICA_MONTEVIDEO = "America/Montevideo",
  AMERICA_MONTREAL = "America/Montreal",
  AMERICA_MONTSERRAT = "America/Montserrat",
  AMERICA_NASSAU = "America/Nassau",
  AMERICA_NEW_YORK = "America/New_York",
  AMERICA_NIPIGON = "America/Nipigon",
  AMERICA_NOME = "America/Nome",
  AMERICA_NORONHA = "America/Noronha",
  AMERICA_NORTH_DAKOTA_BEULAH = "America/North_Dakota/Beulah",
  AMERICA_NORTH_DAKOTA_CENTER = "America/North_Dakota/Center",
  AMERICA_NORTH_DAKOTA_NEW_SALEM = "America/North_Dakota/New_Salem",
  AMERICA_NUUK = "America/Nuuk",
  AMERICA_OJINAGA = "America/Ojinaga",
  AMERICA_PANAMA = "America/Panama",
  AMERICA_PANGNIRTUNG = "America/Pangnirtung",
  AMERICA_PARAMARIBO = "America/Paramaribo",
  AMERICA_PHOENIX = "America/Phoenix",
  AMERICA_PORT_AU_PRINCE = "America/Port-au-Prince",
  AMERICA_PORT_OF_SPAIN = "America/Port_of_Spain",
  AMERICA_PORTO_ACRE = "America/Porto_Acre",
  AMERICA_PORTO_VELHO = "America/Porto_Velho",
  AMERICA_PUERTO_RICO = "America/Puerto_Rico",
  AMERICA_PUNTA_ARENAS = "America/Punta_Arenas",
  AMERICA_RAINY_RIVER = "America/Rainy_River",
  AMERICA_RANKIN_INLET = "America/Rankin_Inlet",
  AMERICA_RECIFE = "America/Recife",
  AMERICA_REGINA = "America/Regina",
  AMERICA_RESOLUTE = "America/Resolute",
  AMERICA_RIO_BRANCO = "America/Rio_Branco",
  AMERICA_ROSARIO = "America/Rosario",
  AMERICA_SANTA_ISABEL = "America/Santa_Isabel",
  AMERICA_SANTAREM = "America/Santarem",
  AMERICA_SANTIAGO = "America/Santiago",
  AMERICA_SANTO_DOMINGO = "America/Santo_Domingo",
  AMERICA_SAO_PAULO = "America/Sao_Paulo",
  AMERICA_SCORESBYSUND = "America/Scoresbysund",
  AMERICA_SHIPROCK = "America/Shiprock",
  AMERICA_SITKA = "America/Sitka",
  AMERICA_ST_BARTHELEMY = "America/St_Barthelemy",
  AMERICA_ST_JOHNS = "America/St_Johns",
  AMERICA_ST_KITTS = "America/St_Kitts",
  AMERICA_ST_LUCIA = "America/St_Lucia",
  AMERICA_ST_THOMAS = "America/St_Thomas",
  AMERICA_ST_VINCENT = "America/St_Vincent",
  AMERICA_SWIFT_CURRENT = "America/Swift_Current",
  AMERICA_TEGUCIGALPA = "America/Tegucigalpa",
  AMERICA_THULE = "America/Thule",
  AMERICA_THUNDER_BAY = "America/Thunder_Bay",
  AMERICA_TIJUANA = "America/Tijuana",
  AMERICA_TORONTO = "America/Toronto",
  AMERICA_TORTOLA = "America/Tortola",
  AMERICA_VANCOUVER = "America/Vancouver",
  AMERICA_VIRGIN = "America/Virgin",
  AMERICA_WHITEHORSE = "America/Whitehorse",
  AMERICA_WINNIPEG = "America/Winnipeg",
  AMERICA_YAKUTAT = "America/Yakutat",
  AMERICA_YELLOWKNIFE = "America/Yellowknife",
  ANTARCTICA_CASEY = "Antarctica/Casey",
  ANTARCTICA_DAVIS = "Antarctica/Davis",
  ANTARCTICA_DUMONT_D_URVILLE = "Antarctica/DumontDUrville",
  ANTARCTICA_MACQUARIE = "Antarctica/Macquarie",
  ANTARCTICA_MAWSON = "Antarctica/Mawson",
  ANTARCTICA_MC_MURDO = "Antarctica/McMurdo",
  ANTARCTICA_PALMER = "Antarctica/Palmer",
  ANTARCTICA_ROTHERA = "Antarctica/Rothera",
  ANTARCTICA_SOUTH_POLE = "Antarctica/South_Pole",
  ANTARCTICA_SYOWA = "Antarctica/Syowa",
  ANTARCTICA_TROLL = "Antarctica/Troll",
  ANTARCTICA_VOSTOK = "Antarctica/Vostok",
  ARCTIC_LONGYEARBYEN = "Arctic/Longyearbyen",
  ASIA_ADEN = "Asia/Aden",
  ASIA_ALMATY = "Asia/Almaty",
  ASIA_AMMAN = "Asia/Amman",
  ASIA_ANADYR = "Asia/Anadyr",
  ASIA_AQTAU = "Asia/Aqtau",
  ASIA_AQTOBE = "Asia/Aqtobe",
  ASIA_ASHGABAT = "Asia/Ashgabat",
  ASIA_ASHKHABAD = "Asia/Ashkhabad",
  ASIA_ATYRAU = "Asia/Atyrau",
  ASIA_BAGHDAD = "Asia/Baghdad",
  ASIA_BAHRAIN = "Asia/Bahrain",
  ASIA_BAKU = "Asia/Baku",
  ASIA_BANGKOK = "Asia/Bangkok",
  ASIA_BARNAUL = "Asia/Barnaul",
  ASIA_BEIRUT = "Asia/Beirut",
  ASIA_BISHKEK = "Asia/Bishkek",
  ASIA_BRUNEI = "Asia/Brunei",
  ASIA_CALCUTTA = "Asia/Calcutta",
  ASIA_CHITA = "Asia/Chita",
  ASIA_CHOIBALSAN = "Asia/Choibalsan",
  ASIA_CHONGQING = "Asia/Chongqing",
  ASIA_CHUNGKING = "Asia/Chungking",
  ASIA_COLOMBO = "Asia/Colombo",
  ASIA_DACCA = "Asia/Dacca",
  ASIA_DAMASCUS = "Asia/Damascus",
  ASIA_DHAKA = "Asia/Dhaka",
  ASIA_DILI = "Asia/Dili",
  ASIA_DUBAI = "Asia/Dubai",
  ASIA_DUSHANBE = "Asia/Dushanbe",
  ASIA_FAMAGUSTA = "Asia/Famagusta",
  ASIA_GAZA = "Asia/Gaza",
  ASIA_HARBIN = "Asia/Harbin",
  ASIA_HEBRON = "Asia/Hebron",
  ASIA_HO_CHI_MINH = "Asia/Ho_Chi_Minh",
  ASIA_HONG_KONG = "Asia/Hong_Kong",
  ASIA_HOVD = "Asia/Hovd",
  ASIA_IRKUTSK = "Asia/Irkutsk",
  ASIA_ISTANBUL = "Asia/Istanbul",
  ASIA_JAKARTA = "Asia/Jakarta",
  ASIA_JAYAPURA = "Asia/Jayapura",
  ASIA_JERUSALEM = "Asia/Jerusalem",
  ASIA_KABUL = "Asia/Kabul",
  ASIA_KAMCHATKA = "Asia/Kamchatka",
  ASIA_KARACHI = "Asia/Karachi",
  ASIA_KASHGAR = "Asia/Kashgar",
  ASIA_KATHMANDU = "Asia/Kathmandu",
  ASIA_KATMANDU = "Asia/Katmandu",
  ASIA_KHANDYGA = "Asia/Khandyga",
  ASIA_KOLKATA = "Asia/Kolkata",
  ASIA_KRASNOYARSK = "Asia/Krasnoyarsk",
  ASIA_KUALA_LUMPUR = "Asia/Kuala_Lumpur",
  ASIA_KUCHING = "Asia/Kuching",
  ASIA_KUWAIT = "Asia/Kuwait",
  ASIA_MACAO = "Asia/Macao",
  ASIA_MACAU = "Asia/Macau",
  ASIA_MAGADAN = "Asia/Magadan",
  ASIA_MAKASSAR = "Asia/Makassar",
  ASIA_MANILA = "Asia/Manila",
  ASIA_MUSCAT = "Asia/Muscat",
  ASIA_NICOSIA = "Asia/Nicosia",
  ASIA_NOVOKUZNETSK = "Asia/Novokuznetsk",
  ASIA_NOVOSIBIRSK = "Asia/Novosibirsk",
  ASIA_OMSK = "Asia/Omsk",
  ASIA_ORAL = "Asia/Oral",
  ASIA_PHNOM_PENH = "Asia/Phnom_Penh",
  ASIA_PONTIANAK = "Asia/Pontianak",
  ASIA_PYONGYANG = "Asia/Pyongyang",
  ASIA_QATAR = "Asia/Qatar",
  ASIA_QOSTANAY = "Asia/Qostanay",
  ASIA_QYZYLORDA = "Asia/Qyzylorda",
  ASIA_RANGOON = "Asia/Rangoon",
  ASIA_RIYADH = "Asia/Riyadh",
  ASIA_SAIGON = "Asia/Saigon",
  ASIA_SAKHALIN = "Asia/Sakhalin",
  ASIA_SAMARKAND = "Asia/Samarkand",
  ASIA_SEOUL = "Asia/Seoul",
  ASIA_SHANGHAI = "Asia/Shanghai",
  ASIA_SINGAPORE = "Asia/Singapore",
  ASIA_SREDNEKOLYMSK = "Asia/Srednekolymsk",
  ASIA_TAIPEI = "Asia/Taipei",
  ASIA_TASHKENT = "Asia/Tashkent",
  ASIA_TBILISI = "Asia/Tbilisi",
  ASIA_TEHRAN = "Asia/Tehran",
  ASIA_TEL_AVIV = "Asia/Tel_Aviv",
  ASIA_THIMBU = "Asia/Thimbu",
  ASIA_THIMPHU = "Asia/Thimphu",
  ASIA_TOKYO = "Asia/Tokyo",
  ASIA_TOMSK = "Asia/Tomsk",
  ASIA_UJUNG_PANDANG = "Asia/Ujung_Pandang",
  ASIA_ULAANBAATAR = "Asia/Ulaanbaatar",
  ASIA_ULAN_BATOR = "Asia/Ulan_Bator",
  ASIA_URUMQI = "Asia/Urumqi",
  ASIA_UST_NERA = "Asia/Ust-Nera",
  ASIA_VIENTIANE = "Asia/Vientiane",
  ASIA_VLADIVOSTOK = "Asia/Vladivostok",
  ASIA_YAKUTSK = "Asia/Yakutsk",
  ASIA_YANGON = "Asia/Yangon",
  ASIA_YEKATERINBURG = "Asia/Yekaterinburg",
  ASIA_YEREVAN = "Asia/Yerevan",
  ATLANTIC_AZORES = "Atlantic/Azores",
  ATLANTIC_BERMUDA = "Atlantic/Bermuda",
  ATLANTIC_CANARY = "Atlantic/Canary",
  ATLANTIC_CAPE_VERDE = "Atlantic/Cape_Verde",
  ATLANTIC_FAEROE = "Atlantic/Faeroe",
  ATLANTIC_FAROE = "Atlantic/Faroe",
  ATLANTIC_JAN_MAYEN = "Atlantic/Jan_Mayen",
  ATLANTIC_MADEIRA = "Atlantic/Madeira",
  ATLANTIC_REYKJAVIK = "Atlantic/Reykjavik",
  ATLANTIC_SOUTH_GEORGIA = "Atlantic/South_Georgia",
  ATLANTIC_ST_HELENA = "Atlantic/St_Helena",
  ATLANTIC_STANLEY = "Atlantic/Stanley",
  AUSTRALIA_ACT = "Australia/ACT",
  AUSTRALIA_ADELAIDE = "Australia/Adelaide",
  AUSTRALIA_BRISBANE = "Australia/Brisbane",
  AUSTRALIA_BROKEN_HILL = "Australia/Broken_Hill",
  AUSTRALIA_CANBERRA = "Australia/Canberra",
  AUSTRALIA_CURRIE = "Australia/Currie",
  AUSTRALIA_DARWIN = "Australia/Darwin",
  AUSTRALIA_EUCLA = "Australia/Eucla",
  AUSTRALIA_HOBART = "Australia/Hobart",
  AUSTRALIA_LHI = "Australia/LHI",
  AUSTRALIA_LINDEMAN = "Australia/Lindeman",
  AUSTRALIA_LORD_HOWE = "Australia/Lord_Howe",
  AUSTRALIA_MELBOURNE = "Australia/Melbourne",
  AUSTRALIA_NSW = "Australia/NSW",
  AUSTRALIA_NORTH = "Australia/North",
  AUSTRALIA_PERTH = "Australia/Perth",
  AUSTRALIA_QUEENSLAND = "Australia/Queensland",
  AUSTRALIA_SOUTH = "Australia/South",
  AUSTRALIA_SYDNEY = "Australia/Sydney",
  AUSTRALIA_TASMANIA = "Australia/Tasmania",
  AUSTRALIA_VICTORIA = "Australia/Victoria",
  AUSTRALIA_WEST = "Australia/West",
  AUSTRALIA_YANCOWINNA = "Australia/Yancowinna",
  BRAZIL_ACRE = "Brazil/Acre",
  BRAZIL_DE_NORONHA = "Brazil/DeNoronha",
  BRAZIL_EAST = "Brazil/East",
  BRAZIL_WEST = "Brazil/West",
  CET = "CET",
  CST6CDT = "CST6CDT",
  CANADA_ATLANTIC = "Canada/Atlantic",
  CANADA_CENTRAL = "Canada/Central",
  CANADA_EASTERN = "Canada/Eastern",
  CANADA_MOUNTAIN = "Canada/Mountain",
  CANADA_NEWFOUNDLAND = "Canada/Newfoundland",
  CANADA_PACIFIC = "Canada/Pacific",
  CANADA_SASKATCHEWAN = "Canada/Saskatchewan",
  CANADA_YUKON = "Canada/Yukon",
  CHILE_CONTINENTAL = "Chile/Continental",
  CHILE_EASTER_ISLAND = "Chile/EasterIsland",
  CUBA = "Cuba",
  EET = "EET",
  EST = "EST",
  EST5EDT = "EST5EDT",
  EGYPT = "Egypt",
  EIRE = "Eire",
  ETC_GMT = "Etc/GMT",
  "ETC_GMT+0" = "Etc/GMT+0",
  "ETC_GMT+1" = "Etc/GMT+1",
  "ETC_GMT+10" = "Etc/GMT+10",
  "ETC_GMT+11" = "Etc/GMT+11",
  "ETC_GMT+12" = "Etc/GMT+12",
  "ETC_GMT+2" = "Etc/GMT+2",
  "ETC_GMT+3" = "Etc/GMT+3",
  "ETC_GMT+4" = "Etc/GMT+4",
  "ETC_GMT+5" = "Etc/GMT+5",
  "ETC_GMT+6" = "Etc/GMT+6",
  "ETC_GMT+7" = "Etc/GMT+7",
  "ETC_GMT+8" = "Etc/GMT+8",
  "ETC_GMT+9" = "Etc/GMT+9",
  ETC_GMT_0 = "Etc/GMT-0",
  ETC_GMT_1 = "Etc/GMT-1",
  ETC_GMT_10 = "Etc/GMT-10",
  ETC_GMT_11 = "Etc/GMT-11",
  ETC_GMT_12 = "Etc/GMT-12",
  ETC_GMT_13 = "Etc/GMT-13",
  ETC_GMT_14 = "Etc/GMT-14",
  ETC_GMT_2 = "Etc/GMT-2",
  ETC_GMT_3 = "Etc/GMT-3",
  ETC_GMT_4 = "Etc/GMT-4",
  ETC_GMT_5 = "Etc/GMT-5",
  ETC_GMT_6 = "Etc/GMT-6",
  ETC_GMT_7 = "Etc/GMT-7",
  ETC_GMT_8 = "Etc/GMT-8",
  ETC_GMT_9 = "Etc/GMT-9",
  ETC_GMT0 = "Etc/GMT0",
  ETC_GREENWICH = "Etc/Greenwich",
  ETC_UCT = "Etc/UCT",
  ETC_UTC = "Etc/UTC",
  ETC_UNIVERSAL = "Etc/Universal",
  ETC_ZULU = "Etc/Zulu",
  EUROPE_AMSTERDAM = "Europe/Amsterdam",
  EUROPE_ANDORRA = "Europe/Andorra",
  EUROPE_ASTRAKHAN = "Europe/Astrakhan",
  EUROPE_ATHENS = "Europe/Athens",
  EUROPE_BELFAST = "Europe/Belfast",
  EUROPE_BELGRADE = "Europe/Belgrade",
  EUROPE_BERLIN = "Europe/Berlin",
  EUROPE_BRATISLAVA = "Europe/Bratislava",
  EUROPE_BRUSSELS = "Europe/Brussels",
  EUROPE_BUCHAREST = "Europe/Bucharest",
  EUROPE_BUDAPEST = "Europe/Budapest",
  EUROPE_BUSINGEN = "Europe/Busingen",
  EUROPE_CHISINAU = "Europe/Chisinau",
  EUROPE_COPENHAGEN = "Europe/Copenhagen",
  EUROPE_DUBLIN = "Europe/Dublin",
  EUROPE_GIBRALTAR = "Europe/Gibraltar",
  EUROPE_GUERNSEY = "Europe/Guernsey",
  EUROPE_HELSINKI = "Europe/Helsinki",
  EUROPE_ISLE_OF_MAN = "Europe/Isle_of_Man",
  EUROPE_ISTANBUL = "Europe/Istanbul",
  EUROPE_JERSEY = "Europe/Jersey",
  EUROPE_KALININGRAD = "Europe/Kaliningrad",
  EUROPE_KIEV = "Europe/Kiev",
  EUROPE_KIROV = "Europe/Kirov",
  EUROPE_KYIV = "Europe/Kyiv",
  EUROPE_LISBON = "Europe/Lisbon",
  EUROPE_LJUBLJANA = "Europe/Ljubljana",
  EUROPE_LONDON = "Europe/London",
  EUROPE_LUXEMBOURG = "Europe/Luxembourg",
  EUROPE_MADRID = "Europe/Madrid",
  EUROPE_MALTA = "Europe/Malta",
  EUROPE_MARIEHAMN = "Europe/Mariehamn",
  EUROPE_MINSK = "Europe/Minsk",
  EUROPE_MONACO = "Europe/Monaco",
  EUROPE_MOSCOW = "Europe/Moscow",
  EUROPE_NICOSIA = "Europe/Nicosia",
  EUROPE_OSLO = "Europe/Oslo",
  EUROPE_PARIS = "Europe/Paris",
  EUROPE_PODGORICA = "Europe/Podgorica",
  EUROPE_PRAGUE = "Europe/Prague",
  EUROPE_RIGA = "Europe/Riga",
  EUROPE_ROME = "Europe/Rome",
  EUROPE_SAMARA = "Europe/Samara",
  EUROPE_SAN_MARINO = "Europe/San_Marino",
  EUROPE_SARAJEVO = "Europe/Sarajevo",
  EUROPE_SARATOV = "Europe/Saratov",
  EUROPE_SIMFEROPOL = "Europe/Simferopol",
  EUROPE_SKOPJE = "Europe/Skopje",
  EUROPE_SOFIA = "Europe/Sofia",
  EUROPE_STOCKHOLM = "Europe/Stockholm",
  EUROPE_TALLINN = "Europe/Tallinn",
  EUROPE_TIRANE = "Europe/Tirane",
  EUROPE_TIRASPOL = "Europe/Tiraspol",
  EUROPE_ULYANOVSK = "Europe/Ulyanovsk",
  EUROPE_UZHGOROD = "Europe/Uzhgorod",
  EUROPE_VADUZ = "Europe/Vaduz",
  EUROPE_VATICAN = "Europe/Vatican",
  EUROPE_VIENNA = "Europe/Vienna",
  EUROPE_VILNIUS = "Europe/Vilnius",
  EUROPE_VOLGOGRAD = "Europe/Volgograd",
  EUROPE_WARSAW = "Europe/Warsaw",
  EUROPE_ZAGREB = "Europe/Zagreb",
  EUROPE_ZAPOROZHYE = "Europe/Zaporozhye",
  EUROPE_ZURICH = "Europe/Zurich",
  GB = "GB",
  GB_EIRE = "GB-Eire",
  GMT = "GMT",
  "GMT+0" = "GMT+0",
  GMT_0 = "GMT-0",
  GMT0 = "GMT0",
  GREENWICH = "Greenwich",
  HST = "HST",
  HONGKONG = "Hongkong",
  ICELAND = "Iceland",
  INDIAN_ANTANANARIVO = "Indian/Antananarivo",
  INDIAN_CHAGOS = "Indian/Chagos",
  INDIAN_CHRISTMAS = "Indian/Christmas",
  INDIAN_COCOS = "Indian/Cocos",
  INDIAN_COMORO = "Indian/Comoro",
  INDIAN_KERGUELEN = "Indian/Kerguelen",
  INDIAN_MAHE = "Indian/Mahe",
  INDIAN_MALDIVES = "Indian/Maldives",
  INDIAN_MAURITIUS = "Indian/Mauritius",
  INDIAN_MAYOTTE = "Indian/Mayotte",
  INDIAN_REUNION = "Indian/Reunion",
  IRAN = "Iran",
  ISRAEL = "Israel",
  JAMAICA = "Jamaica",
  JAPAN = "Japan",
  KWAJALEIN = "Kwajalein",
  LIBYA = "Libya",
  MET = "MET",
  MST = "MST",
  MST7MDT = "MST7MDT",
  MEXICO_BAJA_NORTE = "Mexico/BajaNorte",
  MEXICO_BAJA_SUR = "Mexico/BajaSur",
  MEXICO_GENERAL = "Mexico/General",
  NZ = "NZ",
  NZ_CHAT = "NZ-CHAT",
  NAVAJO = "Navajo",
  PRC = "PRC",
  PST8PDT = "PST8PDT",
  PACIFIC_APIA = "Pacific/Apia",
  PACIFIC_AUCKLAND = "Pacific/Auckland",
  PACIFIC_BOUGAINVILLE = "Pacific/Bougainville",
  PACIFIC_CHATHAM = "Pacific/Chatham",
  PACIFIC_CHUUK = "Pacific/Chuuk",
  PACIFIC_EASTER = "Pacific/Easter",
  PACIFIC_EFATE = "Pacific/Efate",
  PACIFIC_ENDERBURY = "Pacific/Enderbury",
  PACIFIC_FAKAOFO = "Pacific/Fakaofo",
  PACIFIC_FIJI = "Pacific/Fiji",
  PACIFIC_FUNAFUTI = "Pacific/Funafuti",
  PACIFIC_GALAPAGOS = "Pacific/Galapagos",
  PACIFIC_GAMBIER = "Pacific/Gambier",
  PACIFIC_GUADALCANAL = "Pacific/Guadalcanal",
  PACIFIC_GUAM = "Pacific/Guam",
  PACIFIC_HONOLULU = "Pacific/Honolulu",
  PACIFIC_JOHNSTON = "Pacific/Johnston",
  PACIFIC_KANTON = "Pacific/Kanton",
  PACIFIC_KIRITIMATI = "Pacific/Kiritimati",
  PACIFIC_KOSRAE = "Pacific/Kosrae",
  PACIFIC_KWAJALEIN = "Pacific/Kwajalein",
  PACIFIC_MAJURO = "Pacific/Majuro",
  PACIFIC_MARQUESAS = "Pacific/Marquesas",
  PACIFIC_MIDWAY = "Pacific/Midway",
  PACIFIC_NAURU = "Pacific/Nauru",
  PACIFIC_NIUE = "Pacific/Niue",
  PACIFIC_NORFOLK = "Pacific/Norfolk",
  PACIFIC_NOUMEA = "Pacific/Noumea",
  PACIFIC_PAGO_PAGO = "Pacific/Pago_Pago",
  PACIFIC_PALAU = "Pacific/Palau",
  PACIFIC_PITCAIRN = "Pacific/Pitcairn",
  PACIFIC_POHNPEI = "Pacific/Pohnpei",
  PACIFIC_PONAPE = "Pacific/Ponape",
  PACIFIC_PORT_MORESBY = "Pacific/Port_Moresby",
  PACIFIC_RAROTONGA = "Pacific/Rarotonga",
  PACIFIC_SAIPAN = "Pacific/Saipan",
  PACIFIC_SAMOA = "Pacific/Samoa",
  PACIFIC_TAHITI = "Pacific/Tahiti",
  PACIFIC_TARAWA = "Pacific/Tarawa",
  PACIFIC_TONGATAPU = "Pacific/Tongatapu",
  PACIFIC_TRUK = "Pacific/Truk",
  PACIFIC_WAKE = "Pacific/Wake",
  PACIFIC_WALLIS = "Pacific/Wallis",
  PACIFIC_YAP = "Pacific/Yap",
  POLAND = "Poland",
  PORTUGAL = "Portugal",
  ROC = "ROC",
  ROK = "ROK",
  SINGAPORE = "Singapore",
  TURKEY = "Turkey",
  UCT = "UCT",
  US_ALASKA = "US/Alaska",
  US_ALEUTIAN = "US/Aleutian",
  US_ARIZONA = "US/Arizona",
  US_CENTRAL = "US/Central",
  US_EAST_INDIANA = "US/East-Indiana",
  US_EASTERN = "US/Eastern",
  US_HAWAII = "US/Hawaii",
  US_INDIANA_STARKE = "US/Indiana-Starke",
  US_MICHIGAN = "US/Michigan",
  US_MOUNTAIN = "US/Mountain",
  US_PACIFIC = "US/Pacific",
  US_SAMOA = "US/Samoa",
  UTC = "UTC",
  UNIVERSAL = "Universal",
  W_SU = "W-SU",
  WET = "WET",
  ZULU = "Zulu",
}

/**
 * A registration token for a site.
 */
export type Token = {
  id: number;
  value: string;
  audience: string;
  purpose: string;
  expired: string;
  created: string;
  site_id?: number | null;
};

/**
 * List of existing tokens.
 */
export type TokensGetResponse = {
  total: number;
  page: number;
  size: number;
  items: Array<Token>;
};

/**
 * Request to create one or more tokens, with a certain validity.
 */
export type TokensPostRequest = {
  count?: number;
  duration: string;
};

/**
 * Response containing generated tokens.
 */
export type TokensPostResponse = {
  items: Array<Token>;
};

export type UnauthorizedErrorBodyResponse = {
  code?: ExceptionCode;
  message?: string;
  details?: Array<BaseExceptionDetail> | null;
};

export type UnauthorizedErrorResponseModel = {
  error: UnauthorizedErrorBodyResponse;
};

/**
 * A user.
 */
export type User = {
  id: number;
  email: string;
  username: string;
  full_name: string;
  is_admin: boolean;
};

/**
 * List of existing users.
 */
export type UsersGetResponse = {
  total: number;
  page: number;
  size: number;
  items: Array<User>;
};

/**
 * User password change schema.
 */
export type UsersPasswordPatchRequest = {
  current_password: string;
  new_password: string;
  confirm_password: string;
};

/**
 * User Edit Details about themselves.
 */
export type UsersPatchMeRequest = {
  username?: string | null;
  full_name?: string | null;
  email?: string | null;
};

/**
 * Request to edit details for a User.
 */
export type UsersPatchRequest = {
  full_name?: string | null;
  username?: string | null;
  email?: string | null;
  password?: string | null;
  confirm_password?: string | null;
  is_admin?: boolean | null;
};

/**
 * Request to create a User.
 */
export type UsersPostRequest = {
  full_name: string;
  username: string;
  email: string;
  password: string;
  confirm_password: string;
  is_admin?: boolean;
};

export type ValidationErrorBodyResponse = {
  code?: ExceptionCode;
  message?: string;
  details?: Array<BaseExceptionDetail> | null;
};

export type ValidationErrorResponseModel = {
  error: ValidationErrorBodyResponse;
};

export type GetBootAssetsV1BootassetsGetData = {
  body?: never;
  path?: never;
  query?: {
    sort_by?: string | null;
    page?: number;
    size?: number;
    boot_source_id?: Array<number> | null;
    kind?: Array<BootAssetKind> | null;
    label?: Array<BootAssetLabel> | null;
    os?: Array<string> | null;
    arch?: Array<string> | null;
    release?: Array<string> | null;
  };
  url: "/v1/bootassets";
};

export type GetBootAssetsV1BootassetsGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetBootAssetsV1BootassetsGetError =
  GetBootAssetsV1BootassetsGetErrors[keyof GetBootAssetsV1BootassetsGetErrors];

export type GetBootAssetsV1BootassetsGetResponses = {
  /**
   * Successful Response
   */
  200: BootAssetsGetResponse;
};

export type GetBootAssetsV1BootassetsGetResponse =
  GetBootAssetsV1BootassetsGetResponses[keyof GetBootAssetsV1BootassetsGetResponses];

export type PostBootAssetsV1BootassetsPostData = {
  body: BootAssetsPostRequest;
  path?: never;
  query?: never;
  url: "/v1/bootassets";
};

export type PostBootAssetsV1BootassetsPostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostBootAssetsV1BootassetsPostError =
  PostBootAssetsV1BootassetsPostErrors[keyof PostBootAssetsV1BootassetsPostErrors];

export type PostBootAssetsV1BootassetsPostResponses = {
  /**
   * Successful Response
   */
  200: BootAssetsPostResponse;
};

export type PostBootAssetsV1BootassetsPostResponse =
  PostBootAssetsV1BootassetsPostResponses[keyof PostBootAssetsV1BootassetsPostResponses];

export type GetBootSourcesV1BootassetSourcesGetData = {
  body?: never;
  path?: never;
  query?: {
    sort_by?: string | null;
    page?: number;
    size?: number;
  };
  url: "/v1/bootasset-sources";
};

export type GetBootSourcesV1BootassetSourcesGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetBootSourcesV1BootassetSourcesGetError =
  GetBootSourcesV1BootassetSourcesGetErrors[keyof GetBootSourcesV1BootassetSourcesGetErrors];

export type GetBootSourcesV1BootassetSourcesGetResponses = {
  /**
   * Successful Response
   */
  200: BootSourcesGetResponse;
};

export type GetBootSourcesV1BootassetSourcesGetResponse =
  GetBootSourcesV1BootassetSourcesGetResponses[keyof GetBootSourcesV1BootassetSourcesGetResponses];

export type PostBootSourcesV1BootassetSourcesPostData = {
  body: BootSourcesPostRequest;
  path?: never;
  query?: never;
  url: "/v1/bootasset-sources";
};

export type PostBootSourcesV1BootassetSourcesPostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostBootSourcesV1BootassetSourcesPostError =
  PostBootSourcesV1BootassetSourcesPostErrors[keyof PostBootSourcesV1BootassetSourcesPostErrors];

export type PostBootSourcesV1BootassetSourcesPostResponses = {
  /**
   * Successful Response
   */
  200: BootSourcesPostResponse;
};

export type PostBootSourcesV1BootassetSourcesPostResponse =
  PostBootSourcesV1BootassetSourcesPostResponses[keyof PostBootSourcesV1BootassetSourcesPostResponses];

export type GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    sort_by?: string | null;
    page?: number;
    size?: number;
  };
  url: "/v1/bootasset-sources/{id}/selections";
};

export type GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetError =
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetErrors[keyof GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetErrors];

export type GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponses = {
  /**
   * Successful Response
   */
  200: BootSourceSelectionsGetResponse;
};

export type GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponse =
  GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponses[keyof GetBootSourceSelectionsV1BootassetSourcesIdSelectionsGetResponses];

export type PostBootAssetVersionV1BootassetsIdVersionsPostData = {
  body: BootAssetVersionPostRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/bootassets/{id}/versions";
};

export type PostBootAssetVersionV1BootassetsIdVersionsPostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostBootAssetVersionV1BootassetsIdVersionsPostError =
  PostBootAssetVersionV1BootassetsIdVersionsPostErrors[keyof PostBootAssetVersionV1BootassetsIdVersionsPostErrors];

export type PostBootAssetVersionV1BootassetsIdVersionsPostResponses = {
  /**
   * Successful Response
   */
  200: BootAssetVersionPostResponse;
};

export type PostBootAssetVersionV1BootassetsIdVersionsPostResponse =
  PostBootAssetVersionV1BootassetsIdVersionsPostResponses[keyof PostBootAssetVersionV1BootassetsIdVersionsPostResponses];

export type GetBootAssetVersionsV1BootassetVersionsGetData = {
  body?: never;
  path?: never;
  query?: {
    sort_by?: string | null;
    page?: number;
    size?: number;
    boot_asset_id?: Array<number> | null;
    version?: Array<string> | null;
  };
  url: "/v1/bootasset-versions";
};

export type GetBootAssetVersionsV1BootassetVersionsGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetBootAssetVersionsV1BootassetVersionsGetError =
  GetBootAssetVersionsV1BootassetVersionsGetErrors[keyof GetBootAssetVersionsV1BootassetVersionsGetErrors];

export type GetBootAssetVersionsV1BootassetVersionsGetResponses = {
  /**
   * Successful Response
   */
  200: BootAssetVersionsGetResponse;
};

export type GetBootAssetVersionsV1BootassetVersionsGetResponse =
  GetBootAssetVersionsV1BootassetVersionsGetResponses[keyof GetBootAssetVersionsV1BootassetVersionsGetResponses];

export type PostBootAssetItemV1BootassetVersionsIdItemsPostData = {
  body: BootAssetItemPostRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/bootasset-versions/{id}/items";
};

export type PostBootAssetItemV1BootassetVersionsIdItemsPostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostBootAssetItemV1BootassetVersionsIdItemsPostError =
  PostBootAssetItemV1BootassetVersionsIdItemsPostErrors[keyof PostBootAssetItemV1BootassetVersionsIdItemsPostErrors];

export type PostBootAssetItemV1BootassetVersionsIdItemsPostResponses = {
  /**
   * Successful Response
   */
  200: BootAssetItemPostResponse;
};

export type PostBootAssetItemV1BootassetVersionsIdItemsPostResponse =
  PostBootAssetItemV1BootassetVersionsIdItemsPostResponses[keyof PostBootAssetItemV1BootassetVersionsIdItemsPostResponses];

export type GetBootAssetItemsV1BootassetItemsGetData = {
  body?: never;
  path?: never;
  query?: {
    sort_by?: string | null;
    page?: number;
    size?: number;
    boot_asset_version_id?: Array<number> | null;
    ftype?: Array<string> | null;
    sha256?: Array<string> | null;
    path?: Array<string> | null;
    file_size?: Array<number> | null;
  };
  url: "/v1/bootasset-items";
};

export type GetBootAssetItemsV1BootassetItemsGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetBootAssetItemsV1BootassetItemsGetError =
  GetBootAssetItemsV1BootassetItemsGetErrors[keyof GetBootAssetItemsV1BootassetItemsGetErrors];

export type GetBootAssetItemsV1BootassetItemsGetResponses = {
  /**
   * Successful Response
   */
  200: BootAssetItemsGetResponse;
};

export type GetBootAssetItemsV1BootassetItemsGetResponse =
  GetBootAssetItemsV1BootassetItemsGetResponses[keyof GetBootAssetItemsV1BootassetItemsGetResponses];

export type DeleteImagesV1BootassetItemsIdDeleteData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/bootasset-items/{id}";
};

export type DeleteImagesV1BootassetItemsIdDeleteErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteImagesV1BootassetItemsIdDeleteError =
  DeleteImagesV1BootassetItemsIdDeleteErrors[keyof DeleteImagesV1BootassetItemsIdDeleteErrors];

export type DeleteImagesV1BootassetItemsIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PatchBootAssetItemsV1BootassetItemsIdPatchData = {
  body: BootAssetItemPatchRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/bootasset-items/{id}";
};

export type PatchBootAssetItemsV1BootassetItemsIdPatchErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchBootAssetItemsV1BootassetItemsIdPatchError =
  PatchBootAssetItemsV1BootassetItemsIdPatchErrors[keyof PatchBootAssetItemsV1BootassetItemsIdPatchErrors];

export type PatchBootAssetItemsV1BootassetItemsIdPatchResponses = {
  /**
   * Successful Response
   */
  200: BootAssetItem;
};

export type PatchBootAssetItemsV1BootassetItemsIdPatchResponse =
  PatchBootAssetItemsV1BootassetItemsIdPatchResponses[keyof PatchBootAssetItemsV1BootassetItemsIdPatchResponses];

export type PostImagesV1BootassetItemsBootAssetVersionIdPostData = {
  body?: never;
  path: {
    boot_asset_version_id: number;
  };
  query?: never;
  url: "/v1/bootasset-items/{boot_asset_version_id}";
};

export type PostImagesV1BootassetItemsBootAssetVersionIdPostErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostImagesV1BootassetItemsBootAssetVersionIdPostError =
  PostImagesV1BootassetItemsBootAssetVersionIdPostErrors[keyof PostImagesV1BootassetItemsBootAssetVersionIdPostErrors];

export type PostImagesV1BootassetItemsBootAssetVersionIdPostResponses = {
  /**
   * Successful Response
   */
  200: BootAssetItem;
};

export type PostImagesV1BootassetItemsBootAssetVersionIdPostResponse =
  PostImagesV1BootassetItemsBootAssetVersionIdPostResponses[keyof PostImagesV1BootassetItemsBootAssetVersionIdPostResponses];

export type PostV1LoginPostData = {
  body: BodyPostV1LoginPost;
  path?: never;
  query?: never;
  url: "/v1/login";
};

export type PostV1LoginPostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostV1LoginPostError = PostV1LoginPostErrors[keyof PostV1LoginPostErrors];

export type PostV1LoginPostResponses = {
  /**
   * Successful Response
   */
  200: AccessTokenResponse;
};

export type PostV1LoginPostResponse = PostV1LoginPostResponses[keyof PostV1LoginPostResponses];

export type GetV1SettingsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/settings";
};

export type GetV1SettingsGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
};

export type GetV1SettingsGetError = GetV1SettingsGetErrors[keyof GetV1SettingsGetErrors];

export type GetV1SettingsGetResponses = {
  /**
   * Successful Response
   */
  200: Settings;
};

export type GetV1SettingsGetResponse = GetV1SettingsGetResponses[keyof GetV1SettingsGetResponses];

export type PatchV1SettingsPatchData = {
  body: SettingsUpdate;
  path?: never;
  query?: never;
  url: "/v1/settings";
};

export type PatchV1SettingsPatchErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchV1SettingsPatchError = PatchV1SettingsPatchErrors[keyof PatchV1SettingsPatchErrors];

export type PatchV1SettingsPatchResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetPendingV1SitesPendingGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
  };
  url: "/v1/sites/pending";
};

export type GetPendingV1SitesPendingGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetPendingV1SitesPendingGetError =
  GetPendingV1SitesPendingGetErrors[keyof GetPendingV1SitesPendingGetErrors];

export type GetPendingV1SitesPendingGetResponses = {
  /**
   * Successful Response
   */
  200: PendingSitesGetResponse;
};

export type GetPendingV1SitesPendingGetResponse =
  GetPendingV1SitesPendingGetResponses[keyof GetPendingV1SitesPendingGetResponses];

export type PostPendingV1SitesPendingPostData = {
  body: PendingSitesPostRequest;
  path?: never;
  query?: never;
  url: "/v1/sites/pending";
};

export type PostPendingV1SitesPendingPostErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostPendingV1SitesPendingPostError =
  PostPendingV1SitesPendingPostErrors[keyof PostPendingV1SitesPendingPostErrors];

export type PostPendingV1SitesPendingPostResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type PostPendingV1SitesPendingPostResponse =
  PostPendingV1SitesPendingPostResponses[keyof PostPendingV1SitesPendingPostResponses];

export type DeleteManyV1SitesDeleteData = {
  body?: never;
  path?: never;
  query: {
    ids: Array<number>;
  };
  url: "/v1/sites";
};

export type DeleteManyV1SitesDeleteErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteManyV1SitesDeleteError = DeleteManyV1SitesDeleteErrors[keyof DeleteManyV1SitesDeleteErrors];

export type DeleteManyV1SitesDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteManyV1SitesDeleteResponse = DeleteManyV1SitesDeleteResponses[keyof DeleteManyV1SitesDeleteResponses];

export type GetV1SitesGetData = {
  body?: never;
  path?: never;
  query?: {
    coordinates?: boolean | null;
    page?: number;
    size?: number;
    city?: Array<string> | null;
    country?: Array<string> | null;
    name?: Array<string> | null;
    note?: Array<string> | null;
    state?: Array<string> | null;
    address?: Array<string> | null;
    postal_code?: Array<string> | null;
    timezone?: Array<string> | null;
    url?: Array<string> | null;
    cluster_uuid?: Array<string> | null;
    q?: string | null;
    sort_by?: string | null;
  };
  url: "/v1/sites";
};

export type GetV1SitesGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetV1SitesGetError = GetV1SitesGetErrors[keyof GetV1SitesGetErrors];

export type GetV1SitesGetResponses = {
  /**
   * Successful Response
   */
  200: SitesGetResponse;
};

export type GetV1SitesGetResponse = GetV1SitesGetResponses[keyof GetV1SitesGetResponses];

export type GetCoordinatesV1SitesCoordinatesGetData = {
  body?: never;
  path?: never;
  query?: {
    city?: Array<string> | null;
    country?: Array<string> | null;
    name?: Array<string> | null;
    note?: Array<string> | null;
    state?: Array<string> | null;
    address?: Array<string> | null;
    postal_code?: Array<string> | null;
    timezone?: Array<string> | null;
    url?: Array<string> | null;
    cluster_uuid?: Array<string> | null;
    q?: string | null;
  };
  url: "/v1/sites/coordinates";
};

export type GetCoordinatesV1SitesCoordinatesGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetCoordinatesV1SitesCoordinatesGetError =
  GetCoordinatesV1SitesCoordinatesGetErrors[keyof GetCoordinatesV1SitesCoordinatesGetErrors];

export type GetCoordinatesV1SitesCoordinatesGetResponses = {
  /**
   * Successful Response
   */
  200: Array<SiteCoordinates>;
};

export type GetCoordinatesV1SitesCoordinatesGetResponse =
  GetCoordinatesV1SitesCoordinatesGetResponses[keyof GetCoordinatesV1SitesCoordinatesGetResponses];

export type DeleteV1SitesIdDeleteData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/sites/{id}";
};

export type DeleteV1SitesIdDeleteErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteV1SitesIdDeleteError = DeleteV1SitesIdDeleteErrors[keyof DeleteV1SitesIdDeleteErrors];

export type DeleteV1SitesIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteV1SitesIdDeleteResponse = DeleteV1SitesIdDeleteResponses[keyof DeleteV1SitesIdDeleteResponses];

export type GetIdV1SitesIdGetData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/sites/{id}";
};

export type GetIdV1SitesIdGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetIdV1SitesIdGetError = GetIdV1SitesIdGetErrors[keyof GetIdV1SitesIdGetErrors];

export type GetIdV1SitesIdGetResponses = {
  /**
   * Successful Response
   */
  200: Site;
};

export type GetIdV1SitesIdGetResponse = GetIdV1SitesIdGetResponses[keyof GetIdV1SitesIdGetResponses];

export type PatchV1SitesIdPatchData = {
  body: SiteUpdateRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/sites/{id}";
};

export type PatchV1SitesIdPatchErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchV1SitesIdPatchError = PatchV1SitesIdPatchErrors[keyof PatchV1SitesIdPatchErrors];

export type PatchV1SitesIdPatchResponses = {
  /**
   * Successful Response
   */
  200: Site;
};

export type PatchV1SitesIdPatchResponse = PatchV1SitesIdPatchResponses[keyof PatchV1SitesIdPatchResponses];

export type DeleteManyV1TokensDeleteData = {
  body?: never;
  path?: never;
  query: {
    ids: Array<number>;
  };
  url: "/v1/tokens";
};

export type DeleteManyV1TokensDeleteErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteManyV1TokensDeleteError = DeleteManyV1TokensDeleteErrors[keyof DeleteManyV1TokensDeleteErrors];

export type DeleteManyV1TokensDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteManyV1TokensDeleteResponse =
  DeleteManyV1TokensDeleteResponses[keyof DeleteManyV1TokensDeleteResponses];

export type GetV1TokensGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
    id?: Array<number> | null;
    value?: Array<string> | null;
    site_id?: Array<number> | null;
  };
  url: "/v1/tokens";
};

export type GetV1TokensGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetV1TokensGetError = GetV1TokensGetErrors[keyof GetV1TokensGetErrors];

export type GetV1TokensGetResponses = {
  /**
   * Successful Response
   */
  200: TokensGetResponse;
};

export type GetV1TokensGetResponse = GetV1TokensGetResponses[keyof GetV1TokensGetResponses];

export type PostV1TokensPostData = {
  body: TokensPostRequest;
  path?: never;
  query?: never;
  url: "/v1/tokens";
};

export type PostV1TokensPostErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostV1TokensPostError = PostV1TokensPostErrors[keyof PostV1TokensPostErrors];

export type PostV1TokensPostResponses = {
  /**
   * Successful Response
   */
  200: TokensPostResponse;
};

export type PostV1TokensPostResponse = PostV1TokensPostResponses[keyof PostV1TokensPostResponses];

export type GetExportV1TokensExportGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
    id?: Array<number> | null;
    value?: Array<string> | null;
    site_id?: Array<number> | null;
  };
  url: "/v1/tokens/export";
};

export type GetExportV1TokensExportGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetExportV1TokensExportGetError = GetExportV1TokensExportGetErrors[keyof GetExportV1TokensExportGetErrors];

export type GetExportV1TokensExportGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteV1TokensIdDeleteData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/tokens/{id}";
};

export type DeleteV1TokensIdDeleteErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteV1TokensIdDeleteError = DeleteV1TokensIdDeleteErrors[keyof DeleteV1TokensIdDeleteErrors];

export type DeleteV1TokensIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteV1TokensIdDeleteResponse = DeleteV1TokensIdDeleteResponses[keyof DeleteV1TokensIdDeleteResponses];

export type GetV1UsersGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
    email?: Array<string> | null;
    username?: Array<string> | null;
    full_name?: Array<string> | null;
    is_admin?: Array<boolean> | null;
    sort_by?: string | null;
    search_text?: string;
  };
  url: "/v1/users";
};

export type GetV1UsersGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetV1UsersGetError = GetV1UsersGetErrors[keyof GetV1UsersGetErrors];

export type GetV1UsersGetResponses = {
  /**
   * Successful Response
   */
  200: UsersGetResponse;
};

export type GetV1UsersGetResponse = GetV1UsersGetResponses[keyof GetV1UsersGetResponses];

export type PostV1UsersPostData = {
  body: UsersPostRequest;
  path?: never;
  query?: never;
  url: "/v1/users";
};

export type PostV1UsersPostErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PostV1UsersPostError = PostV1UsersPostErrors[keyof PostV1UsersPostErrors];

export type PostV1UsersPostResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type PostV1UsersPostResponse = PostV1UsersPostResponses[keyof PostV1UsersPostResponses];

export type GetMeV1UsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/users/me";
};

export type GetMeV1UsersMeGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
};

export type GetMeV1UsersMeGetError = GetMeV1UsersMeGetErrors[keyof GetMeV1UsersMeGetErrors];

export type GetMeV1UsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type GetMeV1UsersMeGetResponse = GetMeV1UsersMeGetResponses[keyof GetMeV1UsersMeGetResponses];

export type PatchMeV1UsersMePatchData = {
  body: UsersPatchMeRequest;
  path?: never;
  query?: never;
  url: "/v1/users/me";
};

export type PatchMeV1UsersMePatchErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchMeV1UsersMePatchError = PatchMeV1UsersMePatchErrors[keyof PatchMeV1UsersMePatchErrors];

export type PatchMeV1UsersMePatchResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type PatchMeV1UsersMePatchResponse = PatchMeV1UsersMePatchResponses[keyof PatchMeV1UsersMePatchResponses];

export type PatchMePasswordV1UsersMePasswordPatchData = {
  body: UsersPasswordPatchRequest;
  path?: never;
  query?: never;
  url: "/v1/users/me/password";
};

export type PatchMePasswordV1UsersMePasswordPatchErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchMePasswordV1UsersMePasswordPatchError =
  PatchMePasswordV1UsersMePasswordPatchErrors[keyof PatchMePasswordV1UsersMePasswordPatchErrors];

export type PatchMePasswordV1UsersMePasswordPatchResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteV1UsersIdDeleteData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/users/{id}";
};

export type DeleteV1UsersIdDeleteErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type DeleteV1UsersIdDeleteError = DeleteV1UsersIdDeleteErrors[keyof DeleteV1UsersIdDeleteErrors];

export type DeleteV1UsersIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteV1UsersIdDeleteResponse = DeleteV1UsersIdDeleteResponses[keyof DeleteV1UsersIdDeleteResponses];

export type GetIdV1UsersIdGetData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/users/{id}";
};

export type GetIdV1UsersIdGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type GetIdV1UsersIdGetError = GetIdV1UsersIdGetErrors[keyof GetIdV1UsersIdGetErrors];

export type GetIdV1UsersIdGetResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type GetIdV1UsersIdGetResponse = GetIdV1UsersIdGetResponses[keyof GetIdV1UsersIdGetResponses];

export type PatchV1UsersIdPatchData = {
  body: UsersPatchRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/v1/users/{id}";
};

export type PatchV1UsersIdPatchErrors = {
  /**
   * Bad Request
   */
  400: BadRequestErrorResponseModel;
  /**
   * Unauthorized
   */
  401: UnauthorizedErrorResponseModel;
  /**
   * Forbidden
   */
  403: ForbiddenErrorResponseModel;
  /**
   * Not Found
   */
  404: NotFoundErrorResponseModel;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponseModel;
};

export type PatchV1UsersIdPatchError = PatchV1UsersIdPatchErrors[keyof PatchV1UsersIdPatchErrors];

export type PatchV1UsersIdPatchResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type PatchV1UsersIdPatchResponse = PatchV1UsersIdPatchResponses[keyof PatchV1UsersIdPatchResponses];

export type ClientOptions = {
  baseURL: `${string}://${string}/api` | (string & {});
};
