name: Rock Builder

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to build
        required: true
        type: string

jobs:
  build-rock:
    runs-on: ubuntu-24.04
    env:
      BRANCH: ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.ref_name }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ env.BRANCH }}
      - name: Install dependencies
        run: |
          snap install rockcraft --classic
          snap install yq
      - name: Build rock(s)
        run: |
          rockcraft pack -v
          rock_file=$(find -name "*.rock" -exec basename {} \;)
          image_name=$(cat ./rockcraft.yaml | yq .name)
          if [ "${BRANCH}" = "main" ]; then
            version="latest"
          else
            version=$(cat ./rockcraft.yaml | yq .version)
          fi
          rockcraft.skopeo --insecure-policy copy \
            --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            "oci-archive:${rock_file}" \
            "docker://ghcr.io/canonical/${image_name}:${version}"
          echo "Published rock ${image_name}:${version}"
